<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Dr Muhammad Saufi">
<meta name="dcterms.date" content="2024-06-07">
<title>Linear Mixed Models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="Linear Mixed Models_files/libs/clipboard/clipboard.min.js"></script>
<script src="Linear Mixed Models_files/libs/quarto-html/quarto.js"></script>
<script src="Linear Mixed Models_files/libs/quarto-html/popper.min.js"></script>
<script src="Linear Mixed Models_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Linear Mixed Models_files/libs/quarto-html/anchor.min.js"></script>
<link href="Linear Mixed Models_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Linear Mixed Models_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="Linear Mixed Models_files/libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="Linear Mixed Models_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Linear Mixed Models_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Linear Mixed Models_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="Linear Mixed Models_files/libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script src="Linear%20Mixed%20Models_files/libs/kePrint-0.0.1/kePrint.js"></script><link href="Linear%20Mixed%20Models_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="1"><h2 id="toc-title">Contents</h2>
   
  <ul>
<li><a href="#loading-packages" id="toc-loading-packages" class="nav-link active" data-scroll-target="#loading-packages"><span class="header-section-number">1</span> Loading Packages</a></li>
  <li>
<a href="#dataset" id="toc-dataset" class="nav-link" data-scroll-target="#dataset"><span class="header-section-number">2</span> Dataset</a>
  <ul>
<li><a href="#load-the-dataset" id="toc-load-the-dataset" class="nav-link" data-scroll-target="#load-the-dataset"><span class="header-section-number">2.1</span> Load the Dataset</a></li>
  <li><a href="#data-wrangling" id="toc-data-wrangling" class="nav-link" data-scroll-target="#data-wrangling"><span class="header-section-number">2.2</span> Data Wrangling</a></li>
  <li>
<a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis"><span class="header-section-number">2.3</span> Exploratory Data Analysis</a>
  <ul>
<li><a href="#descriptive-table" id="toc-descriptive-table" class="nav-link" data-scroll-target="#descriptive-table"><span class="header-section-number">2.3.1</span> Descriptive Table</a></li>
  <li><a href="#plot-1" id="toc-plot-1" class="nav-link" data-scroll-target="#plot-1"><span class="header-section-number">2.3.2</span> Plot 1</a></li>
  <li><a href="#plot-2" id="toc-plot-2" class="nav-link" data-scroll-target="#plot-2"><span class="header-section-number">2.3.3</span> Plot 2</a></li>
  </ul>
</li>
  </ul>
</li>
  <li>
<a href="#multilevel-model" id="toc-multilevel-model" class="nav-link" data-scroll-target="#multilevel-model"><span class="header-section-number">3</span> Multilevel Model</a>
  <ul>
<li><a href="#null-model-simplest-model" id="toc-null-model-simplest-model" class="nav-link" data-scroll-target="#null-model-simplest-model"><span class="header-section-number">3.1</span> Null Model (Simplest Model)</a></li>
  <li><a href="#single-level-analysis" id="toc-single-level-analysis" class="nav-link" data-scroll-target="#single-level-analysis"><span class="header-section-number">3.2</span> Single-Level Analysis</a></li>
  <li>
<a href="#multilevel-analysis" id="toc-multilevel-analysis" class="nav-link" data-scroll-target="#multilevel-analysis"><span class="header-section-number">3.3</span> Multilevel Analysis</a>
  <ul>
<li>
<a href="#random-intercept-models" id="toc-random-intercept-models" class="nav-link" data-scroll-target="#random-intercept-models"><span class="header-section-number">3.3.1</span> Random Intercept Models</a>
  <ul class="collapse">
<li><a href="#add-an-explanatory-variable" id="toc-add-an-explanatory-variable" class="nav-link" data-scroll-target="#add-an-explanatory-variable"><span class="header-section-number">3.3.1.1</span> Add an Explanatory Variable</a></li>
  <li>
<a href="#prediction" id="toc-prediction" class="nav-link" data-scroll-target="#prediction"><span class="header-section-number">3.3.1.2</span> Prediction</a>
  <ul class="collapse">
<li><a href="#steps-for-prediction" id="toc-steps-for-prediction" class="nav-link" data-scroll-target="#steps-for-prediction"><span class="header-section-number">3.3.1.2.1</span> Steps for Prediction</a></li>
  <li><a href="#explanation" id="toc-explanation" class="nav-link" data-scroll-target="#explanation"><span class="header-section-number">3.3.1.2.2</span> Explanation</a></li>
  <li><a href="#confirmation-with-manual-calculation" id="toc-confirmation-with-manual-calculation" class="nav-link" data-scroll-target="#confirmation-with-manual-calculation"><span class="header-section-number">3.3.1.2.3</span> Confirmation with Manual Calculation</a></li>
  </ul>
</li>
  <li><a href="#plot" id="toc-plot" class="nav-link" data-scroll-target="#plot"><span class="header-section-number">3.3.1.3</span> Plot</a></li>
  <li>
<a href="#variance" id="toc-variance" class="nav-link" data-scroll-target="#variance"><span class="header-section-number">3.3.1.4</span> Variance</a>
  <ul class="collapse">
<li><a href="#between-school-variance" id="toc-between-school-variance" class="nav-link" data-scroll-target="#between-school-variance"><span class="header-section-number">3.3.1.4.1</span> Between School Variance</a></li>
  <li><a href="#within-school-variance" id="toc-within-school-variance" class="nav-link" data-scroll-target="#within-school-variance"><span class="header-section-number">3.3.1.4.2</span> Within School Variance</a></li>
  </ul>
</li>
  </ul>
</li>
  </ul>
</li>
  </ul>
</li>
  </ul></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Linear Mixed Models</h1>
<p class="subtitle lead">Advanced Numerical Data Analysis</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Dr Muhammad Saufi </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 7, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header><section id="loading-packages" class="level1" data-number="1"><h1 data-number="1">
<span class="header-section-number">1</span> Loading Packages</h1>
<div class="cell">
<details class="code-fold"><summary>Show the code</summary><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://haven.tidyverse.org">haven</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<details class="code-fold"><summary>Show the code</summary><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/bbolker/broom.mixed">broom.mixed</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://here.r-lib.org/">here</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stderr">
<pre><code>here() starts at D:/OneDrive/My Education/R Learning Hub/DrPH Epidemiology Revision</code></pre>
</div>
<details class="code-fold"><summary>Show the code</summary><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/ddsjoberg/gtsummary">gtsummary</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/rstudio/DT">DT</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://haozhu233.github.io/kableExtra/">kableExtra</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'kableExtra'

The following object is masked from 'package:dplyr':

    group_rows</code></pre>
</div>
<details class="code-fold"><summary>Show the code</summary><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/lme4/lme4/">lme4</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stderr">
<pre><code>Loading required package: Matrix

Attaching package: 'Matrix'

The following objects are masked from 'package:tidyr':

    expand, pack, unpack</code></pre>
</div>
<details class="code-fold"><summary>Show the code</summary><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/runehaubo/lmerTestR">lmerTest</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'lmerTest'

The following object is masked from 'package:lme4':

    lmer

The following object is masked from 'package:stats':

    step</code></pre>
</div>
<details class="code-fold"><summary>Show the code</summary><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section><section id="dataset" class="level1" data-number="2"><h1 data-number="2">
<span class="header-section-number">2</span> Dataset</h1>
<p>The dataset is from the Scottish School Leavers Survey (SSLS). It is a longitudinal dataset that captures information on several cohorts of young people over time.</p>
<p><strong>Hierarchy</strong>: The dataset has a hierarchical structure with students (level 1) nested within schools (level 2).</p>
<ul>
<li>
<strong>Level 1 (Students)</strong>: Individual students identified by <code>caseid</code>.</li>
<li>
<strong>Level 2 (Schools)</strong>: Schools identified by <code>schoolid</code>.</li>
</ul>
<p><strong>Dependent Variable</strong>:</p>
<ul>
<li>
<code>score</code>: Total attainment score of the student, ranging from 0 to 75.</li>
</ul>
<p><strong>Explanatory Variables</strong>:</p>
<ul>
<li>
<code>cohort90</code>: Year of the cohort, represented by subtracting 1990 from each value. Values range from -6 (1984) to 8 (1998), with 0 representing 1990.</li>
<li>
<code>female</code>: Gender of the student (1 = female, 0 = male).</li>
<li>
<code>sclass</code>: Social class of the student, defined as the higher class of mother or father (1 = managerial and professional, 2 = intermediate, 3 = working, 4 = unclassified).</li>
<li>
<code>schtype</code>: Type of school (1 = independent, 0 = state-funded).</li>
<li>
<code>schurban</code>: Urban-rural classification of the school (1 = urban, 0 = town or rural).</li>
<li>
<code>schdenom</code>: School denomination (1 = Roman Catholic, 0 = non-denominational).</li>
</ul>
<section id="load-the-dataset" class="level2" data-number="2.1"><h2 data-number="2.1" class="anchored" data-anchor-id="load-the-dataset">
<span class="header-section-number">2.1</span> Load the Dataset</h2>
<div class="cell">
<details class="code-fold"><summary>Show the code</summary><div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">score.sch</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://haven.tidyverse.org/reference/read_dta.html">read_dta</a></span><span class="op">(</span><span class="st">"score.sch_data.dta"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">score.sch</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Rows: 33,988
Columns: 9
$ caseid   &lt;dbl&gt; 18, 17, 19, 20, 21, 13, 16, 14, 15, 12, 12865, 6509, 12866, 1…
$ schoolid &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ score    &lt;dbl&gt; 0, 10, 0, 40, 42, 4, 0, 0, 14, 27, 18, 23, 24, 0, 25, 4, 11, …
$ cohort90 &lt;dbl&gt; -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -2, -4, -2, -2, -4, -…
$ female   &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0…
$ sclass   &lt;dbl&gt; 2, 2, 4, 3, 2, 2, 3, 4, 3, 2, 2, 1, 2, 3, 2, 3, 2, 4, 3, 3, 3…
$ schtype  &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ schurban &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ schdenom &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…</code></pre>
</div>
</div>
</section><section id="data-wrangling" class="level2" data-number="2.2"><h2 data-number="2.2" class="anchored" data-anchor-id="data-wrangling">
<span class="header-section-number">2.2</span> Data Wrangling</h2>
<p>Numerical variables are often converted to factors to facilitate easier analysis and interpretation.</p>
<div class="cell">
<details class="code-fold"><summary>Show the code</summary><div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">score.sch</span> <span class="op">&lt;-</span> <span class="va">score.sch</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>    female2 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">female</span>, labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'male'</span>, <span class="st">'female'</span><span class="op">)</span><span class="op">)</span>,</span>
<span>    class2 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">sclass</span>, labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'managerial+prof'</span>, <span class="st">'intermediate'</span>, <span class="st">'working'</span>, <span class="st">'unclassified'</span><span class="op">)</span><span class="op">)</span>,</span>
<span>    schtype2 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">schtype</span>, labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'state-funded'</span>, <span class="st">'independent'</span><span class="op">)</span><span class="op">)</span>,</span>
<span>    schurban2 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">schurban</span>, labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'town/rural'</span>, <span class="st">'urban'</span><span class="op">)</span><span class="op">)</span>,</span>
<span>    schdenom2 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">schdenom</span>, labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'state-funded'</span>, <span class="st">'independent'</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">score.sch</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Rows: 33,988
Columns: 14
$ caseid    &lt;dbl&gt; 18, 17, 19, 20, 21, 13, 16, 14, 15, 12, 12865, 6509, 12866, …
$ schoolid  &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ score     &lt;dbl&gt; 0, 10, 0, 40, 42, 4, 0, 0, 14, 27, 18, 23, 24, 0, 25, 4, 11,…
$ cohort90  &lt;dbl&gt; -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -2, -4, -2, -2, -4, …
$ female    &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ sclass    &lt;dbl&gt; 2, 2, 4, 3, 2, 2, 3, 4, 3, 2, 2, 1, 2, 3, 2, 3, 2, 4, 3, 3, …
$ schtype   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ schurban  &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ schdenom  &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ female2   &lt;fct&gt; female, female, female, female, female, female, female, fema…
$ class2    &lt;fct&gt; intermediate, intermediate, unclassified, working, intermedi…
$ schtype2  &lt;fct&gt; state-funded, state-funded, state-funded, state-funded, stat…
$ schurban2 &lt;fct&gt; urban, urban, urban, urban, urban, urban, urban, urban, urba…
$ schdenom2 &lt;fct&gt; state-funded, state-funded, state-funded, state-funded, stat…</code></pre>
</div>
</div>
</section><section id="exploratory-data-analysis" class="level2" data-number="2.3"><h2 data-number="2.3" class="anchored" data-anchor-id="exploratory-data-analysis">
<span class="header-section-number">2.3</span> Exploratory Data Analysis</h2>
<p>Summarize the data and create some basic plots.</p>
<section id="descriptive-table" class="level3" data-number="2.3.1"><h3 data-number="2.3.1" class="anchored" data-anchor-id="descriptive-table">
<span class="header-section-number">2.3.1</span> Descriptive Table</h3>
<div class="cell">
<details class="code-fold"><summary>Show the code</summary><div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">score.sch</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://www.danieldsjoberg.com/gtsummary/reference/tbl_summary.html">tbl_summary</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div>
<div id="jqakstpklj" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#jqakstpklj table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#jqakstpklj thead, #jqakstpklj tbody, #jqakstpklj tfoot, #jqakstpklj tr, #jqakstpklj td, #jqakstpklj th {
  border-style: none;
}

#jqakstpklj p {
  margin: 0;
  padding: 0;
}

#jqakstpklj .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#jqakstpklj .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#jqakstpklj .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#jqakstpklj .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#jqakstpklj .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#jqakstpklj .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#jqakstpklj .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#jqakstpklj .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#jqakstpklj .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#jqakstpklj .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#jqakstpklj .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#jqakstpklj .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#jqakstpklj .gt_spanner_row {
  border-bottom-style: hidden;
}

#jqakstpklj .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#jqakstpklj .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#jqakstpklj .gt_from_md > :first-child {
  margin-top: 0;
}

#jqakstpklj .gt_from_md > :last-child {
  margin-bottom: 0;
}

#jqakstpklj .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#jqakstpklj .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#jqakstpklj .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#jqakstpklj .gt_row_group_first td {
  border-top-width: 2px;
}

#jqakstpklj .gt_row_group_first th {
  border-top-width: 2px;
}

#jqakstpklj .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#jqakstpklj .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#jqakstpklj .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#jqakstpklj .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#jqakstpklj .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#jqakstpklj .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#jqakstpklj .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#jqakstpklj .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#jqakstpklj .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#jqakstpklj .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#jqakstpklj .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#jqakstpklj .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#jqakstpklj .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#jqakstpklj .gt_left {
  text-align: left;
}

#jqakstpklj .gt_center {
  text-align: center;
}

#jqakstpklj .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#jqakstpklj .gt_font_normal {
  font-weight: normal;
}

#jqakstpklj .gt_font_bold {
  font-weight: bold;
}

#jqakstpklj .gt_font_italic {
  font-style: italic;
}

#jqakstpklj .gt_super {
  font-size: 65%;
}

#jqakstpklj .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#jqakstpklj .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#jqakstpklj .gt_indent_1 {
  text-indent: 5px;
}

#jqakstpklj .gt_indent_2 {
  text-indent: 10px;
}

#jqakstpklj .gt_indent_3 {
  text-indent: 15px;
}

#jqakstpklj .gt_indent_4 {
  text-indent: 20px;
}

#jqakstpklj .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead><tr class="header gt_col_headings">
<th id="<strong>Characteristic</strong>" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><strong>Characteristic</strong></th>
<th id="<strong>N = 33,988</strong><span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">
<strong>N = 33,988</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span>
</th>
</tr></thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="label">Case ID</td>
<td class="gt_row gt_center" headers="stat_0">17,319 (8,532, 29,428)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">School ID</td>
<td class="gt_row gt_center" headers="stat_0">256 (123, 386)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">Score</td>
<td class="gt_row gt_center" headers="stat_0">33 (19, 45)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">Cohort</td>
<td class="gt_row gt_center" headers="stat_0"><br></td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;-6</td>
<td class="gt_row gt_center" headers="stat_0">6,478 (19%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;-4</td>
<td class="gt_row gt_center" headers="stat_0">6,325 (19%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;-2</td>
<td class="gt_row gt_center" headers="stat_0">5,245 (15%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;0</td>
<td class="gt_row gt_center" headers="stat_0">4,371 (13%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;6</td>
<td class="gt_row gt_center" headers="stat_0">4,244 (12%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;8</td>
<td class="gt_row gt_center" headers="stat_0">7,325 (22%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">Female</td>
<td class="gt_row gt_center" headers="stat_0">17,933 (53%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">Social class</td>
<td class="gt_row gt_center" headers="stat_0"><br></td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;1</td>
<td class="gt_row gt_center" headers="stat_0">11,173 (33%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;2</td>
<td class="gt_row gt_center" headers="stat_0">9,994 (29%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;3</td>
<td class="gt_row gt_center" headers="stat_0">9,486 (28%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;4</td>
<td class="gt_row gt_center" headers="stat_0">3,335 (9.8%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">School type</td>
<td class="gt_row gt_center" headers="stat_0">1,540 (4.5%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">School urban-rural classification</td>
<td class="gt_row gt_center" headers="stat_0">24,116 (71%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">School denomination</td>
<td class="gt_row gt_center" headers="stat_0">5,358 (16%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">female2</td>
<td class="gt_row gt_center" headers="stat_0"><br></td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;male</td>
<td class="gt_row gt_center" headers="stat_0">16,055 (47%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;female</td>
<td class="gt_row gt_center" headers="stat_0">17,933 (53%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">class2</td>
<td class="gt_row gt_center" headers="stat_0"><br></td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;managerial+prof</td>
<td class="gt_row gt_center" headers="stat_0">11,173 (33%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;intermediate</td>
<td class="gt_row gt_center" headers="stat_0">9,994 (29%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;working</td>
<td class="gt_row gt_center" headers="stat_0">9,486 (28%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;unclassified</td>
<td class="gt_row gt_center" headers="stat_0">3,335 (9.8%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">schtype2</td>
<td class="gt_row gt_center" headers="stat_0"><br></td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;state-funded</td>
<td class="gt_row gt_center" headers="stat_0">32,448 (95%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;independent</td>
<td class="gt_row gt_center" headers="stat_0">1,540 (4.5%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">schurban2</td>
<td class="gt_row gt_center" headers="stat_0"><br></td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;town/rural</td>
<td class="gt_row gt_center" headers="stat_0">9,872 (29%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;urban</td>
<td class="gt_row gt_center" headers="stat_0">24,116 (71%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">schdenom2</td>
<td class="gt_row gt_center" headers="stat_0"><br></td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;state-funded</td>
<td class="gt_row gt_center" headers="stat_0">28,630 (84%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;independent</td>
<td class="gt_row gt_center" headers="stat_0">5,358 (16%)</td>
</tr>
</tbody>
<tfoot class="gt_footnotes"><tr class="odd">
<td colspan="2" class="gt_footnote">
<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> Median (IQR); n (%)</td>
</tr></tfoot>
</table>
</div>
</div>
</div>
</div>
</section><section id="plot-1" class="level3" data-number="2.3.2"><h3 data-number="2.3.2" class="anchored" data-anchor-id="plot-1">
<span class="header-section-number">2.3.2</span> Plot 1</h3>
<div class="cell">
<details class="code-fold"><summary>Show the code</summary><div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">score.sch</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">cohort90</span>, y <span class="op">=</span> <span class="va">score</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="va">lm</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="Linear-Mixed-Models_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Comment:</strong> This graph displays the relationship between <code>cohort90</code> and <code>score</code>, along with a fitted linear regression line. The graph suggests that student attainment scores have generally increased over the years from 1984 to 1998. However, there is a substantial amount of variability in the scores within each cohort year. The positive slope of the regression line quantifies the trend of improvement in scores over time.</p>
</section><section id="plot-2" class="level3" data-number="2.3.3"><h3 data-number="2.3.3" class="anchored" data-anchor-id="plot-2">
<span class="header-section-number">2.3.3</span> Plot 2</h3>
<div class="cell">
<details class="code-fold"><summary>Show the code</summary><div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">score.sch</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">cohort90</span>, y <span class="op">=</span> <span class="va">score</span>, col <span class="op">=</span> <span class="va">female</span>, group <span class="op">=</span> <span class="va">female</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="va">lm</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="Linear-Mixed-Models_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Comment:</strong> This graph shows the relationship between <code>cohort90</code> and <code>score</code>, with a distinction between male and female students. The graph indicates that both male and female students have experienced improvements in attainment scores over the years from 1984 to 1998. The trends for both genders are very similar, suggesting that gender does not play a significant role in the difference in attainment scores within this dataset. The upward slope of both lines quantifies the overall improvement in scores over time, and the color differentiation helps visualize the gender distribution within each cohort.</p>
</section></section></section><section id="multilevel-model" class="level1" data-number="3"><h1 data-number="3">
<span class="header-section-number">3</span> Multilevel Model</h1>
<p>Multilevel model, also known as a hierarchical linear model or mixed-effects model, accounts for the nested structure of the data. In this dataset, students are nested within schools.</p>
<section id="null-model-simplest-model" class="level2" data-number="3.1"><h2 data-number="3.1" class="anchored" data-anchor-id="null-model-simplest-model">
<span class="header-section-number">3.1</span> Null Model (Simplest Model)</h2>
<p>The simplest form of a multilevel model is the null model, which does not include any explanatory variables. It only includes random intercepts for the groups (schools in this case). The null model helps in understanding how much of the total variance in the outcome variable (score) can be attributed to differences between groups (schools).</p>
<p>The equation for the null model is: <span class="math display">\[
score_{ij} = \beta_0 + u_{0j} + e_{ij}
\]</span></p>
<ul>
<li>
<span class="math inline">\(score_{ij}\)</span> is the attainment score of student <span class="math inline">\(i\)</span> in school <span class="math inline">\(j\)</span>.</li>
<li>
<span class="math inline">\(\beta_0\)</span> is the overall mean score across all schools.</li>
<li>
<span class="math inline">\(u_{0j}\)</span> is the random effect for school <span class="math inline">\(j\)</span>, capturing the deviation of school <span class="math inline">\(j\)</span>’s mean score from the overall mean.</li>
<li>
<span class="math inline">\(e_{ij}\)</span> is the residual error term for student <span class="math inline">\(i\)</span> in school <span class="math inline">\(j\)</span>.</li>
</ul></section><section id="single-level-analysis" class="level2" data-number="3.2"><h2 data-number="3.2" class="anchored" data-anchor-id="single-level-analysis">
<span class="header-section-number">3.2</span> Single-Level Analysis</h2>
<p>A single-level analysis uses a standard linear regression model assuming that all data points are independent and the outcome is normally distributed.</p>
<div class="cell">
<details class="code-fold"><summary>Show the code</summary><div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m.lm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">score</span> <span class="op">~</span> <span class="fl">1</span>, data <span class="op">=</span> <span class="va">score.sch</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m.lm</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = score ~ 1, data = score.sch)

Residuals:
    Min      1Q  Median      3Q     Max 
-31.095 -12.095   1.905  13.905  43.905 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 31.09462    0.09392   331.1   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 17.31 on 33987 degrees of freedom</code></pre>
</div>
</div>
<p><strong>Summary of the Output</strong></p>
<ol type="1">
<li>
<p><strong>Call</strong>: <code>lm(formula = score ~ 1, data = score.sch)</code></p>
<ul>
<li>This indicates that a linear model is being fitted with <code>score</code> as the response variable and no predictors (only an intercept).</li>
</ul>
</li>
<li>
<p><strong>Residuals</strong>: The residuals section provides a summary of the distribution of the residuals (differences between observed and predicted values):</p>
<ul>
<li>
<strong>Min</strong>: -31.095</li>
<li>
<strong>1Q (First Quartile)</strong>: -12.095</li>
<li>
<strong>Median</strong>: 1.905</li>
<li>
<strong>3Q (Third Quartile)</strong>: 13.905</li>
<li>
<strong>Max</strong>: 43.905</li>
</ul>
</li>
<li>
<p><strong>Coefficients</strong>: The coefficients section provides the estimate of the model’s intercept:</p>
<ul>
<li>
<strong>Estimate</strong>: 31.09462 This is the estimated mean score for all students.</li>
<li>
<strong>Std. Error</strong>: 0.09392 This is the standard error of the intercept estimate, indicating the precision of the estimate.</li>
<li>
<strong>t value</strong>: 331.1 This is the t-statistic for testing whether the intercept is significantly different from zero.</li>
<li>
<strong>Pr(&gt;|t|)</strong>: &lt;2e-16 This is the p-value associated with the t-statistic, indicating that the intercept is highly significant (p &lt; 0.001).</li>
</ul>
</li>
<li>
<p><strong>Residual Standard Error</strong>:</p>
<ul>
<li>
<strong>Residual standard error</strong>: 17.31 on 33987 degrees of freedom</li>
<li>This value measures the average distance that the observed scores fall from the regression line (mean score). A lower residual standard error indicates a better fit.</li>
</ul>
</li>
<li>
<p><strong>Interpretation</strong>:</p>
<ol type="i">
<li><p><strong>Overall Mean Score</strong>: The overall mean score for students is estimated to be 31.09462. This value is statistically significant, as indicated by the extremely small p-value (p &lt; 0.001).</p></li>
<li><p><strong>Residuals</strong>: The residuals indicate the spread of the differences between observed scores and the estimated mean score. The range of residuals (-31.095 to 43.905) suggests variability in scores around the mean.</p></li>
<li><p><strong>Model Fit</strong>: The residual standard error of 17.31 suggests that there is considerable variability in student scores around the mean. This model does not account for any grouping structure (such as schools), meaning it assumes all observations are independent.</p></li>
</ol>
</li>
<li>
<p><strong>Equation</strong>:</p>
<ul>
<li><span class="math inline">\(\hat{\text{score}} = \beta_0\)</span></li>
<li><span class="math inline">\(\hat{\text{score}} = 31.09462\)</span></li>
</ul>
</li>
<li><p><strong>Conclusion</strong>: The single-level analysis provides an estimate of the overall mean score (31.09462) for all students, which is highly significant. However, the residual standard error and the spread of residuals indicate that there is substantial variability in scores that is not explained by this simple model. This highlights the potential need for a more complex model, such as a multilevel model, to account for the nested structure of the data and potentially explain some of the variability in scores.</p></li>
</ol></section><section id="multilevel-analysis" class="level2" data-number="3.3"><h2 data-number="3.3" class="anchored" data-anchor-id="multilevel-analysis">
<span class="header-section-number">3.3</span> Multilevel Analysis</h2>
<p>Multilevel analysis (also known as hierarchical linear modeling or mixed-effects modeling) is used to analyze data that has a nested structure. In this dataset, students are nested within schools. This type of analysis allows us to account for variability at both the student level and the school level, providing more accurate estimates and inferences.</p>
<ol type="1">
<li><p><strong>Fixed Effects:</strong> The overall mean score <span class="math inline">\(\beta_0\)</span> is estimated. These are the effects that are assumed to be constant across all groups. For example, the average effect of a variable like cohort90 on score across all students and schools.</p></li>
<li><p><strong>Random Effects:</strong> These allow for variability between groups. For example, different schools may have different baseline scores (intercepts), and the effect of cohort90 on score may vary between schools.</p></li>
</ol>
<ul>
<li>
<strong>Between-School Variance</strong>: Variance due to differences between schools <span class="math inline">\(u_{0j}\)</span>.</li>
<li>
<strong>Within-School Variance</strong>: Variance due to differences within schools <span class="math inline">\(e_{ij}\)</span>.</li>
</ul>
<div class="cell">
<details class="code-fold"><summary>Show the code</summary><div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m0</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/lmerTest/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">score</span> <span class="op">~</span> <span class="fl">1</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">schoolid</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">score.sch</span>, REML <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m0</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite's
  method [lmerModLmerTest]
Formula: score ~ 1 + (1 | schoolid)
   Data: score.sch

      AIC       BIC    logLik  deviance  df.resid 
 286545.1  286570.4 -143269.5  286539.1     33985 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.9763 -0.7010  0.1017  0.7391  3.0817 

Random effects:
 Groups   Name        Variance Std.Dev.
 schoolid (Intercept)  61.02    7.812  
 Residual             258.36   16.073  
Number of obs: 33988, groups:  schoolid, 508

Fixed effects:
            Estimate Std. Error       df t value Pr(&gt;|t|)    
(Intercept)  30.6006     0.3694 451.5326   82.83   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>Summary of the Output</strong></p>
<ol type="1">
<li><p><strong>Fixed Effects</strong>: The estimated overall mean score across all schools is 30.6006. This value is statistically significant with a very small p-value (&lt; 2e-16), indicating that the mean score is significantly different from zero.</p></li>
<li>
<p><strong>Random Effects</strong></p>
<ul>
<li>The variance of the school-level intercepts (i.e., the variability in the mean scores between schools) is 61.02, with a standard deviation of 7.812.</li>
<li>The variance of the residual errors (i.e., the variability in scores within schools) is 258.36, with a standard deviation of 16.073.</li>
</ul>
</li>
<li>
<p><strong>Model Fit Statistics</strong></p>
<ul>
<li>
<strong>AIC</strong>: 286545.1, <strong>BIC</strong>: 286570.4</li>
<li>These statistics provide measures of the model fit. Lower AIC and BIC values indicate a better-fitting model.</li>
</ul>
</li>
<li><p><strong>Scaled Residuals</strong>: These are the quartiles of the residuals, which provide information about the distribution of the residuals.</p></li>
<li>
<p><strong>Interpretation</strong></p>
<ol type="i">
<li><p><strong>Overall Mean Score</strong>: The overall mean score for students across all schools is 30.6006, which is statistically significant.</p></li>
<li>
<p><strong>Variance Components</strong>:</p>
<ul>
<li>The between-school variance (61.02) indicates that there is variability in mean scores between different schools.</li>
<li>The within-school variance (258.36) indicates that there is substantial variability in scores within schools.</li>
</ul>
</li>
<li><p><strong>Intraclass Correlation Coefficient (ICC)</strong>: <span class="math display">\[
\text{ICC} = \frac{\sigma^2_{\text{between}}}{\sigma^2_{\text{between}} + \sigma^2_{\text{within}}} = \frac{61.02}{61.02 + 258.36} \approx 0.191
\]</span></p></li>
</ol>
<ul>
<li>The ICC can be calculated to understand the proportion of total variance that is attributable to the grouping structure (schools in this case).</li>
<li>Approximately 19.1% of the total variance in scores is attributable to differences between schools, while the remaining 80.9% is due to differences within schools.</li>
</ul>
</li>
<li>
<p><strong>Equation</strong> <span class="math inline">\({score}_{ij} = 30.6006 + u_{0j} + e_{ij}\)</span></p>
<ul>
<li>
<span class="math inline">\(\beta_0 = 30.6006\)</span> is the fixed effect (overall mean score).</li>
<li>
<span class="math inline">\(u_{0j} \sim N(0, 61.02)\)</span> is the random effect for school ( j ) with a variance of 61.02.</li>
<li>
<span class="math inline">\(e_{ij} \sim N(0, 258.36)\)</span> is the residual error term for student ( i ) in school ( j ) with a variance of 258.36.</li>
</ul>
</li>
<li><p><strong>Conclusion</strong>: The multilevel analysis shows that there is significant variability in student scores both within and between schools. The mean score across all schools is estimated to be 30.6006, with substantial variability observed within schools and some variability observed between schools. The intraclass correlation coefficient (ICC) indicates that a meaningful proportion (19.1%) of the total variance in scores can be attributed to differences between schools. This justifies the use of a multilevel model, as it captures the hierarchical structure of the data and provides a more nuanced understanding of the variability in student scores.</p></li>
</ol>
<section id="random-intercept-models" class="level3" data-number="3.3.1"><h3 data-number="3.3.1" class="anchored" data-anchor-id="random-intercept-models">
<span class="header-section-number">3.3.1</span> Random Intercept Models</h3>
<p>Random intercept models are a type of multilevel model where each group (e.g., school) has its own intercept but shares the same slope for explanatory variables. This allows the model to account for the fact that different groups may have different baseline levels of the outcome variable.</p>
<section id="add-an-explanatory-variable" class="level4" data-number="3.3.1.1"><h4 data-number="3.3.1.1" class="anchored" data-anchor-id="add-an-explanatory-variable">
<span class="header-section-number">3.3.1.1</span> Add an Explanatory Variable</h4>
<p>Adding an explanatory variable (predictor) to the random intercept model helps to explain some of the variability in the outcome variable. This allows us to understand how much of the variability is due to the predictor, in addition to the variability captured by the random intercepts.</p>
<p><span class="math display">\[
\text{score}_{ij} = \beta_0 + \beta_1 \text{cohort90}_{ij} + u_{0j} + e_{ij}
\]</span> This equation represents a random intercept model with one explanatory variable (<code>cohort90</code>):</p>
<ul>
<li>
<span class="math inline">\(\text{score}_{ij}\)</span>: The score for student <span class="math inline">\(i\)</span> in school <span class="math inline">\(j\)</span>.</li>
<li>
<span class="math inline">\(\beta_0\)</span>: The overall intercept, representing the average score when all predictors are zero. This is the fixed effect for the intercept.</li>
<li>
<span class="math inline">\(\beta_1 \text{cohort90}_{ij}\)</span>: The fixed effect of the explanatory variable <code>cohort90</code> on the score. <span class="math inline">\(\beta_1\)</span> is the coefficient that quantifies how much the score changes with each unit change in <code>cohort90</code>.</li>
<li>
<span class="math inline">\(u_{0j}\)</span>: The random effect for school <span class="math inline">\(j\)</span>. This term captures the deviation of school <span class="math inline">\(j\)</span>’s intercept from the overall intercept <span class="math inline">\(\beta_0\)</span>. It accounts for the fact that different schools may have different baseline scores.</li>
<li>
<span class="math inline">\(e_{ij}\)</span>: The residual error term for student <span class="math inline">\(i\)</span> in school <span class="math inline">\(j\)</span>. This term captures the deviation of the individual student’s score from their school’s mean score, after accounting for the effects of <code>cohort90</code> and the school-level random intercept.</li>
</ul>
<div class="cell">
<details class="code-fold"><summary>Show the code</summary><div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Adding an explanatory variable (cohort90)</span></span>
<span><span class="va">ri_model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/lmerTest/man/lmer.html">lmer</a></span><span class="op">(</span><span class="va">score</span> <span class="op">~</span> <span class="va">cohort90</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">schoolid</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">score.sch</span>, REML <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">ri_model</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite's
  method [lmerModLmerTest]
Formula: score ~ cohort90 + (1 | schoolid)
   Data: score.sch

      AIC       BIC    logLik  deviance  df.resid 
 280921.6  280955.3 -140456.8  280913.6     33984 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-3.1487 -0.7242  0.0363  0.7339  3.7097 

Random effects:
 Groups   Name        Variance Std.Dev.
 schoolid (Intercept)  45.99    6.781  
 Residual             219.29   14.808  
Number of obs: 33988, groups:  schoolid, 508

Fixed effects:
             Estimate Std. Error        df t value Pr(&gt;|t|)    
(Intercept) 3.056e+01  3.225e-01 4.326e+02   94.74   &lt;2e-16 ***
cohort90    1.215e+00  1.553e-02 3.392e+04   78.24   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
         (Intr)
cohort90 -0.002</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold"><summary>Show the code</summary><div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="va">ri_model</span>, conf.int <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="va">kbl</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/kable_styling.html">kable_styling</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div>
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">effect</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">group</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">conf.low</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">conf.high</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">fixed</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">30.559151</td>
<td style="text-align: right;">0.3225430</td>
<td style="text-align: right;">94.74442</td>
<td style="text-align: right;">432.5598</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">29.925204</td>
<td style="text-align: right;">31.193097</td>
</tr>
<tr class="even">
<td style="text-align: left;">fixed</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">cohort90</td>
<td style="text-align: right;">1.214954</td>
<td style="text-align: right;">0.0155293</td>
<td style="text-align: right;">78.23636</td>
<td style="text-align: right;">33924.8362</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.184517</td>
<td style="text-align: right;">1.245392</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ran_pars</td>
<td style="text-align: left;">schoolid</td>
<td style="text-align: left;">sd__(Intercept)</td>
<td style="text-align: right;">6.781462</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">ran_pars</td>
<td style="text-align: left;">Residual</td>
<td style="text-align: left;">sd__Observation</td>
<td style="text-align: right;">14.808372</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><strong>Summary of the Output</strong></p>
<ol type="1">
<li>
<p><strong>Fixed Effects</strong>:</p>
<ul>
<li>
<strong>(Intercept)</strong>: The estimated overall mean score when <code>cohort90</code> is zero is 30.56. This value is statistically significant with a very small p-value (&lt; 2e-16), indicating that the intercept is significantly different from zero.</li>
<li>
<strong>cohort90</strong>: The coefficient for <code>cohort90</code> is 1.215. This means that for each unit increase in <code>cohort90</code>, the score increases by 1.215 points on average. This effect is also highly significant (p &lt; 2e-16).</li>
</ul>
</li>
<li>
<p><strong>Random Effects</strong>:</p>
<ul>
<li>
<strong>schoolid (Intercept)</strong>: <strong>Variance</strong>: 45.99, <strong>Std.Dev.</strong>: 6.781. This indicates that the variance of the school-level intercepts (i.e., the variability in the mean scores between schools) is 45.99, with a standard deviation of 6.781.</li>
<li>
<strong>Residual</strong>: <strong>Variance</strong>: 219.29, <strong>Std.Dev.</strong>: 14.808. This indicates the variance of the residual errors (i.e., the variability in scores within schools) is 219.29, with a standard deviation of 14.808.</li>
<li>
<strong>Number of Observations</strong>: 33,988 students</li>
<li>
<strong>Number of Groups (schools)</strong>: 508 schools</li>
</ul>
</li>
<li>
<p><strong>Model Fit Statistics</strong>: These statistics provide measures of the model fit. Lower AIC and BIC values indicate a better-fitting model.</p>
<ul>
<li>
<strong>AIC</strong>: 280921.6, <strong>BIC</strong>: 280955.3</li>
</ul>
</li>
<li>
<p><strong>Scaled Residuals</strong>: These are the quartiles of the residuals, which provide information about the distribution of the residuals.</p>
<ul>
<li>
<strong>Min</strong>: -3.1487, <strong>1Q</strong>: -0.7242, <strong>Median</strong>: 0.0363, <strong>3Q</strong>: 0.7339, <strong>Max</strong>: 3.7097</li>
</ul>
</li>
<li>
<p><strong>Interpretation</strong>:</p>
<ol type="i">
<li>
<strong>Overall Mean Score</strong>: The overall mean score for students, when <code>cohort90</code> is zero, is estimated to be 30.56.</li>
<li>
<strong>Effect of cohort90</strong>: The score increases by 1.215 points for each unit increase in <code>cohort90</code>. This indicates a positive relationship between <code>cohort90</code> and <code>score</code>.</li>
<li>
<strong>Variance Components</strong>: The variance of the school-level random intercepts is 45.99, indicating variability in mean scores between schools. The residual variance is 219.29, indicating variability in scores within schools.</li>
<li>
<strong>Intraclass Correlation Coefficient (ICC)</strong>: Approximately 17.3% of the total variance in scores is attributable to differences between schools, while the remaining 82.7% is due to differences within schools. <span class="math display">\[
\text{ICC} = \frac{\sigma^2_{\text{between}}}{\sigma^2_{\text{between}} + \sigma^2_{\text{within}}} = \frac{45.99}{45.99 + 219.29} \approx 0.173
\]</span>
</li>
<li>
<strong>Model Fit</strong>: The model fit statistics (AIC, BIC, logLik, deviance) suggest that the model fits the data reasonably well. Lower AIC and BIC values compared to other models would indicate a better fit.</li>
</ol>
</li>
<li><p><strong>Conclusion</strong>: The random intercept model with <code>cohort90</code> as an explanatory variable shows that there is significant variability in student scores both within and between schools. The average score increases with higher values of <code>cohort90</code>, suggesting a positive trend over time or across cohorts. The random intercepts capture the variability between schools, and the residual variance captures the variability within schools. The intraclass correlation coefficient (ICC) indicates that a meaningful proportion of the variance in scores is due to differences between schools, justifying the use of a multilevel model.</p></li>
</ol></section><section id="prediction" class="level4" data-number="3.3.1.2"><h4 data-number="3.3.1.2" class="anchored" data-anchor-id="prediction">
<span class="header-section-number">3.3.1.2</span> Prediction</h4>
<p>In multilevel modeling, the goal of prediction is to estimate the outcome variable (in this case, <code>score</code>) for each individual observation by considering both the fixed effects and the random effects. This allows for more accurate predictions by taking into account the hierarchical structure of the data. The general form of the prediction equation in a random intercept model with one explanatory variable (<code>cohort90</code>) is: <span class="math display">\[
\text{score}_{ij} = \beta_0 + \beta_1 \text{cohort90}_{ij} + u_{0j} + e_{ij}
\]</span></p>
<section id="steps-for-prediction" class="level5" data-number="3.3.1.2.1"><h5 data-number="3.3.1.2.1" class="anchored" data-anchor-id="steps-for-prediction">
<span class="header-section-number">3.3.1.2.1</span> Steps for Prediction</h5>
<ol type="1">
<li><p>Fitting the model - use the random intercept model using the <code>lmer</code> function earlier.</p></li>
<li><p>Generating Predicted Values To generate predicted values for the outcome variable, use the <code>fitted</code> function. This function provides the fitted values (predictions) for each observation in the dataset based on the fixed and random effects:</p></li>
</ol>
<div class="cell">
<details class="code-fold"><summary>Show the code</summary><div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">pred_score</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">ri_model</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">pred_score</span>, <span class="fl">10</span><span class="op">)</span>  <span class="co"># Display the first 10 predicted scores</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>       1        2        3        4        5        6        7        8 
16.54111 16.54111 16.54111 16.54111 16.54111 16.54111 16.54111 16.54111 
       9       10 
16.54111 16.54111 </code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Extracting Random Effects The random effects (school-specific intercepts) can be extracted using the <code>ranef</code> function. This provides the deviations of each school’s intercept from the overall intercept:</li>
</ol>
<div class="cell">
<details class="code-fold"><summary>Show the code</summary><div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">rand_ef</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/nlme/man/random.effects.html">ranef</a></span><span class="op">(</span><span class="va">ri_model</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">rand_ef</span><span class="op">$</span><span class="va">schoolid</span>, <span class="fl">12</span><span class="op">)</span>  <span class="co"># Display the random intercepts for the first 12 schools</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>   (Intercept)
1    -6.728310
2     2.789899
3     2.034756
4    -7.631468
5     3.074107
6    11.833121
7    -1.604856
8    17.792799
9    -7.995792
10    2.778860
11   -8.618580
12   -2.198355</code></pre>
</div>
</div>
<ol start="4" type="1">
<li>Using <code><a href="https://generics.r-lib.org/reference/augment.html">broom.mixed::augment</a></code> The <code>broom.mixed</code> package’s <code>augment</code> function creates a data frame that includes the original data, fitted values, and residuals. This can be useful for further analysis and visualization:</li>
</ol>
<div class="cell">
<details class="code-fold"><summary>Show the code</summary><div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ri_fitted</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span><span class="op">(</span><span class="va">ri_model</span><span class="op">)</span></span>
<span><span class="va">ri_fitted</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/slice.html">slice</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">12</span><span class="op">)</span>  <span class="co"># Display the first 12 rows of the augmented data frame</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 14
   score cohort90 schoolid .fitted .resid   .hat  .cooksd .fixed   .mu .offset
   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
 1     0       -6        1    16.5 -16.5  0.0219 0.0143     23.3  16.5       0
 2    10       -6        1    16.5  -6.54 0.0219 0.00223    23.3  16.5       0
 3     0       -6        1    16.5 -16.5  0.0219 0.0143     23.3  16.5       0
 4    40       -6        1    16.5  23.5  0.0219 0.0287     23.3  16.5       0
 5    42       -6        1    16.5  25.5  0.0219 0.0338     23.3  16.5       0
 6     4       -6        1    16.5 -12.5  0.0219 0.00819    23.3  16.5       0
 7     0       -6        1    16.5 -16.5  0.0219 0.0143     23.3  16.5       0
 8     0       -6        1    16.5 -16.5  0.0219 0.0143     23.3  16.5       0
 9    14       -6        1    16.5  -2.54 0.0219 0.000336   23.3  16.5       0
10    27       -6        1    16.5  10.5  0.0219 0.00570    23.3  16.5       0
11    18       -2        1    21.4  -3.40 0.0219 0.000603   28.1  21.4       0
12    23       -4        1    19.0   4.03 0.0219 0.000845   25.7  19.0       0
# ℹ 4 more variables: .sqrtXwt &lt;dbl&gt;, .sqrtrwt &lt;dbl&gt;, .weights &lt;dbl&gt;,
#   .wtres &lt;dbl&gt;</code></pre>
</div>
</div>
</section><section id="explanation" class="level5" data-number="3.3.1.2.2"><h5 data-number="3.3.1.2.2" class="anchored" data-anchor-id="explanation">
<span class="header-section-number">3.3.1.2.2</span> Explanation</h5>
<ol type="1">
<li>
<strong>Fixed Effects</strong>:
<ul>
<li>The fixed effects (<span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>) provide the overall intercept and the effect of <code>cohort90</code> on <code>score</code>.</li>
<li>These effects are assumed to be the same across all schools.</li>
</ul>
</li>
<li>
<strong>Random Effects</strong>:
<ul>
<li>The random effects (<span class="math inline">\(u_{0j}\)</span>) represent the school-specific deviations from the overall intercept.</li>
<li>Each school has its own intercept, which is the sum of the overall intercept (<span class="math inline">\(\beta_0\)</span>) and the school’s random intercept (<span class="math inline">\(u_{0j}\)</span>).</li>
</ul>
</li>
<li>
<strong>Residuals</strong>:
<ul>
<li>The residuals (<span class="math inline">\(e_{ij}\)</span>) represent the individual-specific deviations from the school’s predicted score.</li>
<li>These capture the within-school variability that is not explained by the model.</li>
</ul>
</li>
<li>
<strong>Combined Prediction</strong>:
<ul>
<li>The predicted score for each student is the sum of the overall intercept, the effect of <code>cohort90</code>, the school-specific random intercept, and the individual-specific residual.</li>
<li>This combined approach ensures that the prediction accounts for both the fixed effects (common to all students) and the random effects (specific to each school).</li>
</ul>
</li>
</ol></section><section id="confirmation-with-manual-calculation" class="level5" data-number="3.3.1.2.3"><h5 data-number="3.3.1.2.3" class="anchored" data-anchor-id="confirmation-with-manual-calculation">
<span class="header-section-number">3.3.1.2.3</span> Confirmation with Manual Calculation</h5>
<p>Manually calculate the fitted values (predicted scores) to confirm the results from the model.</p>
<ol type="1">
<li><p><strong>Intercept (</strong><span class="math inline">\(\beta_0\)</span>): 30.55915. This is the overall average score when <code>cohort90</code> is zero.</p></li>
<li><p><strong>Level-2 Residual (school level residual,</strong> <span class="math inline">\(u_{0j}\)</span>): For <code>schoolid = 1</code>, this is -6.73. This represents the deviation of this school’s intercept from the overall intercept.</p></li>
<li><p><strong>Coefficient for <code>cohort90</code> (</strong><span class="math inline">\(\beta_1\)</span>): 1.214955. This indicates the average change in score for each unit change in <code>cohort90</code>.</p></li>
<li>
<p><strong>Example</strong>: For the first observation = <strong>cohort90</strong>: -6, <strong>schoolid</strong>: 1</p>
<ul>
<li><p>The fitted value (predicted score) can be calculated as: <span class="math display">\[
\text{score}_{ij} = \beta_0 + \beta_1 \text{cohort90}_{ij} + u_{0j} + e_{ij}
\]</span></p></li>
<li><p>Since <span class="math inline">\(e_{ij}\)</span> (the individual-level residual) is what we are trying to predict, we simplify to: <span class="math display">\[
\text{score}_{ij} = \beta_0 + \beta_1 \text{cohort90}_{ij} + u_{0j}
\]</span></p></li>
<li><p>Using the provided values: <span class="math display">\[
\text{score}_{ij} = 30.55915 - 6.728309492 + 1.214955 \times (-6)
\]</span> <span class="math display">\[
\text{score}_{ij} = 30.55915 - 6.728309492 - 7.28973
\]</span> <span class="math display">\[
\text{score}_{ij} = 16.54111
\]</span></p></li>
<li><p>This matches the calculated fitted value.</p></li>
</ul>
</li>
</ol></section></section><section id="plot" class="level4" data-number="3.3.1.3"><h4 data-number="3.3.1.3" class="anchored" data-anchor-id="plot">
<span class="header-section-number">3.3.1.3</span> Plot</h4>
<p>Plotting the model helps to visualize the fitted values from a random intercept model with an explanatory variable, such as <code>cohort90</code>. Visualization helps in understanding the model fit and the relationship between the variables.</p>
<div class="cell">
<details class="code-fold"><summary>Show the code</summary><div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">ri_fitted</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">cohort90</span>, <span class="va">.fitted</span>, group <span class="op">=</span> <span class="va">schoolid</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.3</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.3</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span><span class="op">(</span><span class="st">'Fitted score attainment'</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span><span class="op">(</span><span class="st">'Year: where 0 is the year 1990'</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="st">'The fitted value for random intercept model with covariate cohort90'</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div>
<figure class="figure"><p><img src="Linear-Mixed-Models_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Comment</strong>: This plot visualizes the fitted values from the random intercept model with cohort90 as the explanatory variable. It provides a visual confirmation of the model’s results, showing how the fitted scores vary across different cohort years and schools. The general upward trend indicates improving scores over time, while the variation between schools highlights the importance of accounting for school-specific effects in the model. This visualization helps in understanding the combined impact of fixed and random effects on the predicted scores.</p>
</section><section id="variance" class="level4" data-number="3.3.1.4"><h4 data-number="3.3.1.4" class="anchored" data-anchor-id="variance">
<span class="header-section-number">3.3.1.4</span> Variance</h4>
<section id="between-school-variance" class="level5" data-number="3.3.1.4.1"><h5 data-number="3.3.1.4.1" class="anchored" data-anchor-id="between-school-variance">
<span class="header-section-number">3.3.1.4.1</span> Between School Variance</h5>
<p>Between-school variance refers to the variation in the outcome variable (score) that is attributed to differences between schools. This variance component is crucial in multilevel modeling as it helps to understand how much of the total variance in scores can be explained by the differences between schools.</p>
<ol type="1">
<li>
<strong>Constant Only Model</strong>:
<ul>
<li>In the constant only (null) model, the variance due to differences between schools (random intercept) is 61.02.</li>
<li>This model does not include any explanatory variables and serves as a baseline to compare other models.</li>
</ul>
</li>
<li>
<strong>Model with Explanatory Variable (cohort90)</strong>:
<ul>
<li>When <code>cohort90</code> is added as an explanatory variable, the between-school variance reduces to 45.99.</li>
<li>This reduction indicates that some of the variance between schools is explained by the cohort year.</li>
</ul>
</li>
<li>
<strong>Proportion of Unexplained Variance</strong>:
<ul>
<li>After accounting for the cohort effects, the proportion of unexplained variance due to differences between schools is calculated as: <span class="math display">\[
\frac{45.99}{45.99 + 219.29} = 17\%
\]</span>
</li>
<li>This means that 17% of the total unexplained variance in scores is attributable to differences between schools after accounting for the cohort effect.</li>
</ul>
</li>
</ol></section><section id="within-school-variance" class="level5" data-number="3.3.1.4.2"><h5 data-number="3.3.1.4.2" class="anchored" data-anchor-id="within-school-variance">
<span class="header-section-number">3.3.1.4.2</span> Within School Variance</h5>
<p>Within-school variance refers to the variation in the outcome variable (score) within schools. This component captures the differences in scores among students within the same school. Understanding this variance is essential for identifying how much of the total variance is due to individual differences within schools.</p>
<ol type="1">
<li>
<strong>Constant Only Model</strong>:
<ul>
<li>In the constant only (null) model, the within-school variance (residual variance) is 258.36.</li>
<li>This model does not include any explanatory variables and serves as a baseline to compare other models.</li>
</ul>
</li>
<li>
<strong>Model with Explanatory Variable (cohort90)</strong>:
<ul>
<li>When <code>cohort90</code> is added as an explanatory variable, the within-school variance reduces to 219.29.</li>
<li>This reduction indicates that some of the variance within schools is explained by the cohort year.</li>
</ul>
</li>
<li>
<strong>Reduction in Variance</strong>:
<ul>
<li>The addition of <code>cohort90</code> reduces both the between-school and within-school variances.</li>
<li>The between-school variance reduces from 61.02 to 45.99.</li>
<li>The within-school variance reduces from 258.36 to 219.29.</li>
<li>The decrease in within-school variance is expected because <code>cohort90</code> is a student-level variable, meaning it explains part of the individual differences within schools.</li>
</ul>
</li>
</ol></section></section></section></section></section></main><!-- /main column -->
&nbsp;
<hr>
<p style="text-align: center;">A dedicated work by Dr Muhammad Saufi</p>

<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- Add font awesome icons --><p style="text-align: center;">
    <a href="https://www.facebook.com/drsaufimbbch/" class="fa fa-facebook"></a>
    <a href="https://github.com/drsaufi" class="fa fa-github"></a>
    <a href="mailto:drsaufimbbch@gmail.com" class="fa fa-envelope"></a>
</p>

&nbsp;
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>