<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Dr Muhammad Saufi">
<meta name="dcterms.date" content="2024-06-14">
<title>Logistic Regression with Correlated Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="Logistic Regression with Correlated Data_files/libs/clipboard/clipboard.min.js"></script>
<script src="Logistic Regression with Correlated Data_files/libs/quarto-html/quarto.js"></script>
<script src="Logistic Regression with Correlated Data_files/libs/quarto-html/popper.min.js"></script>
<script src="Logistic Regression with Correlated Data_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Logistic Regression with Correlated Data_files/libs/quarto-html/anchor.min.js"></script>
<link href="Logistic Regression with Correlated Data_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Logistic Regression with Correlated Data_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="Logistic Regression with Correlated Data_files/libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="Logistic Regression with Correlated Data_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Logistic Regression with Correlated Data_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Logistic Regression with Correlated Data_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="Logistic Regression with Correlated Data_files/libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><link rel="stylesheet" href="styles.css">
</head>
<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="1"><h2 id="toc-title">Contents</h2>
   
  <ul>
<li>
<a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a>
  <ul>
<li><a href="#marginal-models-population-average-models" id="toc-marginal-models-population-average-models" class="nav-link" data-scroll-target="#marginal-models-population-average-models"><span class="header-section-number">1.1</span> Marginal Models (Population Average Models)</a></li>
  <li><a href="#conditional-models-random-effects-models" id="toc-conditional-models-random-effects-models" class="nav-link" data-scroll-target="#conditional-models-random-effects-models"><span class="header-section-number">1.2</span> Conditional Models (Random Effects Models)</a></li>
  </ul>
</li>
  <li>
<a href="#multilevel-random-intercept-model" id="toc-multilevel-random-intercept-model" class="nav-link" data-scroll-target="#multilevel-random-intercept-model"><span class="header-section-number">2</span> Multilevel Random Intercept Model</a>
  <ul>
<li><a href="#setting-up-the-environment" id="toc-setting-up-the-environment" class="nav-link" data-scroll-target="#setting-up-the-environment"><span class="header-section-number">2.1</span> Setting Up the Environment</a></li>
  <li><a href="#dataset-overview" id="toc-dataset-overview" class="nav-link" data-scroll-target="#dataset-overview"><span class="header-section-number">2.2</span> Dataset Overview</a></li>
  <li><a href="#hierarchical-data-structure" id="toc-hierarchical-data-structure" class="nav-link" data-scroll-target="#hierarchical-data-structure"><span class="header-section-number">2.3</span> Hierarchical Data Structure</a></li>
  <li>
<a href="#estimation" id="toc-estimation" class="nav-link" data-scroll-target="#estimation"><span class="header-section-number">2.4</span> Estimation</a>
  <ul>
<li><a href="#sources-of-correlation" id="toc-sources-of-correlation" class="nav-link" data-scroll-target="#sources-of-correlation"><span class="header-section-number">2.4.1</span> Sources of Correlation</a></li>
  <li><a href="#model-variables" id="toc-model-variables" class="nav-link" data-scroll-target="#model-variables"><span class="header-section-number">2.4.2</span> Model Variables</a></li>
  <li><a href="#data-transformation" id="toc-data-transformation" class="nav-link" data-scroll-target="#data-transformation"><span class="header-section-number">2.4.3</span> Data Transformation</a></li>
  <li><a href="#population-average-model" id="toc-population-average-model" class="nav-link" data-scroll-target="#population-average-model"><span class="header-section-number">2.4.4</span> Population Average Model</a></li>
  </ul>
</li>
  </ul>
</li>
  </ul></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Logistic Regression with Correlated Data</h1>
<p class="subtitle lead">Advanced Categorical Data Analysis</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Dr Muhammad Saufi </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 14, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header><section id="introduction" class="level1" data-number="1"><h1 data-number="1">
<span class="header-section-number">1</span> Introduction</h1>
<p>Logistic regression for correlated data is designed to handle situations where binary outcomes (e.g., success/failure) are not independent, such as in clustered data (e.g., patients within hospitals) or repeated measures (e.g., multiple observations over time on the same subject). Standard logistic regression assumes independence among observations, which, when violated, leads to biased estimates and incorrect inferences. To address this, two primary models are used: marginal models and conditional models.</p>
<section id="marginal-models-population-average-models" class="level2" data-number="1.1"><h2 data-number="1.1" class="anchored" data-anchor-id="marginal-models-population-average-models">
<span class="header-section-number">1.1</span> Marginal Models (Population Average Models)</h2>
<p>Marginal models focus on estimating the average effect of covariates across the entire population. They use Generalized Estimating Equations (GEE) to account for the correlation within clusters. The GEE approach specifies a working correlation structure (e.g., independence, exchangeable, auto-regressive, unstructured) to adjust for within-cluster correlations and provides robust population-level estimates.</p>
</section><section id="conditional-models-random-effects-models" class="level2" data-number="1.2"><h2 data-number="1.2" class="anchored" data-anchor-id="conditional-models-random-effects-models">
<span class="header-section-number">1.2</span> Conditional Models (Random Effects Models)</h2>
<p>Conditional models include random effects to capture variability within clusters, offering subject-specific or cluster-specific inferences.</p>
<ul>
<li><p><strong>Random Intercept Models</strong>: Allow the intercept to vary across clusters, capturing baseline differences. Represent the average effect of covariates on the log-odds of the outcome.</p></li>
<li><p><strong>Random Slope Models</strong>: Allow both the intercept and the slope of the covariate to vary across clusters, capturing differences in the effect of covariates. Capture unobserved heterogeneity between clusters or subjects.</p></li>
</ul></section></section><section id="multilevel-random-intercept-model" class="level1" data-number="2"><h1 data-number="2">
<span class="header-section-number">2</span> Multilevel Random Intercept Model</h1>
<p>Random intercept model is used to account for hierarchical or nested data structures. This model includes both fixed effects, which apply to the entire population, and random effects, which account for the variability between clusters by allowing each cluster to have its own intercept, which captures the baseline level of the response variable for that cluster.</p>
<section id="setting-up-the-environment" class="level2" data-number="2.1"><h2 data-number="2.1" class="anchored" data-anchor-id="setting-up-the-environment">
<span class="header-section-number">2.1</span> Setting Up the Environment</h2>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Load the libraries</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/lbraglia/aplore3">aplore3</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/dcomtois/summarytools">summarytools</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/bbolker/broom.mixed">broom.mixed</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/lme4/lme4/">lme4</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">gee</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://strengejacke.github.io/sjPlot/">sjPlot</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://haozhu233.github.io/kableExtra/">kableExtra</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section><section id="dataset-overview" class="level2" data-number="2.2"><h2 data-number="2.2" class="anchored" data-anchor-id="dataset-overview">
<span class="header-section-number">2.2</span> Dataset Overview</h2>
<p>The dataset is from the book “Applied Logistic Regression” by Hosmer, Lemeshow, and Sturdivant (2013). The specific dataset referred to is called <code>GLOW_RAND</code>, which contains 500 observations. This dataset is used for demonstrating logistic regression techniques and can be loaded in R using the <code>aplore3</code> package. The dataset contains:</p>
<ul>
<li><p><strong>6 sites</strong>: The number of subjects per site varies from as few as 24 in one site (site 4) to as many as 113 in another site (site 2).</p></li>
<li><p><strong>124 physicians</strong>: The number of subjects treated by each physician varies from 1 to 13.</p></li>
<li><p><strong>Outcome of Interest</strong>: Whether a fracture occurred in the first year of follow-up (FRACTURE), coded as <code>NO</code> (0) or <code>YES</code> (1).</p></li>
</ul>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Data wrangling</span></span>
<span><span class="va">data_glow</span> <span class="op">&lt;-</span> <span class="va">glow_rand</span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">data_glow</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Rows: 500
Columns: 15
$ sub_id    &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 1…
$ site_id   &lt;int&gt; 2, 3, 3, 4, 5, 1, 3, 5, 5, 1, 1, 6, 2, 2, 3, 1, 1, 1, 2, 3, …
$ phy_id    &lt;int&gt; 80, 95, 184, 280, 289, 39, 114, 297, 294, 39, 28, 313, 71, 7…
$ priorfrac &lt;fct&gt; No, No, No, No, No, No, Yes, No, No, No, Yes, Yes, No, Yes, …
$ age       &lt;int&gt; 69, 66, 62, 69, 58, 86, 64, 75, 62, 80, 74, 85, 58, 66, 61, …
$ weight    &lt;dbl&gt; 72.6, 79.4, 78.5, 72.6, 48.5, 80.7, 68.0, 77.1, 49.9, 62.6, …
$ height    &lt;dbl&gt; 157.5, 162.6, 170.2, 154.9, 157.5, 154.9, 175.3, 160.0, 160.…
$ bmi       &lt;dbl&gt; 29.3, 30.0, 27.1, 30.2, 19.6, 33.6, 22.2, 30.1, 19.5, 26.1, …
$ premeno   &lt;fct&gt; No, No, No, Yes, No, No, No, Yes, No, No, No, No, No, Yes, N…
$ momfrac   &lt;fct&gt; No, No, No, No, No, Yes, No, No, No, No, No, No, No, No, No,…
$ armassist &lt;fct&gt; Yes, Yes, No, Yes, No, No, No, Yes, No, No, No, No, No, No, …
$ smoke     &lt;fct&gt; No, No, No, Yes, No, No, No, No, No, No, Yes, No, No, No, No…
$ raterisk  &lt;fct&gt; Greater, Greater, Same, Same, Greater, Same, Greater, Less, …
$ fracscore &lt;int&gt; 4, 4, 1, 4, 1, 7, 2, 6, 2, 5, 5, 7, 0, 3, 1, 7, 6, 3, 4, 7, …
$ fracture  &lt;fct&gt; No, No, No, No, No, No, No, No, No, No, No, No, No, No, No, …</code></pre>
</div>
</div>
</section><section id="hierarchical-data-structure" class="level2" data-number="2.3"><h2 data-number="2.3" class="anchored" data-anchor-id="hierarchical-data-structure">
<span class="header-section-number">2.3</span> Hierarchical Data Structure</h2>
<p>The data is structured in multiple levels to account for the correlation within clusters. Each level represents a different grouping or clustering of the data:</p>
<ul>
<li>
<p><strong>Level 1</strong>: Subject</p>
<ul>
<li>This is the individual level, where each <code>sub_id</code> represents a unique participant or subject in the study.</li>
<li>A participant in a clinical study with specific characteristics like age, gender, medical history, etc.</li>
</ul>
</li>
<li>
<p><strong>Level 2</strong>: Physician for Subject</p>
<ul>
<li>This level groups subjects under the same physician. Each <code>phy_id</code> represents a unique physician who is responsible for multiple subjects.</li>
<li>All subjects treated by the same doctor. This introduces correlation because subjects under the same physician might receive similar treatments or follow similar protocols.</li>
</ul>
</li>
<li>
<p><strong>Level 3</strong>: Site Where Physician Works</p>
<ul>
<li>This is the highest level, grouping physicians by the site or location where they work. Each <code>site_id</code> represents a unique site, such as a hospital or clinic.</li>
<li>All physicians working in the same hospital. This adds another layer of correlation because practices and resources can vary between sites, affecting the subjects treated there.</li>
</ul>
</li>
</ul>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Data structure</span></span>
<span><span class="va">data_glow</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">site_id</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>  site_id   n
1       1 111
2       2 113
3       3  76
4       4  24
5       5  99
6       6  77</code></pre>
</div>
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">data_glow</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">site_id</span>, <span class="va">phy_id</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>    site_id phy_id  n
1         1      1  5
2         1      3  3
3         1      7  3
4         1      8  1
5         1     16  1
6         1     21  3
7         1     22  2
8         1     23 10
9         1     24  6
10        1     25  2
11        1     26  3
12        1     27  6
13        1     28  2
14        1     29  3
15        1     30  4
16        1     31  7
17        1     33  2
18        1     34  7
19        1     35  4
20        1     36 11
21        1     37  7
22        1     38  4
23        1     39 12
24        1     42  3
25        2     45  4
26        2     49  1
27        2     50  6
28        2     51  1
29        2     53  5
30        2     54  5
31        2     59  4
32        2     61  5
33        2     62  2
34        2     63  8
35        2     64 12
36        2     66  3
37        2     68  5
38        2     70  4
39        2     71  7
40        2     72  6
41        2     73  2
42        2     74  2
43        2     76  4
44        2     77  5
45        2     78  1
46        2     79  7
47        2     80  5
48        2     82  1
49        2     85  4
50        2     87  4
51        3     95  2
52        3     97  1
53        3    109  3
54        3    111  5
55        3    114  3
56        3    115  1
57        3    116  2
58        3    121  3
59        3    126  1
60        3    128  2
61        3    130  2
62        3    137  1
63        3    141  2
64        3    143  2
65        3    145  2
66        3    146  4
67        3    159  1
68        3    162  3
69        3    163  4
70        3    166  6
71        3    172  1
72        3    175  1
73        3    179  2
74        3    180  2
75        3    181  3
76        3    184  3
77        3    185  4
78        3    186  3
79        3    187  4
80        3    190  2
81        3    193  1
82        4    194  4
83        4    197  1
84        4    229  1
85        4    280  6
86        4    282  6
87        4    283  1
88        4    284  5
89        5    285  7
90        5    286  9
91        5    287  5
92        5    288  6
93        5    289  5
94        5    290  2
95        5    291  7
96        5    292  2
97        5    293  2
98        5    294 13
99        5    295  5
100       5    296  9
101       5    297  2
102       5    298  4
103       5    299  1
104       5    300  4
105       5    301 11
106       5    302  3
107       5    304  2
108       6    305  4
109       6    306  1
110       6    309  5
111       6    311  3
112       6    312  4
113       6    313  9
114       6    315  3
115       6    316  4
116       6    317  7
117       6    318  5
118       6    319  7
119       6    320  2
120       6    321  4
121       6    322  4
122       6    323  2
123       6    324  5
124       6    325  8</code></pre>
</div>
</div>
</section><section id="estimation" class="level2" data-number="2.4"><h2 data-number="2.4" class="anchored" data-anchor-id="estimation">
<span class="header-section-number">2.4</span> Estimation</h2>
<p>In hierarchical or nested data structures, observations within the same group tend to be more similar to each other than to observations in different groups. This leads to correlation within groups, which needs to be accounted for in the analysis to avoid biased estimates and incorrect inferences.</p>
<section id="sources-of-correlation" class="level3" data-number="2.4.1"><h3 data-number="2.4.1" class="anchored" data-anchor-id="sources-of-correlation">
<span class="header-section-number">2.4.1</span> Sources of Correlation</h3>
<p>In this dataset, there are two possible sources of correlation:</p>
<ol type="1">
<li><p><strong>Physician (PHYS_ID)</strong>: Subjects (Level 1) are grouped under the same physician (Level 2). This means that subjects treated by the same physician may have more similar outcomes compared to subjects treated by different physicians.</p></li>
<li><p><strong>Site (SITE_ID)</strong>: Physicians (Level 2) are grouped under the same site (Level 3). This means that physicians working at the same site may follow similar protocols or share resources, leading to more similar outcomes for their subjects compared to physicians working at different sites.</p></li>
</ol>
<p>Because of these nested structures, we consider using random effects models to account for the correlation within these groups. However, in this analysis, the focus is on a two-level model using only the site level (SITE_ID).</p>
</section><section id="model-variables" class="level3" data-number="2.4.2"><h3 data-number="2.4.2" class="anchored" data-anchor-id="model-variables">
<span class="header-section-number">2.4.2</span> Model Variables</h3>
<p>The following covariates are used:</p>
<ul>
<li><p><strong>WEIGHT5</strong>: Continuous variable representing the weight (in kg) at enrollment, divided by 5. Dividing by 5 helps in interpreting the coefficient more easily, as it will represent the change in log-odds for a 5 kg increase in weight.</p></li>
<li><p><strong>ARMASSIST</strong>: Dichotomous variable indicating whether the subject needs assistance with their arms to stand.</p></li>
<li><p><strong>RATERISK</strong>: Three-level categorical variable indicating the self-reported risk of fracture (low, medium, high).</p></li>
</ul></section><section id="data-transformation" class="level3" data-number="2.4.3"><h3 data-number="2.4.3" class="anchored" data-anchor-id="data-transformation">
<span class="header-section-number">2.4.3</span> Data Transformation</h3>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Data transformation</span></span>
<span><span class="va">data_glow2</span> <span class="op">&lt;-</span> <span class="va">data_glow</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>weight5 <span class="op">=</span> <span class="va">weight</span><span class="op">/</span><span class="fl">5</span>, frac2 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/integer.html">as.integer</a></span><span class="op">(</span><span class="va">fracture</span><span class="op">)</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Summarize the transformed data</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/summarytools/man/dfSummary.html">dfSummary</a></span><span class="op">(</span><span class="va">data_glow2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Data Frame Summary  
data_glow2  
Dimensions: 500 x 17  
Duplicates: 0  

--------------------------------------------------------------------------------------------------------------
No   Variable    Stats / Values              Freqs (% of Valid)    Graph                  Valid      Missing  
---- ----------- --------------------------- --------------------- ---------------------- ---------- ---------
1    sub_id      Mean (sd) : 250.5 (144.5)   500 distinct values   : : : : : : : : : :    500        0        
     [integer]   min &lt; med &lt; max:            (Integer sequence)    : : : : : : : : : :    (100.0%)   (0.0%)   
                 1 &lt; 250.5 &lt; 500                                   : : : : : : : : : :                        
                 IQR (CV) : 249.5 (0.6)                            : : : : : : : : : :                        
                                                                   : : : : : : : : : :                        

2    site_id     Mean (sd) : 3.2 (1.8)       1 : 111 (22.2%)       IIII                   500        0        
     [integer]   min &lt; med &lt; max:            2 : 113 (22.6%)       IIII                   (100.0%)   (0.0%)   
                 1 &lt; 3 &lt; 6                   3 :  76 (15.2%)       III                                        
                 IQR (CV) : 3 (0.6)          4 :  24 ( 4.8%)                                                  
                                             5 :  99 (19.8%)       III                                        
                                             6 :  77 (15.4%)       III                                        

3    phy_id      Mean (sd) : 163.9 (117.8)   124 distinct values   : .                    500        0        
     [integer]   min &lt; med &lt; max:                                  : :       : :          (100.0%)   (0.0%)   
                 1 &lt; 139 &lt; 325                                     : :       : :                              
                 IQR (CV) : 241 (0.7)                              : : . :   : :                              
                                                                   : : : :   : :                              

4    priorfrac   1. No                       359 (71.8%)           IIIIIIIIIIIIII         500        0        
     [factor]    2. Yes                      141 (28.2%)           IIIII                  (100.0%)   (0.0%)   

5    age         Mean (sd) : 68.6 (8.7)      36 distinct values    : . :                  500        0        
     [integer]   min &lt; med &lt; max:                                  : : : .                (100.0%)   (0.0%)   
                 55 &lt; 67 &lt; 90                                      : : : : :                                  
                 IQR (CV) : 14 (0.1)                               : : : : : :                                
                                                                   : : : : : : :                              

6    weight      Mean (sd) : 71.8 (15.1)     120 distinct values       : :                500        0        
     [numeric]   min &lt; med &lt; max:                                      : : :              (100.0%)   (0.0%)   
                 38.1 &lt; 70.3 &lt; 129.3                                 . : : :                                  
                 IQR (CV) : 19 (0.2)                                 : : : : :                                
                                                                     : : : : : . . .                          

7    height      Mean (sd) : 161.9 (6.3)     17 distinct values          :   :            500        0        
     [numeric]   min &lt; med &lt; max:                                        :   :            (100.0%)   (0.0%)   
                 142.2 &lt; 162.6 &lt; 182.9                                 . : : :                                
                 IQR (CV) : 7.6 (0)                                    : : : : .                              
                                                                     . : : : : : .                            

8    bmi         Mean (sd) : 27.4 (5.4)      178 distinct values     . :                  500        0        
     [numeric]   min &lt; med &lt; max:                                    : :                  (100.0%)   (0.0%)   
                 15.4 &lt; 26.6 &lt; 48.1                                  : : .                                    
                 IQR (CV) : 7.2 (0.2)                                : : :                                    
                                                                   . : : : : .                                

9    premeno     1. No                       409 (81.8%)           IIIIIIIIIIIIIIII       500        0        
     [factor]    2. Yes                       91 (18.2%)           III                    (100.0%)   (0.0%)   

10   momfrac     1. No                       432 (86.4%)           IIIIIIIIIIIIIIIII      500        0        
     [factor]    2. Yes                       68 (13.6%)           II                     (100.0%)   (0.0%)   

11   armassist   1. No                       309 (61.8%)           IIIIIIIIIIII           500        0        
     [factor]    2. Yes                      191 (38.2%)           IIIIIII                (100.0%)   (0.0%)   

12   smoke       1. No                       469 (93.8%)           IIIIIIIIIIIIIIIIII     500        0        
     [factor]    2. Yes                       31 ( 6.2%)           I                      (100.0%)   (0.0%)   

13   raterisk    1. Less                     137 (27.4%)           IIIII                  500        0        
     [factor]    2. Same                     210 (42.0%)           IIIIIIII               (100.0%)   (0.0%)   
                 3. Greater                  153 (30.6%)           IIIIII                                     

14   fracscore   Mean (sd) : 3.6 (2.5)       11 distinct values    :                      500        0        
     [integer]   min &lt; med &lt; max:                                  : .   .                (100.0%)   (0.0%)   
                 0 &lt; 3 &lt; 10                                        : : : :                                    
                 IQR (CV) : 3 (0.7)                                : : : : : . . .                            
                                                                   : : : : : : : : .                          

15   fracture    1. No                       375 (75.0%)           IIIIIIIIIIIIIII        500        0        
     [factor]    2. Yes                      125 (25.0%)           IIIII                  (100.0%)   (0.0%)   

16   weight5     Mean (sd) : 14.4 (3)        120 distinct values       : :                500        0        
     [numeric]   min &lt; med &lt; max:                                      : : :              (100.0%)   (0.0%)   
                 7.6 &lt; 14.1 &lt; 25.9                                   . : : :                                  
                 IQR (CV) : 3.8 (0.2)                                : : : : :                                
                                                                     : : : : : . . .                          

17   frac2       Min  : 0                    0 : 375 (75.0%)       IIIIIIIIIIIIIII        500        0        
     [numeric]   Mean : 0.2                  1 : 125 (25.0%)       IIIII                  (100.0%)   (0.0%)   
                 Max  : 1                                                                                     
--------------------------------------------------------------------------------------------------------------</code></pre>
</div>
</div>
<ol type="1">
<li><p>A new variable <code>weight5</code> is created by dividing the original weight by 5. For example, if the original weight is 70 kg, <code>weight5</code> will be 70/5 = 14. This transformation is done so that the coefficient for <code>weight5</code> in the logistic regression model represents the change in log-odds for a 5 kg increase in weight, making interpretation easier.</p></li>
<li><p>The <code>FRACTURE</code> variable is originally coded as <code>NO</code> and <code>YES</code>. This step converts it into a numeric format where <code>NO</code> becomes 0 and <code>YES</code> becomes 1. The <code><a href="https://rdrr.io/r/base/integer.html">as.integer()</a></code> function converts <code>NO</code> to 1 and <code>YES</code> to 2, so subtracting 1 results in <code>NO</code> becoming 0 and <code>YES</code> becoming 1.</p></li>
</ol></section><section id="population-average-model" class="level3" data-number="2.4.4"><h3 data-number="2.4.4" class="anchored" data-anchor-id="population-average-model">
<span class="header-section-number">2.4.4</span> Population Average Model</h3>
<p>Population Average Model is used to estimate the average effect of predictors on the outcome across the entire population. This approach is implemented using Generalized Estimating Equations (GEE).</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Fit the GEE model</span></span>
<span><span class="va">glow_gee</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/gee/man/gee.html">gee</a></span><span class="op">(</span><span class="va">frac2</span> <span class="op">~</span> <span class="va">weight5</span> <span class="op">+</span> <span class="va">raterisk</span> <span class="op">+</span> <span class="va">armassist</span>, id <span class="op">=</span> <span class="va">site_id</span>, data <span class="op">=</span> <span class="va">data_glow2</span>, family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span> <span class="st">'logit'</span><span class="op">)</span>, corstr <span class="op">=</span> <span class="st">"independence"</span>, scale.fix <span class="op">=</span> <span class="cn">TRUE</span>, scale.value <span class="op">=</span> <span class="fl">1</span>, maxiter <span class="op">=</span> <span class="fl">100</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stderr">
<pre><code>Beginning Cgee S-function, @(#) geeformula.q 4.13 98/01/27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>running glm to get initial regression estimate</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>    (Intercept)         weight5    rateriskSame rateriskGreater    armassistYes 
     -0.3424651      -0.1211036       0.7208085       0.7713922       0.9012544 </code></pre>
</div>
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># View the GEE model</span></span>
<span><span class="va">glow_gee</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
 GEE:  GENERALIZED LINEAR MODELS FOR DEPENDENT DATA
 gee S-function, version 4.13 modified 98/01/27 (1998) 

Model:
 Link:                      Logit 
 Variance to Mean Relation: Binomial 
 Correlation Structure:     Independent 

Call:
gee(formula = frac2 ~ weight5 + raterisk + armassist, id = site_id, 
    data = data_glow2, maxiter = 100, family = binomial(link = "logit"), 
    corstr = "independence", scale.fix = TRUE, scale.value = 1)

Number of observations :  500 

Maximum cluster size   :  4 


Coefficients:
    (Intercept)         weight5    rateriskSame rateriskGreater    armassistYes 
     -0.3424651      -0.1211036       0.7208085       0.7713922       0.9012544 

Estimated Scale Parameter:  1
Number of Iterations:  1

Working Correlation[1:4,1:4]
     [,1] [,2] [,3] [,4]
[1,]    1    0    0    0
[2,]    0    0    0    0
[3,]    0    0    0    0
[4,]    0    0    0    0


Returned Error Value:
[1] 0</code></pre>
</div>
</div>
<p><strong>Summary of Output</strong>:</p>
<ol type="1">
<li>
<p><strong>Model Formula</strong>: <code>frac2 ~ weight5 + raterisk + armassist</code> specifies the dependent variable (<code>frac2</code>) and the independent variables (<code>weight5</code>, <code>raterisk</code>, and <code>armassist</code>).</p>
<ul>
<li>
<strong>ID</strong>: <code>site_id</code> indicates that clustering is by site.</li>
<li>
<strong>Data</strong>: <code>data_glow2</code> is the dataset used.</li>
<li>
<strong>Max Iterations</strong>: The maximum number of iterations for the algorithm is set to 100.</li>
<li>
<strong>Family</strong>: <code>binomial(link = "logit")</code> indicates a logistic regression model.</li>
<li>
<strong>Correlation Structure</strong>: <code>independence</code> specifies an independent correlation structure.</li>
<li>
<strong>Scale</strong>: The scale parameter is fixed at 1.</li>
</ul>
</li>
<li>
<p><strong>Interpretation</strong></p>
<ul>
<li>
<strong>Intercept</strong>: The baseline log-odds of having a fracture when all predictors are at their reference levels is -0.342.</li>
<li>
<strong>weight5</strong>: A 5 kg increase in weight is associated with a decrease in the log-odds of having a fracture by 0.121.</li>
<li>
<strong>rateriskSame</strong>: Compared to low risk, the same risk increases the log-odds of having a fracture by 0.721.</li>
<li>
<strong>rateriskGreater</strong>: Compared to low risk, greater risk increases the log-odds of having a fracture by 0.771.</li>
<li>
<strong>armassistYes</strong>: Needing arm assistance increases the log-odds of having a fracture by 0.901.</li>
</ul>
</li>
</ol>
<p>Proceed with the calculation of log odds and odds ratios from the model coefficients. <code><a href="https://rdrr.io/r/stats/coef.html">coef()</a></code> function extracts the estimated coefficients (log odds) from the GEE model <code>glow_gee</code>, and <code><a href="https://rdrr.io/r/base/Log.html">exp()</a></code> function exponentiates the coefficients to convert them from log odds to odds ratios.</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">res_glow_gee</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>log_odds <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">glow_gee</span><span class="op">)</span>, odds_ratio <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">glow_gee</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">res_glow_gee</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>                  log_odds odds_ratio
(Intercept)     -0.3424651  0.7100179
weight5         -0.1211036  0.8859421
rateriskSame     0.7208085  2.0560948
rateriskGreater  0.7713922  2.1627751
armassistYes     0.9012544  2.4626903</code></pre>
</div>
</div>
<p><strong>Summary of Output</strong>:</p>
<ol type="1">
<li>
<p><strong>Intercept</strong>:</p>
<ul>
<li>
<strong>Log Odds</strong>: -0.3424651, <strong>Odds Ratio</strong>: 0.7100179</li>
<li>The odds ratio of the baseline category (when all predictors are at their reference levels) is 0.71, indicating that the odds of having a fracture are 29% lower compared to the reference category.</li>
</ul>
</li>
<li>
<p><strong>weight5</strong>:</p>
<ul>
<li>
<strong>Log Odds</strong>: -0.1211036, <strong>Odds Ratio</strong>: 0.8859421</li>
<li>For each 5 kg increase in weight, the odds of having a fracture decrease by 11.4% (odds ratio of 0.886).</li>
</ul>
</li>
<li>
<p><strong>rateriskSame</strong>:</p>
<ul>
<li>
<strong>Log Odds</strong>: 0.7208085, <strong>Odds Ratio</strong>: 2.0560948</li>
<li>Compared to the reference category (low risk), the odds of having a fracture are approximately 2.06 times higher for those with the same risk.</li>
</ul>
</li>
<li>
<p><strong>rateriskGreater</strong>:</p>
<ul>
<li>
<strong>Log Odds</strong>: 0.7713922, <strong>Odds Ratio</strong>: 2.1627751</li>
<li>Compared to the reference category (low risk), the odds of having a fracture are approximately 2.16 times higher for those with a greater risk.</li>
</ul>
</li>
<li>
<p><strong>armassistYes</strong>:</p>
<ul>
<li>
<strong>Log Odds</strong>: 0.9012544, <strong>Odds Ratio</strong>: 2.4626903</li>
<li>The odds of having a fracture are approximately 2.46 times higher for those who need assistance with their arms to stand compared to those who do not.</li>
</ul>
</li>
</ol></section></section></section></main><!-- /main column -->
&nbsp;
<hr>
<p style="text-align: center;">A dedicated work by Dr Muhammad Saufi</p>

<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- Add font awesome icons --><p style="text-align: center;">
    <a href="https://www.facebook.com/drsaufimbbch/" class="fa fa-facebook"></a>
    <a href="https://github.com/drsaufi" class="fa fa-github"></a>
    <a href="mailto:drsaufimbbch@gmail.com" class="fa fa-envelope"></a>
</p>

&nbsp;
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>