<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Dr Muhammad Saufi">
<meta name="dcterms.date" content="2024-07-17">
<title>Multinomial Logistic Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="Multinomial-LR_files/libs/clipboard/clipboard.min.js"></script>
<script src="Multinomial-LR_files/libs/quarto-html/quarto.js"></script>
<script src="Multinomial-LR_files/libs/quarto-html/popper.min.js"></script>
<script src="Multinomial-LR_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Multinomial-LR_files/libs/quarto-html/anchor.min.js"></script>
<link href="Multinomial-LR_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Multinomial-LR_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="Multinomial-LR_files/libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="Multinomial-LR_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Multinomial-LR_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Multinomial-LR_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="Multinomial-LR_files/libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script src="Multinomial-LR_files/libs/kePrint-0.0.1/kePrint.js"></script><link href="Multinomial-LR_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="styles.css">
</head>
<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="1"><h2 id="toc-title">Contents</h2>
   
  <ul>
<li>
<a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a>
  <ul>
<li><a href="#model-structure" id="toc-model-structure" class="nav-link" data-scroll-target="#model-structure"><span class="header-section-number">1.1</span> Model Structure</a></li>
  <li><a href="#model-formulation" id="toc-model-formulation" class="nav-link" data-scroll-target="#model-formulation"><span class="header-section-number">1.2</span> Model Formulation</a></li>
  <li><a href="#estimation" id="toc-estimation" class="nav-link" data-scroll-target="#estimation"><span class="header-section-number">1.3</span> Estimation</a></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation"><span class="header-section-number">1.4</span> Interpretation</a></li>
  <li><a href="#model-fit-and-diagnostics" id="toc-model-fit-and-diagnostics" class="nav-link" data-scroll-target="#model-fit-and-diagnostics"><span class="header-section-number">1.5</span> Model Fit and Diagnostics</a></li>
  </ul>
</li>
  <li><a href="#setting-up-the-environment" id="toc-setting-up-the-environment" class="nav-link" data-scroll-target="#setting-up-the-environment"><span class="header-section-number">2</span> Setting Up the Environment</a></li>
  <li>
<a href="#practical-1-mammography-experience-dataset" id="toc-practical-1-mammography-experience-dataset" class="nav-link" data-scroll-target="#practical-1-mammography-experience-dataset"><span class="header-section-number">3</span> Practical 1: Mammography Experience Dataset</a>
  <ul>
<li><a href="#dataset-overview" id="toc-dataset-overview" class="nav-link" data-scroll-target="#dataset-overview"><span class="header-section-number">3.1</span> Dataset Overview</a></li>
  <li><a href="#data-reading-and-exploration" id="toc-data-reading-and-exploration" class="nav-link" data-scroll-target="#data-reading-and-exploration"><span class="header-section-number">3.2</span> Data Reading and Exploration</a></li>
  <li>
<a href="#data-wrangling" id="toc-data-wrangling" class="nav-link" data-scroll-target="#data-wrangling"><span class="header-section-number">3.3</span> Data Wrangling</a>
  <ul>
<li><a href="#me-variable" id="toc-me-variable" class="nav-link" data-scroll-target="#me-variable"><span class="header-section-number">3.3.1</span> <code>me</code> Variable</a></li>
  <li><a href="#hist-variable" id="toc-hist-variable" class="nav-link" data-scroll-target="#hist-variable"><span class="header-section-number">3.3.2</span> <code>hist</code> Variable</a></li>
  <li><a href="#table-summary" id="toc-table-summary" class="nav-link" data-scroll-target="#table-summary"><span class="header-section-number">3.3.3</span> Table Summary</a></li>
  </ul>
</li>
  <li>
<a href="#estimation-1" id="toc-estimation-1" class="nav-link" data-scroll-target="#estimation-1"><span class="header-section-number">3.4</span> Estimation</a>
  <ul>
<li><a href="#confirm-the-order-of-factor-levels" id="toc-confirm-the-order-of-factor-levels" class="nav-link" data-scroll-target="#confirm-the-order-of-factor-levels"><span class="header-section-number">3.4.1</span> Confirm the Order of Factor Levels</a></li>
  <li><a href="#reorder-the-factor-levels" id="toc-reorder-the-factor-levels" class="nav-link" data-scroll-target="#reorder-the-factor-levels"><span class="header-section-number">3.4.2</span> Reorder the Factor Levels</a></li>
  <li><a href="#check-the-order-of-levels" id="toc-check-the-order-of-levels" class="nav-link" data-scroll-target="#check-the-order-of-levels"><span class="header-section-number">3.4.3</span> Check the Order of Levels</a></li>
  <li>
<a href="#multinomial-logistic-regression-model" id="toc-multinomial-logistic-regression-model" class="nav-link" data-scroll-target="#multinomial-logistic-regression-model"><span class="header-section-number">3.4.4</span> Multinomial Logistic Regression Model</a>
  <ul class="collapse">
<li><a href="#model-with-hist2-as-predictor" id="toc-model-with-hist2-as-predictor" class="nav-link" data-scroll-target="#model-with-hist2-as-predictor"><span class="header-section-number">3.4.4.1</span> Model with <code>hist2</code> as Predictor</a></li>
  <li><a href="#model-with-detc-as-predictor" id="toc-model-with-detc-as-predictor" class="nav-link" data-scroll-target="#model-with-detc-as-predictor"><span class="header-section-number">3.4.4.2</span> Model with <code>detc</code> as Predictor</a></li>
  </ul>
</li>
  </ul>
</li>
  <li>
<a href="#inferences" id="toc-inferences" class="nav-link" data-scroll-target="#inferences"><span class="header-section-number">3.5</span> Inferences</a>
  <ul>
<li><a href="#calculate-95-confidence-intervals-and-combine-with-coefficients" id="toc-calculate-95-confidence-intervals-and-combine-with-coefficients" class="nav-link" data-scroll-target="#calculate-95-confidence-intervals-and-combine-with-coefficients"><span class="header-section-number">3.5.1</span> Calculate 95% Confidence Intervals and Combine with Coefficients</a></li>
  <li><a href="#exponentiate-coefficients-to-obtain-relative-risk-ratios-rrrs" id="toc-exponentiate-coefficients-to-obtain-relative-risk-ratios-rrrs" class="nav-link" data-scroll-target="#exponentiate-coefficients-to-obtain-relative-risk-ratios-rrrs"><span class="header-section-number">3.5.2</span> Exponentiate Coefficients to Obtain Relative Risk Ratios (RRRs)</a></li>
  </ul>
</li>
  </ul>
</li>
  <li>
<a href="#practical-2-additional-covariates" id="toc-practical-2-additional-covariates" class="nav-link" data-scroll-target="#practical-2-additional-covariates"><span class="header-section-number">4</span> Practical 2: Additional Covariates</a>
  <ul>
<li>
<a href="#estimation-2" id="toc-estimation-2" class="nav-link" data-scroll-target="#estimation-2"><span class="header-section-number">4.1</span> Estimation</a>
  <ul>
<li><a href="#defining-the-model" id="toc-defining-the-model" class="nav-link" data-scroll-target="#defining-the-model"><span class="header-section-number">4.1.1</span> Defining the Model</a></li>
  <li><a href="#checking-and-recoding-sympt-variable" id="toc-checking-and-recoding-sympt-variable" class="nav-link" data-scroll-target="#checking-and-recoding-sympt-variable"><span class="header-section-number">4.1.2</span> Checking and Recoding <code>sympt</code> Variable</a></li>
  <li><a href="#refit-the-model-with-new-symptd-variable" id="toc-refit-the-model-with-new-symptd-variable" class="nav-link" data-scroll-target="#refit-the-model-with-new-symptd-variable"><span class="header-section-number">4.1.3</span> Refit the Model with New <code>symptd</code> Variable</a></li>
  <li><a href="#convert-detc-to-a-binary-variable" id="toc-convert-detc-to-a-binary-variable" class="nav-link" data-scroll-target="#convert-detc-to-a-binary-variable"><span class="header-section-number">4.1.4</span> Convert <code>detc</code> to a Binary Variable</a></li>
  <li><a href="#refit-the-model-with-the-new-detcd-variable" id="toc-refit-the-model-with-the-new-detcd-variable" class="nav-link" data-scroll-target="#refit-the-model-with-the-new-detcd-variable"><span class="header-section-number">4.1.5</span> Refit the Model with the New <code>detcd</code> Variable</a></li>
  </ul>
</li>
  <li>
<a href="#inferences-1" id="toc-inferences-1" class="nav-link" data-scroll-target="#inferences-1"><span class="header-section-number">4.2</span> Inferences</a>
  <ul>
<li><a href="#retrieve-log-odds-and-rrrs" id="toc-retrieve-log-odds-and-rrrs" class="nav-link" data-scroll-target="#retrieve-log-odds-and-rrrs"><span class="header-section-number">4.2.1</span> Retrieve Log-Odds and RRRs</a></li>
  <li><a href="#calculate-95-confidence-intervals" id="toc-calculate-95-confidence-intervals" class="nav-link" data-scroll-target="#calculate-95-confidence-intervals"><span class="header-section-number">4.2.2</span> Calculate 95% Confidence Intervals</a></li>
  <li><a href="#combine-the-results-into-a-table" id="toc-combine-the-results-into-a-table" class="nav-link" data-scroll-target="#combine-the-results-into-a-table"><span class="header-section-number">4.2.3</span> Combine the Results into a Table</a></li>
  <li><a href="#display-the-results" id="toc-display-the-results" class="nav-link" data-scroll-target="#display-the-results"><span class="header-section-number">4.2.4</span> Display the Results</a></li>
  </ul>
</li>
  <li>
<a href="#prediction" id="toc-prediction" class="nav-link" data-scroll-target="#prediction"><span class="header-section-number">4.3</span> Prediction</a>
  <ul>
<li>
<a href="#predict-the-log-odds" id="toc-predict-the-log-odds" class="nav-link" data-scroll-target="#predict-the-log-odds"><span class="header-section-number">4.3.1</span> Predict the Log Odds</a>
  <ul class="collapse">
<li>
<a href="#manual-calculation-of-log-odds" id="toc-manual-calculation-of-log-odds" class="nav-link" data-scroll-target="#manual-calculation-of-log-odds"><span class="header-section-number">4.3.1.1</span> Manual Calculation of Log Odds</a>
  <ul class="collapse">
<li><a href="#st-observation-hist2-no" id="toc-st-observation-hist2-no" class="nav-link" data-scroll-target="#st-observation-hist2-no"><span class="header-section-number">4.3.1.1.1</span> 1st Observation (hist2 = no)</a></li>
  <li><a href="#rd-observation-hist2-yes" id="toc-rd-observation-hist2-yes" class="nav-link" data-scroll-target="#rd-observation-hist2-yes"><span class="header-section-number">4.3.1.1.2</span> 3rd Observation (hist2 = yes)</a></li>
  </ul>
</li>
  </ul>
</li>
  <li>
<a href="#predict-the-probability" id="toc-predict-the-probability" class="nav-link" data-scroll-target="#predict-the-probability"><span class="header-section-number">4.3.2</span> Predict the Probability</a>
  <ul class="collapse">
<li><a href="#probability-of-being-in-the-reference-group-never" id="toc-probability-of-being-in-the-reference-group-never" class="nav-link" data-scroll-target="#probability-of-being-in-the-reference-group-never"><span class="header-section-number">4.3.2.1</span> Probability of Being in the Reference Group (“Never”)</a></li>
  <li><a href="#probability-of-being-in-the-over-a-year-ago-group" id="toc-probability-of-being-in-the-over-a-year-ago-group" class="nav-link" data-scroll-target="#probability-of-being-in-the-over-a-year-ago-group"><span class="header-section-number">4.3.2.2</span> Probability of Being in the “Over a Year Ago” Group</a></li>
  <li><a href="#probability-of-being-in-the-within-a-year-group" id="toc-probability-of-being-in-the-within-a-year-group" class="nav-link" data-scroll-target="#probability-of-being-in-the-within-a-year-group"><span class="header-section-number">4.3.2.3</span> Probability of Being in the “Within a Year” Group</a></li>
  </ul>
</li>
  </ul>
</li>
  </ul>
</li>
  <li>
<a href="#practical-3-alternative-approach" id="toc-practical-3-alternative-approach" class="nav-link" data-scroll-target="#practical-3-alternative-approach"><span class="header-section-number">5</span> Practical 3: Alternative Approach</a>
  <ul>
<li>
<a href="#estimation-3" id="toc-estimation-3" class="nav-link" data-scroll-target="#estimation-3"><span class="header-section-number">5.1</span> Estimation</a>
  <ul>
<li><a href="#fitting-the-model" id="toc-fitting-the-model" class="nav-link" data-scroll-target="#fitting-the-model"><span class="header-section-number">5.1.1</span> Fitting the Model</a></li>
  <li><a href="#changing-the-reference-category" id="toc-changing-the-reference-category" class="nav-link" data-scroll-target="#changing-the-reference-category"><span class="header-section-number">5.1.2</span> Changing the Reference Category</a></li>
  </ul>
</li>
  <li>
<a href="#inferences-2" id="toc-inferences-2" class="nav-link" data-scroll-target="#inferences-2"><span class="header-section-number">5.2</span> Inferences</a>
  <ul>
<li><a href="#getting-p-values" id="toc-getting-p-values" class="nav-link" data-scroll-target="#getting-p-values"><span class="header-section-number">5.2.1</span> Getting P-Values</a></li>
  <li><a href="#confidence-intervals" id="toc-confidence-intervals" class="nav-link" data-scroll-target="#confidence-intervals"><span class="header-section-number">5.2.2</span> Confidence Intervals</a></li>
  </ul>
</li>
  </ul>
</li>
  <li><a href="#acknowledgment" id="toc-acknowledgment" class="nav-link" data-scroll-target="#acknowledgment"><span class="header-section-number">6</span> Acknowledgment</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">7</span> References</a></li>
  <li><a href="#r-codes" id="toc-r-codes" class="nav-link" data-scroll-target="#r-codes"><span class="header-section-number">8</span> R Codes</a></li>
  </ul></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Multinomial Logistic Regression</h1>
<p class="subtitle lead">Advanced Categorical Data Analysis</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Dr Muhammad Saufi </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 17, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header><div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
About This Document
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This document serves both learning and practical purposes. It is designed for educational use, aiming to enhance statistical analysis skills and provide clear, organized notes for future reference.</p>
</div>
</div>
</div>
<section id="introduction" class="level1" data-number="1"><h1 data-number="1">
<span class="header-section-number">1</span> Introduction</h1>
<p>Multinomial Logistic Regression is an extension of binary logistic regression that allows for the modeling of outcome variables with more than two categories. This type of regression is used when the outcome categories are nominal, meaning they do not have a natural order. The dependent variable has multiple categories (more than two), and one of the categories is chosen as the reference category. The model compares each of the other categories to this reference category.</p>
<section id="model-structure" class="level2" data-number="1.1"><h2 data-number="1.1" class="anchored" data-anchor-id="model-structure">
<span class="header-section-number">1.1</span> Model Structure</h2>
<ul>
<li>The model estimates the log odds of each category relative to the reference category.</li>
<li>For a categorical outcome with <span class="math inline">\(k\)</span> categories, the model fits <span class="math inline">\(k-1\)</span> equations.</li>
<li>Each equation models the log odds of a specific category relative to the reference category.</li>
</ul></section><section id="model-formulation" class="level2" data-number="1.2"><h2 data-number="1.2" class="anchored" data-anchor-id="model-formulation">
<span class="header-section-number">1.2</span> Model Formulation</h2>
<ol type="1">
<li><strong>Log Odds</strong></li>
</ol>
<ul>
<li>The log odds of being in category <span class="math inline">\(j\)</span> relative to the reference category <span class="math inline">\(0\)</span> is modeled as:</li>
</ul>
<p><span class="math display">\[
\log \left( \frac{P(Y=j|X)}{P(Y=0|X)} \right) = \alpha_j + \beta_{j1}X_1 + \beta_{j2}X_2 + \ldots + \beta_{jp}X_p
\]</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(\alpha_j\)</span> is the intercept for category <span class="math inline">\(j\)</span>, and <span class="math inline">\(\beta_{jk}\)</span> are the coefficients for the predictor variables <span class="math inline">\(X_k\)</span>.</p>
</div>
</div>
<ol start="2" type="1">
<li><strong>Probability</strong></li>
</ol>
<ul>
<li>The probability of being in category <span class="math inline">\(j\)</span> is derived from the log odds:</li>
</ul>
<p><span class="math display">\[
P(Y=j|X) = \frac{e^{\alpha_j + \beta_{j1}X_1 + \beta_{j2}X_2 + \ldots + \beta_{jp}X_p}}{1 + \sum_{l=1}^{k-1} e^{\alpha_l + \beta_{l1}X_1 + \beta_{l2}X_2 + \ldots + \beta_{lp}X_p}}
\]</span></p>
<ul>
<li>The probability of being in the reference category <span class="math inline">\(0\)</span> is:</li>
</ul>
<p><span class="math display">\[
P(Y=0|X) = \frac{1}{1 + \sum_{l=1}^{k-1} e^{\alpha_l + \beta_{l1}X_1 + \beta_{l2}X_2 + \ldots + \beta_{lp}X_p}}
\]</span></p>
</section><section id="estimation" class="level2" data-number="1.3"><h2 data-number="1.3" class="anchored" data-anchor-id="estimation">
<span class="header-section-number">1.3</span> Estimation</h2>
<ul>
<li>The parameters (<span class="math inline">\(\alpha_j\)</span> and <span class="math inline">\(\beta_{jk}\)</span>) are estimated using maximum likelihood estimation (MLE).</li>
<li>The likelihood function is constructed based on the observed data and the probabilities of each category.</li>
<li>Iterative algorithms, such as Newton-Raphson or Fisher scoring, are used to find the parameter estimates that maximize the likelihood function.</li>
</ul></section><section id="interpretation" class="level2" data-number="1.4"><h2 data-number="1.4" class="anchored" data-anchor-id="interpretation">
<span class="header-section-number">1.4</span> Interpretation</h2>
<ol type="1">
<li>
<p><strong>Coefficients (</strong><span class="math inline">\(\beta\)</span>)</p>
<ul>
<li>The coefficients represent the change in the log odds of being in a category relative to the reference category for a one-unit change in the predictor variable.</li>
<li>Positive coefficients indicate higher odds of being in the category compared to the reference, while negative coefficients indicate lower odds.</li>
</ul>
</li>
<li><p><strong>Odds Ratios (OR)</strong> is obtained by exponentiating the coefficients:</p></li>
</ol>
<p><span class="math display">\[
OR = e^{\beta}
\]</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>An OR greater than 1 indicates increased odds of being in the category compared to the reference, and an OR less than 1 indicates decreased odds.</p>
</div>
</div>
</section><section id="model-fit-and-diagnostics" class="level2" data-number="1.5"><h2 data-number="1.5" class="anchored" data-anchor-id="model-fit-and-diagnostics">
<span class="header-section-number">1.5</span> Model Fit and Diagnostics</h2>
<ul>
<li>
<strong>Likelihood Ratio Test</strong>: Used to compare nested models and assess the significance of adding or removing predictors.</li>
<li>
<strong>Wald Test</strong>: Used to test the significance of individual coefficients.</li>
</ul></section></section><section id="setting-up-the-environment" class="level1" data-number="2"><h1 data-number="2">
<span class="header-section-number">2</span> Setting Up the Environment</h1>
<p>Load the necessary libraries to ensure the R environment is equipped with the tools and functions required for efficient and effective analysis.</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://here.r-lib.org/">here</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://haven.tidyverse.org">haven</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/ddsjoberg/gtsummary">gtsummary</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://www.stat.auckland.ac.nz/~yee/VGAM/">VGAM</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://yihui.org/knitr/">knitr</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://haozhu233.github.io/kableExtra/">kableExtra</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://www.stats.ox.ac.uk/pub/MASS4/">nnet</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://svn.r-project.org/R-packages/trunk/foreign/">foreign</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://readxl.tidyverse.org">readxl</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="practical-1-mammography-experience-dataset" class="level1" data-number="3"><h1 data-number="3">
<span class="header-section-number">3</span> Practical 1: Mammography Experience Dataset</h1>
<p>In this exercise, the objectives are to understand and apply multinomial logistic regression using a dataset related to mammography experiences. The focus is on analyzing the mammography experiences dataset to understand factors influencing whether women have had a mammogram recently, a long time ago, or never.</p>
<section id="dataset-overview" class="level2" data-number="3.1"><h2 data-number="3.1" class="anchored" data-anchor-id="dataset-overview">
<span class="header-section-number">3.1</span> Dataset Overview</h2>
<p>The dataset used is focused on mammography experiences which consists of responses from a survey on mammography experiences and perceptions. The dataset includes the following variables:</p>
<ol type="1">
<li>
<p><strong>me (Mammography Experience)</strong>: This is the outcome variable and is categorical with three levels:</p>
<ul>
<li>
<code>0</code>: Never had a mammogram</li>
<li>
<code>1</code>: Had a mammogram within a year</li>
<li>
<code>2</code>: Had a mammogram over a year ago</li>
</ul>
</li>
<li>
<p><strong>sympt (Symptoms Perception)</strong>: This variable captures the perception that a mammogram is not needed unless symptoms are present.</p>
<ul>
<li>
<code>1</code>: Strongly Agree</li>
<li>
<code>2</code>: Agree</li>
<li>
<code>3</code>: Disagree</li>
<li>
<code>4</code>: Strongly Disagree</li>
</ul>
</li>
<li><p><strong>pb (Perceived Benefit of Mammography)</strong>: This variable measures the perceived benefit of mammography on a scale. The exact scale is not specified but typically ranges from lower to higher perceived benefits.</p></li>
<li>
<p><strong>hist (Family History of Breast Cancer)</strong>: This binary variable indicates whether the respondent has a family history (mother or sister) of breast cancer.</p>
<ul>
<li>
<code>0</code>: No</li>
<li>
<code>1</code>: Yes</li>
</ul>
</li>
<li>
<p><strong>bse (Breast Self-Examination Training)</strong>: This binary variable indicates whether the respondent has been taught how to perform breast self-examinations.</p>
<ul>
<li>
<code>0</code>: No</li>
<li>
<code>1</code>: Yes</li>
</ul>
</li>
<li>
<p><strong>detc (Detection Likelihood)</strong>: This variable measures the respondent’s perception of the likelihood that a mammogram could detect a new case of breast cancer. It is coded as:</p>
<ul>
<li>
<code>1</code>: Not likely</li>
<li>
<code>2</code>: Somewhat likely</li>
<li>
<code>3</code>: Very likely</li>
</ul>
</li>
</ol></section><section id="data-reading-and-exploration" class="level2" data-number="3.2"><h2 data-number="3.2" class="anchored" data-anchor-id="data-reading-and-exploration">
<span class="header-section-number">3.2</span> Data Reading and Exploration</h2>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Read the data</span></span>
<span><span class="va">dat.m1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://haven.tidyverse.org/reference/read_dta.html">read_dta</a></span><span class="op">(</span><span class="st">"Datasets/mammog9.dta"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Explore the data</span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">dat.m1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 412
Columns: 7
$ obs   &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 1…
$ me    &lt;dbl&gt; 0, 0, 0, 1, 2, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0…
$ sympt &lt;dbl&gt; 3, 2, 3, 3, 4, 3, 4, 4, 2, 4, 4, 3, 4, 1, 2, 4, 3, 4, 3, 3, 3, 4…
$ pb    &lt;dbl&gt; 7, 11, 8, 11, 7, 7, 6, 6, 6, 6, 8, 6, 6, 5, 8, 11, 6, 5, 10, 10,…
$ hist  &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0…
$ bse   &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1…
$ detc  &lt;dbl&gt; 2, 3, 3, 3, 3, 3, 2, 3, 3, 3, 2, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 2…</code></pre>
</div>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">dat.m1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      obs              me             sympt             pb        
 Min.   :  1.0   Min.   :0.0000   Min.   :1.000   Min.   : 5.000  
 1st Qu.:103.8   1st Qu.:0.0000   1st Qu.:2.000   1st Qu.: 6.000  
 Median :206.5   Median :0.0000   Median :3.000   Median : 7.000  
 Mean   :206.5   Mean   :0.6117   Mean   :2.966   Mean   : 7.561  
 3rd Qu.:309.2   3rd Qu.:1.0000   3rd Qu.:4.000   3rd Qu.: 9.000  
 Max.   :412.0   Max.   :2.0000   Max.   :4.000   Max.   :17.000  
      hist             bse              detc      
 Min.   :0.0000   Min.   :0.0000   Min.   :1.000  
 1st Qu.:0.0000   1st Qu.:1.0000   1st Qu.:2.000  
 Median :0.0000   Median :1.0000   Median :3.000  
 Mean   :0.1068   Mean   :0.8689   Mean   :2.658  
 3rd Qu.:0.0000   3rd Qu.:1.0000   3rd Qu.:3.000  
 Max.   :1.0000   Max.   :1.0000   Max.   :3.000  </code></pre>
</div>
</div>
</section><section id="data-wrangling" class="level2" data-number="3.3"><h2 data-number="3.3" class="anchored" data-anchor-id="data-wrangling">
<span class="header-section-number">3.3</span> Data Wrangling</h2>
<p>The <code>me</code> and <code>hist</code> variables are treated as numerical despite being categorical variables. To ensure that the data is handled correctly during statistical analyses, these variables must be converted to factors so that each level is treated as a distinct category, and the analysis methods can correctly interpret these categories.</p>
<section id="me-variable" class="level3" data-number="3.3.1"><h3 data-number="3.3.1" class="anchored" data-anchor-id="me-variable">
<span class="header-section-number">3.3.1</span> <code>me</code> Variable</h3>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Counting the Original `me` Variable</span></span>
<span><span class="va">dat.m1</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">me</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
     me     n
  &lt;dbl&gt; &lt;int&gt;
1     0   234
2     1   104
3     2    74</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Copy dataset and keep the original dataset</span></span>
<span><span class="va">dat.m2</span> <span class="op">&lt;-</span> <span class="va">dat.m1</span></span>
<span></span>
<span><span class="co"># Converting `me` to a factor</span></span>
<span><span class="va">dat.m2</span> <span class="op">&lt;-</span> <span class="va">dat.m2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>me2 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">me</span>, labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"never"</span>, <span class="st">"within.a.year"</span>, <span class="st">"over.a.year.ago"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">dat.m2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">me2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  me2                 n
  &lt;fct&gt;           &lt;int&gt;
1 never             234
2 within.a.year     104
3 over.a.year.ago    74</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>This code creates a new variable <code>me2</code> by converting the numeric <code>me</code> variable to a factor. The <code>labels</code> argument assigns meaningful labels to the factor levels.</p>
</div>
</div>
</section><section id="hist-variable" class="level3" data-number="3.3.2"><h3 data-number="3.3.2" class="anchored" data-anchor-id="hist-variable">
<span class="header-section-number">3.3.2</span> <code>hist</code> Variable</h3>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Counting the Original `hist` Variable</span></span>
<span><span class="va">dat.m2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">hist</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
   hist     n
  &lt;dbl&gt; &lt;int&gt;
1     0   368
2     1    44</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Converting `hist` to a Factor</span></span>
<span><span class="va">dat.m2</span> <span class="op">&lt;-</span> <span class="va">dat.m2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>hist2 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">hist</span>, labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"no"</span>, <span class="st">"yes"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">dat.m2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">hist2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  hist2     n
  &lt;fct&gt; &lt;int&gt;
1 no      368
2 yes      44</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>This code creates a new variable <code>hist2</code> by converting the numeric <code>hist</code> variable to a factor, with <code>no</code> and <code>yes</code> as labels.</p>
</div>
</div>
</section><section id="table-summary" class="level3" data-number="3.3.3"><h3 data-number="3.3.3" class="anchored" data-anchor-id="table-summary">
<span class="header-section-number">3.3.3</span> Table Summary</h3>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Generate summary statistics for the dataset, grouped by the `me2` variable</span></span>
<span><span class="va">dat.m2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">-</span><span class="va">me</span>, <span class="op">-</span><span class="va">hist</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://www.danieldsjoberg.com/gtsummary/reference/tbl_summary.html">tbl_summary</a></span><span class="op">(</span>by <span class="op">=</span> <span class="va">me2</span>, statistic <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fu"><a href="https://www.danieldsjoberg.com/gtsummary/reference/select_helpers.html">all_continuous</a></span><span class="op">(</span><span class="op">)</span> <span class="op">~</span> <span class="st">"{mean} ({sd})"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="jedxtanvwr" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#jedxtanvwr table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#jedxtanvwr thead, #jedxtanvwr tbody, #jedxtanvwr tfoot, #jedxtanvwr tr, #jedxtanvwr td, #jedxtanvwr th {
  border-style: none;
}

#jedxtanvwr p {
  margin: 0;
  padding: 0;
}

#jedxtanvwr .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#jedxtanvwr .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#jedxtanvwr .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#jedxtanvwr .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#jedxtanvwr .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#jedxtanvwr .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#jedxtanvwr .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#jedxtanvwr .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#jedxtanvwr .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#jedxtanvwr .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#jedxtanvwr .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#jedxtanvwr .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#jedxtanvwr .gt_spanner_row {
  border-bottom-style: hidden;
}

#jedxtanvwr .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#jedxtanvwr .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#jedxtanvwr .gt_from_md > :first-child {
  margin-top: 0;
}

#jedxtanvwr .gt_from_md > :last-child {
  margin-bottom: 0;
}

#jedxtanvwr .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#jedxtanvwr .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#jedxtanvwr .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#jedxtanvwr .gt_row_group_first td {
  border-top-width: 2px;
}

#jedxtanvwr .gt_row_group_first th {
  border-top-width: 2px;
}

#jedxtanvwr .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#jedxtanvwr .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#jedxtanvwr .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#jedxtanvwr .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#jedxtanvwr .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#jedxtanvwr .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#jedxtanvwr .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#jedxtanvwr .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#jedxtanvwr .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#jedxtanvwr .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#jedxtanvwr .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#jedxtanvwr .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#jedxtanvwr .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#jedxtanvwr .gt_left {
  text-align: left;
}

#jedxtanvwr .gt_center {
  text-align: center;
}

#jedxtanvwr .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#jedxtanvwr .gt_font_normal {
  font-weight: normal;
}

#jedxtanvwr .gt_font_bold {
  font-weight: bold;
}

#jedxtanvwr .gt_font_italic {
  font-style: italic;
}

#jedxtanvwr .gt_super {
  font-size: 65%;
}

#jedxtanvwr .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#jedxtanvwr .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#jedxtanvwr .gt_indent_1 {
  text-indent: 5px;
}

#jedxtanvwr .gt_indent_2 {
  text-indent: 10px;
}

#jedxtanvwr .gt_indent_3 {
  text-indent: 15px;
}

#jedxtanvwr .gt_indent_4 {
  text-indent: 20px;
}

#jedxtanvwr .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead><tr class="header gt_col_headings">
<th id="<strong>Characteristic</strong>" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><strong>Characteristic</strong></th>
<th id="<strong>never</strong>, N = 234<span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">
<strong>never</strong>, N = 234<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span>
</th>
<th id="<strong>within.a.year</strong>, N = 104<span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">
<strong>within.a.year</strong>, N = 104<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span>
</th>
<th id="<strong>over.a.year.ago</strong>, N = 74<span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">
<strong>over.a.year.ago</strong>, N = 74<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span>
</th>
</tr></thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="label">obs</td>
<td class="gt_row gt_center" headers="stat_1">203 (121)</td>
<td class="gt_row gt_center" headers="stat_2">212 (113)</td>
<td class="gt_row gt_center" headers="stat_3">211 (122)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">sympt</td>
<td class="gt_row gt_center" headers="stat_1"><br></td>
<td class="gt_row gt_center" headers="stat_2"><br></td>
<td class="gt_row gt_center" headers="stat_3"><br></td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;1</td>
<td class="gt_row gt_center" headers="stat_1">33 (14%)</td>
<td class="gt_row gt_center" headers="stat_2">2 (1.9%)</td>
<td class="gt_row gt_center" headers="stat_3">5 (6.8%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;2</td>
<td class="gt_row gt_center" headers="stat_1">62 (26%)</td>
<td class="gt_row gt_center" headers="stat_2">4 (3.8%)</td>
<td class="gt_row gt_center" headers="stat_3">7 (9.5%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;3</td>
<td class="gt_row gt_center" headers="stat_1">85 (36%)</td>
<td class="gt_row gt_center" headers="stat_2">43 (41%)</td>
<td class="gt_row gt_center" headers="stat_3">32 (43%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;4</td>
<td class="gt_row gt_center" headers="stat_1">54 (23%)</td>
<td class="gt_row gt_center" headers="stat_2">55 (53%)</td>
<td class="gt_row gt_center" headers="stat_3">30 (41%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">pb</td>
<td class="gt_row gt_center" headers="stat_1">8.06 (2.19)</td>
<td class="gt_row gt_center" headers="stat_2">6.70 (1.66)</td>
<td class="gt_row gt_center" headers="stat_3">7.19 (1.91)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">bse</td>
<td class="gt_row gt_center" headers="stat_1">190 (81%)</td>
<td class="gt_row gt_center" headers="stat_2">99 (95%)</td>
<td class="gt_row gt_center" headers="stat_3">69 (93%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">detc</td>
<td class="gt_row gt_center" headers="stat_1"><br></td>
<td class="gt_row gt_center" headers="stat_2"><br></td>
<td class="gt_row gt_center" headers="stat_3"><br></td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;1</td>
<td class="gt_row gt_center" headers="stat_1">13 (5.6%)</td>
<td class="gt_row gt_center" headers="stat_2">1 (1.0%)</td>
<td class="gt_row gt_center" headers="stat_3">4 (5.4%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;2</td>
<td class="gt_row gt_center" headers="stat_1">77 (33%)</td>
<td class="gt_row gt_center" headers="stat_2">12 (12%)</td>
<td class="gt_row gt_center" headers="stat_3">16 (22%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;3</td>
<td class="gt_row gt_center" headers="stat_1">144 (62%)</td>
<td class="gt_row gt_center" headers="stat_2">91 (88%)</td>
<td class="gt_row gt_center" headers="stat_3">54 (73%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">hist2</td>
<td class="gt_row gt_center" headers="stat_1">14 (6.0%)</td>
<td class="gt_row gt_center" headers="stat_2">19 (18%)</td>
<td class="gt_row gt_center" headers="stat_3">11 (15%)</td>
</tr>
</tbody>
<tfoot class="gt_footnotes"><tr class="even">
<td colspan="4" class="gt_footnote">
<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> Mean (SD); n (%)</td>
</tr></tfoot>
</table>
</div>
</div>
</div>
</section></section><section id="estimation-1" class="level2" data-number="3.4"><h2 data-number="3.4" class="anchored" data-anchor-id="estimation-1">
<span class="header-section-number">3.4</span> Estimation</h2>
<p>The VGAM package is used to run multinomial logistic regression, which is suitable for a dependent variable with more than two categories. The objctive is to use the VGAM package to fit a multinomial logistic regression model and ensure the reference category for the dependent variable <code>me2</code> is “never”.</p>
<section id="confirm-the-order-of-factor-levels" class="level3" data-number="3.4.1"><h3 data-number="3.4.1" class="anchored" data-anchor-id="confirm-the-order-of-factor-levels">
<span class="header-section-number">3.4.1</span> Confirm the Order of Factor Levels</h3>
<p>Check the current order of the factor levels for <code>me2</code>. It is crucial because the reference level in regression models affects the interpretation of coefficients.</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">dat.m2</span><span class="op">$</span><span class="va">me2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "never"           "within.a.year"   "over.a.year.ago"</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The levels are currently in the order where “never” is the first level. For the model, we need “never” to be the last level to serve as the reference category.</p>
</div>
</div>
</section><section id="reorder-the-factor-levels" class="level3" data-number="3.4.2"><h3 data-number="3.4.2" class="anchored" data-anchor-id="reorder-the-factor-levels">
<span class="header-section-number">3.4.2</span> Reorder the Factor Levels</h3>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Create new dataset `dat.m3`</span></span>
<span><span class="va">dat.m3</span> <span class="op">&lt;-</span> <span class="va">dat.m2</span></span>
<span></span>
<span><span class="co"># Generate `me3`</span></span>
<span><span class="va">dat.m3</span> <span class="op">&lt;-</span> <span class="va">dat.m3</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>me3 <span class="op">=</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_relevel.html">fct_relevel</a></span><span class="op">(</span><span class="va">me2</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"over.a.year.ago"</span>, <span class="st">"within.a.year"</span>, <span class="st">"never"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Creates a new variable <code>me3</code> by reordering the levels of <code>me2</code> using <code>fct_relevel</code> so that “never” becomes the reference level.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">dat.m3</span><span class="op">$</span><span class="va">me</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1   2 
234 104  74 </code></pre>
</div>
</div>
<hr>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">dat.m3</span><span class="op">$</span><span class="va">me2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          never   within.a.year over.a.year.ago 
            234             104              74 </code></pre>
</div>
</div>
<hr>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">dat.m3</span><span class="op">$</span><span class="va">me3</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>over.a.year.ago   within.a.year           never 
             74             104             234 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>These functions confirm that the observations and levels are correctly adjusted after releveling.</p>
</div>
</div>
</section><section id="check-the-order-of-levels" class="level3" data-number="3.4.3"><h3 data-number="3.4.3" class="anchored" data-anchor-id="check-the-order-of-levels">
<span class="header-section-number">3.4.3</span> Check the Order of Levels</h3>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">dat.m3</span><span class="op">$</span><span class="va">me2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "never"           "within.a.year"   "over.a.year.ago"</code></pre>
</div>
</div>
<hr>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">dat.m3</span><span class="op">$</span><span class="va">me3</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "over.a.year.ago" "within.a.year"   "never"          </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>This checks the new order of levels to ensure that <code>me3</code> has “never” as the last level (reference category).</p>
</div>
</div>
</section><section id="multinomial-logistic-regression-model" class="level3" data-number="3.4.4"><h3 data-number="3.4.4" class="anchored" data-anchor-id="multinomial-logistic-regression-model">
<span class="header-section-number">3.4.4</span> Multinomial Logistic Regression Model</h3>
<section id="model-with-hist2-as-predictor" class="level4" data-number="3.4.4.1"><h4 data-number="3.4.4.1" class="anchored" data-anchor-id="model-with-hist2-as-predictor">
<span class="header-section-number">3.4.4.1</span> Model with <code>hist2</code> as Predictor</h4>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fitmlog1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/VGAM/man/vglm.html">vglm</a></span><span class="op">(</span><span class="va">me3</span> <span class="op">~</span> <span class="va">hist2</span>,</span>
<span>  family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/VGAM/man/multinomial.html">multinomial</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>  data <span class="op">=</span> <span class="va">dat.m3</span></span>
<span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fitmlog1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
vglm(formula = me3 ~ hist2, family = multinomial(), data = dat.m3)

Coefficients: 
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept):1  -1.2505     0.1429  -8.751  &lt; 2e-16 ***
(Intercept):2  -0.9510     0.1277  -7.446  9.6e-14 ***
hist2yes:1      1.0093     0.4275   2.361 0.018225 *  
hist2yes:2      1.2564     0.3747   3.353 0.000798 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Names of linear predictors: log(mu[,1]/mu[,3]), log(mu[,2]/mu[,3])

Residual deviance: 792.3399 on 820 degrees of freedom

Log-likelihood: -396.17 on 820 degrees of freedom

Number of Fisher scoring iterations: 4 

No Hauck-Donner effect found in any of the estimates


Reference group is level  3  of the response</code></pre>
</div>
</div>
<hr>
<ul>
<li>
<code>vglm(me3 ~ hist2, family = multinomial(), data = dat.m1)</code>: Fits a model where <code>me3</code> (mammography experience) is the dependent variable, and <code>hist2</code> (family history of breast cancer) is the predictor.</li>
<li>
<code>family = multinomial()</code>: Specifies that the model is a multinomial logistic regression.</li>
<li>
<code>data = dat.m3</code>: Specifies the dataset to be used.</li>
</ul>
<hr>
<p><strong>Summary of Output</strong></p>
<ol type="1">
<li>
<p><strong>Intercepts</strong></p>
<ul>
<li>
<code>(Intercept):1</code>: The log-odds of being in the “over a year ago” category relative to “never” when <code>hist2</code> is the reference level (no family history).</li>
<li>
<code>(Intercept):2</code>: The log-odds of being in the “within a year” category relative to “never” when <code>hist2</code> is the reference level (no family history).</li>
</ul>
</li>
<li>
<p><strong>Predictor (<code>hist2yes</code>)</strong></p>
<ul>
<li>
<code>hist2yes:1</code>: The log-odds change of being in the “over a year ago” category relative to “never” for participants with a family history of breast cancer compared to those without.</li>
<li>
<code>hist2yes:2</code>: The log-odds change of being in the “within a year” category relative to “never” for participants with a family history of breast cancer compared to those without.</li>
</ul>
</li>
<li>
<p><strong>Statistical Significance</strong></p>
<ul>
<li>
<code>(Intercept):1</code> and <code>(Intercept):2</code> are highly significant (p &lt; 0.001), indicating that the intercepts are significantly different from zero.</li>
<li>
<code>hist2yes:1</code> is significant at the 0.05 level (<code>*</code>), indicating that the log-odds change for the “over a year ago” category relative to “never” is significant for those with a family history of breast cancer.</li>
<li>
<code>hist2yes:2</code> is highly significant (p &lt; 0.001), indicating that the log-odds change for the “within a year” category relative to “never” is significant for those with a family history of breast cancer.</li>
</ul>
</li>
<li>
<p><strong>Interpretation</strong></p>
<ul>
<li>The model indicates that having a family history of breast cancer (hist2 = “yes”) significantly affects the likelihood of having had a mammogram “within a year” or “over a year ago” compared to “never”.</li>
<li>Significant positive coefficients for <code>hist2yes</code> suggest that participants with a family history of breast cancer are more likely to have had a mammogram within a year or over a year ago compared to those without a family history.</li>
<li>The model fit statistics (residual deviance, log-likelihood) suggest that the model adequately fits the data.</li>
</ul>
</li>
</ol></section><section id="model-with-detc-as-predictor" class="level4" data-number="3.4.4.2"><h4 data-number="3.4.4.2" class="anchored" data-anchor-id="model-with-detc-as-predictor">
<span class="header-section-number">3.4.4.2</span> Model with <code>detc</code> as Predictor</h4>
<div class="cell">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Convert `detc` to a factor</span></span>
<span><span class="va">dat.m3</span> <span class="op">&lt;-</span> <span class="va">dat.m3</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>detc2 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">detc</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Check the distribution of `detc2` across the levels of `me3`</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">dat.m3</span><span class="op">$</span><span class="va">me3</span>, <span class="va">dat.m3</span><span class="op">$</span><span class="va">detc2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 
                    1   2   3
  over.a.year.ago   4  16  54
  within.a.year     1  12  91
  never            13  77 144</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The table shows the count of observations for each combination of <code>me2</code> and <code>detc2</code>.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Fitting the model with `detc2` as predictor</span></span>
<span><span class="va">fitmlog2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/VGAM/man/vglm.html">vglm</a></span><span class="op">(</span><span class="va">me3</span> <span class="op">~</span> <span class="va">detc2</span>,</span>
<span>  family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/VGAM/man/multinomial.html">multinomial</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>  data <span class="op">=</span> <span class="va">dat.m3</span></span>
<span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fitmlog2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
vglm(formula = me3 ~ detc2, family = multinomial(), data = dat.m3)

Coefficients: 
              Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept):1  -1.1787     0.5718  -2.061   0.0393 *
(Intercept):2  -2.5649     1.0377      NA       NA  
detc22:1       -0.3926     0.6344  -0.619   0.5360  
detc22:2        0.7061     1.0832   0.652   0.5145  
detc23:1        0.1978     0.5936   0.333   0.7389  
detc23:2        2.1060     1.0463   2.013   0.0441 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Names of linear predictors: log(mu[,1]/mu[,3]), log(mu[,2]/mu[,3])

Residual deviance: 778.4011 on 818 degrees of freedom

Log-likelihood: -389.2005 on 818 degrees of freedom

Number of Fisher scoring iterations: 5 

Warning: Hauck-Donner effect detected in the following estimate(s):
'(Intercept):2'


Reference group is level  3  of the response</code></pre>
</div>
</div>
<hr>
<p><strong>Summary of Output</strong></p>
<ol type="1">
<li>
<p><strong>Intercepts</strong></p>
<ul>
<li>
<code>(Intercept):1</code>: The log-odds of being in the “over a year ago” category relative to “never” when <code>detc2</code> is at its reference level (usually the first level).</li>
<li>
<code>(Intercept):2</code>: The log-odds of being in the “within a year” category relative to “never” when <code>detc2</code> is at its reference level.</li>
</ul>
</li>
<li>
<p><strong>Predictor (<code>detc2</code>)</strong></p>
<ul>
<li>
<code>detc22:1</code>: The log-odds change of being in the “over a year ago” category relative to “never” for participants with the second level of <code>detc2</code> compared to the reference level.</li>
<li>
<code>detc22:2</code>: The log-odds change of being in the “within a year” category relative to “never” for participants with the second level of <code>detc2</code> compared to the reference level.</li>
<li>
<code>detc23:1</code>: The log-odds change of being in the “over a year ago” category relative to “never” for participants with the third level of <code>detc2</code> compared to the reference level.</li>
<li>
<code>detc23:2</code>: The log-odds change of being in the “within a year” category relative to “never” for participants with the third level of <code>detc2</code> compared to the reference level.</li>
</ul>
</li>
<li>
<p>**Statistical Significance*</p>
<ul>
<li>
<code>(Intercept):1</code> is significant at the 0.05 level (<code>*</code>), indicating that the intercept for the “over a year ago” category relative to “never” is significantly different from zero.</li>
<li>
<code>detc23:2</code> is significant at the 0.05 level (<code>*</code>), indicating that the log-odds change for the “within a year” category relative to “never” is significant for those at the third level of <code>detc2</code>.</li>
</ul>
</li>
<li>
<p><strong>Interpretation</strong></p>
<ul>
<li>The model indicates that the perceived likelihood of detection (<code>detc2</code>) has an effect on the likelihood of having had a mammogram “within a year” compared to “never”.</li>
<li>Significant positive coefficient for <code>detc23:2</code> suggests that participants with the highest level of perceived likelihood of detection are more likely to have had a mammogram within a year compared to those with the lowest level of perceived likelihood.</li>
<li>The model fit statistics (residual deviance, log-likelihood) suggest that the model adequately fits the data.</li>
</ul>
</li>
</ol></section></section></section><section id="inferences" class="level2" data-number="3.5"><h2 data-number="3.5" class="anchored" data-anchor-id="inferences">
<span class="header-section-number">3.5</span> Inferences</h2>
<p>Inferences refer to the process of drawing conclusions about a population based on the analysis of sample data. In multinomial logistic regression model, inferences involve estimating the relationships between the predictor variables and the outcome variable and determining the statistical significance and confidence of these estimates. The process of inferences involves:</p>
<ol type="1">
<li>Calculate the 95% Confidence Intervals (CIs) for the model coefficients.</li>
<li>Calculate the p-values for hypothesis testing.</li>
<li>Exponentiate the coefficients to obtain the Relative Risk Ratios (RRRs).</li>
</ol>
<section id="calculate-95-confidence-intervals-and-combine-with-coefficients" class="level3" data-number="3.5.1"><h3 data-number="3.5.1" class="anchored" data-anchor-id="calculate-95-confidence-intervals-and-combine-with-coefficients">
<span class="header-section-number">3.5.1</span> Calculate 95% Confidence Intervals and Combine with Coefficients</h3>
<div class="cell">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Extract coefficients from the model</span></span>
<span><span class="va">b_fitmlog2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">fitmlog2</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Calculate confidence intervals</span></span>
<span><span class="va">ci_fitmlog2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">fitmlog2</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Combine coefficients and confidence intervals</span></span>
<span><span class="va">b_ci_fitmlog2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">b_fitmlog2</span>, <span class="va">ci_fitmlog2</span><span class="op">)</span></span>
<span><span class="va">b_ci_fitmlog2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              b_fitmlog2       2.5 %      97.5 %
(Intercept):1 -1.1786550 -2.29930795 -0.05800204
(Intercept):2 -2.5649494 -4.59888160 -0.53101711
detc22:1      -0.3925617 -1.63588117  0.85075776
detc22:2       0.7060506 -1.41689336  2.82899454
detc23:1       0.1978257 -0.96565093  1.36130242
detc23:2       2.1059956  0.05519791  4.15679321</code></pre>
</div>
</div>
<hr>
<ul>
<li>
<strong><code>coef(fitmlog2)</code></strong>: Extracts the estimated coefficients from the model <code>fitmlog2</code>.</li>
<li>
<strong><code>confint(fitmlog2)</code></strong>: Calculates the 95% confidence intervals for the model coefficients.</li>
<li>
<strong><code>cbind(b_fitmlog2, ci_fitmlog2)</code></strong>: Combines the coefficients and their confidence intervals into a single table.</li>
<li>
<strong><code>b_fitmlog2</code></strong>: The estimated coefficients.</li>
<li>
<strong><code>2.5 %</code> and <code>97.5 %</code></strong>: The lower and upper bounds of the 95% confidence intervals for each coefficient.</li>
</ul></section><section id="exponentiate-coefficients-to-obtain-relative-risk-ratios-rrrs" class="level3" data-number="3.5.2"><h3 data-number="3.5.2" class="anchored" data-anchor-id="exponentiate-coefficients-to-obtain-relative-risk-ratios-rrrs">
<span class="header-section-number">3.5.2</span> Exponentiate Coefficients to Obtain Relative Risk Ratios (RRRs)</h3>
<div class="cell">
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Exponentiate the combined coefficients and confidence intervals</span></span>
<span><span class="va">rrr_fitmlog2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="va">b_ci_fitmlog2</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Combine the RRRs with the original table</span></span>
<span><span class="va">tab_fitmlog2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">b_ci_fitmlog2</span>, <span class="va">rrr_fitmlog2</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Name the columns of the combined table</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">tab_fitmlog2</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"b"</span>, <span class="st">"lower b"</span>, <span class="st">"upper b"</span>, <span class="st">"rrr"</span>, <span class="st">"lower rrr"</span>, <span class="st">"upper rrr"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Display the combined table</span></span>
<span><span class="va">tab_fitmlog2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       b     lower b     upper b        rrr  lower rrr
(Intercept):1 -1.1786550 -2.29930795 -0.05800204 0.30769231 0.10032825
(Intercept):2 -2.5649494 -4.59888160 -0.53101711 0.07692308 0.01006308
detc22:1      -0.3925617 -1.63588117  0.85075776 0.67532468 0.19478066
detc22:2       0.7060506 -1.41689336  2.82899454 2.02597403 0.24246610
detc23:1       0.1978257 -0.96565093  1.36130242 1.21875000 0.38073529
detc23:2       2.1059956  0.05519791  4.15679321 8.21527778 1.05674974
               upper rrr
(Intercept):1  0.9436480
(Intercept):2  0.5880066
detc22:1       2.3414204
detc22:2      16.9284313
detc23:1       3.9012711
detc23:2      63.8663880</code></pre>
</div>
</div>
<hr>
<ul>
<li>
<strong><code>exp(b_ci_fitmlog2)</code></strong>: Exponentiates the coefficients and their confidence intervals to obtain the RRRs.</li>
<li>
<strong><code>cbind(b_ci_fitmlog2, rrr_fitmlog2)</code></strong>: Combines the original table with the RRRs.</li>
<li>
<strong><code>colnames(tab_fitmlog2) &lt;- c('b', 'lower b', 'upper b', 'rrr', 'lower rrr', 'upper rrr')</code></strong>: Renames the columns of the combined table for clarity.</li>
<li>
<strong><code>b</code></strong>: The estimated coefficients.</li>
<li>
<strong><code>lower b</code> and <code>upper b</code></strong>: The lower and upper bounds of the 95% confidence intervals for the coefficients.</li>
<li>
<strong><code>rrr</code></strong>: The Relative Risk Ratios (exponentiated coefficients).</li>
<li>
<strong><code>lower rrr</code> and <code>upper rrr</code></strong>: The lower and upper bounds of the 95% confidence intervals for the RRRs.</li>
</ul>
<p><strong>Interpretation</strong></p>
<hr>
<ul>
<li>
<p>(Intercept):1</p>
<ul>
<li>The log-odds of being in the “over a year ago” category relative to “never” are -1.1786550 when all predictors are at their reference levels.</li>
<li>The confidence interval for this log-odds is [-2.29930795, -0.0580204], indicating it is statistically significant since it does not include zero.</li>
<li>The relative risk ratio (RRR) is 0.3076921, meaning that the likelihood of being in the “over a year ago” category is about 0.31 times that of the “never” category.</li>
<li>The 95% confidence interval for the RRR is [0.10032825, 0.9434680], indicating the precision of the estimate.</li>
</ul>
</li>
<li>
<p>detc22:1</p>
<ul>
<li>The log-odds of being in the “over a year ago” category relative to “never” decrease by 0.3925617 for each one-unit increase in <code>detc22</code>.</li>
<li>The confidence interval for this coefficient is [-1.63588117, 0.85075776], which includes zero, indicating it is not statistically significant.</li>
<li>The RRR is 0.67532468, meaning the likelihood decreases to about 0.68 times for each one-unit increase in <code>detc22</code>.</li>
<li>The 95% confidence interval for the RRR is [0.19478066, 2.3414204].</li>
</ul>
</li>
<li>
<p>detc23:1</p>
<ul>
<li>The log-odds of being in the “over a year ago” category relative to “never” increase by 0.1978257 for each one-unit increase in <code>detc23</code>.</li>
<li>The confidence interval for this coefficient is [-0.96556939, 1.36130242], which includes zero, indicating it is not statistically significant.</li>
<li>The RRR is 1.21875000, meaning the likelihood increases to about 1.22 times for each one-unit increase in <code>detc23</code>.</li>
<li>The 95% confidence interval for the RRR is [0.38073529, 3.9012711].</li>
</ul>
</li>
</ul>
<hr>
<ul>
<li>
<p>(Intercept):2</p>
<ul>
<li>The log-odds of being in the “within a year” category relative to “never” are -2.5649494 when all predictors are at their reference levels.</li>
<li>The confidence interval for this log-odds is [-4.59888160, -0.5310171], indicating it is statistically significant.</li>
<li>The RRR is 0.07692308, meaning that the likelihood of being in the “within a year” category is about 0.08 times that of the “never” category.</li>
<li>The 95% confidence interval for the RRR is [0.01006308, 0.5888066].</li>
</ul>
</li>
<li>
<p>detc22:2</p>
<ul>
<li>The log-odds of being in the “within a year” category relative to “never” increase by 0.7060506 for each one-unit increase in <code>detc22</code>.</li>
<li>The confidence interval for this coefficient is [-1.41689336, 2.82899454], which includes zero, indicating it is not statistically significant.</li>
<li>The RRR is 2.02597403, meaning the likelihood increases to about 2.03 times for each one-unit increase in <code>detc22</code>.</li>
<li>The 95% confidence interval for the RRR is [0.24246610, 16.9284133].</li>
</ul>
</li>
<li>
<p>detc23:2</p>
<ul>
<li>The log-odds of being in the “within a year” category relative to “never” increase by 2.1059956 for each one-unit increase in <code>detc23</code>.</li>
<li>The confidence interval for this coefficient is [0.05519791, 4.15679321], indicating it is statistically significant since it does not include zero.</li>
<li>The RRR is 8.21527778, meaning the likelihood increases to about 8.22 times for each one-unit increase in <code>detc23</code>.</li>
<li>The 95% confidence interval for the RRR is [1.05674974, 63.8663880], indicating a high degree of variability in the estimate.</li>
</ul>
</li>
</ul></section></section></section><section id="practical-2-additional-covariates" class="level1" data-number="4"><h1 data-number="4">
<span class="header-section-number">4</span> Practical 2: Additional Covariates</h1>
<p>In this exercise, the objective is to extend the initial multinomial logistic regression model by adding more covariates to better understand the relationships between the predictors and the outcome variable. This helps in refining the model and potentially improving its explanatory power.</p>
<section id="estimation-2" class="level2" data-number="4.1"><h2 data-number="4.1" class="anchored" data-anchor-id="estimation-2">
<span class="header-section-number">4.1</span> Estimation</h2>
<p>Define the additional covariates to be included in the model. These include variables such as:</p>
<ul>
<li>
<code>sympt</code> (perception of symptoms)</li>
<li>
<code>pb</code> (perceived benefit)</li>
<li>
<code>hist</code> (family history)</li>
<li>
<code>bse</code> (breast self-exam training)</li>
<li>
<code>detc</code> (detection likelihood)</li>
</ul>
<section id="defining-the-model" class="level3" data-number="4.1.1"><h3 data-number="4.1.1" class="anchored" data-anchor-id="defining-the-model">
<span class="header-section-number">4.1.1</span> Defining the Model</h3>
<p>The model is specified as a multinomial logistic regression, with the dataset <code>dat.m3</code>. The additional covariates are included in the model.</p>
<div class="cell">
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Fitting the model with additional covariates</span></span>
<span><span class="va">fitmlog3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/VGAM/man/vglm.html">vglm</a></span><span class="op">(</span><span class="va">me3</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">sympt</span><span class="op">)</span> <span class="op">+</span> <span class="va">pb</span> <span class="op">+</span> <span class="va">hist2</span> <span class="op">+</span> <span class="va">bse</span> <span class="op">+</span> <span class="va">detc2</span>,</span>
<span>  family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/VGAM/man/multinomial.html">multinomial</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>  data <span class="op">=</span> <span class="va">dat.m3</span></span>
<span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fitmlog3</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
vglm(formula = me3 ~ factor(sympt) + pb + hist2 + bse + detc2, 
    family = multinomial(), data = dat.m3)

Coefficients: 
                 Estimate Std. Error z value Pr(&gt;|z|)   
(Intercept):1    -0.98609    1.11184  -0.887  0.37513   
(Intercept):2    -2.99875    1.53905      NA       NA   
factor(sympt)2:1 -0.29008    0.64406  -0.450  0.65243   
factor(sympt)2:2  0.11004    0.92273   0.119  0.90508   
factor(sympt)3:1  0.81731    0.53979   1.514  0.12999   
factor(sympt)3:2  1.92471    0.77757   2.475  0.01331 * 
factor(sympt)4:1  1.13224    0.54767   2.067  0.03870 * 
factor(sympt)4:2  2.45699    0.77530   3.169  0.00153 **
pb:1             -0.14821    0.07637  -1.941  0.05230 . 
pb:2             -0.21944    0.07551  -2.906  0.00366 **
hist2yes:1        1.06544    0.45940   2.319  0.02038 * 
hist2yes:2        1.36624    0.43752   3.123  0.00179 **
bse:1             1.05214    0.51499   2.043  0.04105 * 
bse:2             1.29167    0.52988   2.438  0.01478 * 
detc22:1         -0.92439    0.71375  -1.295  0.19528   
detc22:2          0.01702    1.16169   0.015  0.98831   
detc23:1         -0.69053    0.68712  -1.005  0.31491   
detc23:2          0.90414    1.12661   0.803  0.42225   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Names of linear predictors: log(mu[,1]/mu[,3]), log(mu[,2]/mu[,3])

Residual deviance: 693.9019 on 806 degrees of freedom

Log-likelihood: -346.951 on 806 degrees of freedom

Number of Fisher scoring iterations: 5 

Warning: Hauck-Donner effect detected in the following estimate(s):
'(Intercept):2'


Reference group is level  3  of the response</code></pre>
</div>
</div>
<hr>
<ul>
<li>
<code><a href="https://rdrr.io/pkg/VGAM/man/vglm.html">vglm()</a></code>: Fits a multinomial logistic regression model with <code>me3</code> as the dependent variable and the specified covariates as predictors.</li>
<li>
<code>factor(sympt)</code> converts <code>sympt</code> to a factor variable.</li>
</ul></section><section id="checking-and-recoding-sympt-variable" class="level3" data-number="4.1.2"><h3 data-number="4.1.2" class="anchored" data-anchor-id="checking-and-recoding-sympt-variable">
<span class="header-section-number">4.1.2</span> Checking and Recoding <code>sympt</code> Variable</h3>
<p>The variable <code>sympt</code> has 4 categories, hence it is needed to be recoded into a binary factor variable <code>symptd</code> for simplicity.</p>
<div class="cell">
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Original `sympt` variable</span></span>
<span><span class="va">dat.m3</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">sympt</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  sympt     n
  &lt;dbl&gt; &lt;int&gt;
1     1    40
2     2    73
3     3   160
4     4   139</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># recode `sympt` into a binary variable `symptd`</span></span>
<span><span class="va">dat.m3</span> <span class="op">&lt;-</span> <span class="va">dat.m3</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>symptd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">sympt</span> <span class="op">&lt;</span> <span class="fl">3</span>, <span class="st">"&lt;3"</span>, <span class="st">"3 or more"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">dat.m3</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">sympt</span>, <span class="va">symptd</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  sympt symptd        n
  &lt;dbl&gt; &lt;chr&gt;     &lt;int&gt;
1     1 &lt;3           40
2     2 &lt;3           73
3     3 3 or more   160
4     4 3 or more   139</code></pre>
</div>
</div>
<hr>
<ul>
<li>
<code>mutate(symptd = ifelse(sympt &lt; 3, '&lt;3', '3 or more'))</code>: Recode <code>sympt</code> into a binary variable <code>symptd</code>, where categories less than 3 are labeled <code>&lt;3</code> and categories 3 or more are labeled <code>3 or more</code>.</li>
</ul></section><section id="refit-the-model-with-new-symptd-variable" class="level3" data-number="4.1.3"><h3 data-number="4.1.3" class="anchored" data-anchor-id="refit-the-model-with-new-symptd-variable">
<span class="header-section-number">4.1.3</span> Refit the Model with New <code>symptd</code> Variable</h3>
<div class="cell">
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Refit the model using the new binary variable `symptd`</span></span>
<span><span class="va">fitmlog4</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/VGAM/man/vglm.html">vglm</a></span><span class="op">(</span><span class="va">me3</span> <span class="op">~</span> <span class="va">symptd</span> <span class="op">+</span> <span class="va">pb</span> <span class="op">+</span> <span class="va">hist2</span> <span class="op">+</span> <span class="va">bse</span> <span class="op">+</span> <span class="va">detc2</span>,</span>
<span>  family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/VGAM/man/multinomial.html">multinomial</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>  data <span class="op">=</span> <span class="va">dat.m3</span></span>
<span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fitmlog4</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
vglm(formula = me3 ~ symptd + pb + hist2 + bse + detc2, family = multinomial(), 
    data = dat.m3)

Coefficients: 
                  Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept):1     -0.99877    1.07197  -0.932 0.351485    
(Intercept):2     -2.70375    1.43422  -1.885 0.059406 .  
symptd3 or more:1  1.12136    0.35720   3.139 0.001693 ** 
symptd3 or more:2  2.09534    0.45739   4.581 4.62e-06 ***
pb:1              -0.16811    0.07417  -2.266 0.023426 *  
pb:2              -0.25101    0.07293  -3.442 0.000578 ***
hist2yes:1         1.01406    0.45381   2.235 0.025446 *  
hist2yes:2         1.29328    0.43353   2.983 0.002853 ** 
bse:1              1.02859    0.51398   2.001 0.045366 *  
bse:2              1.24397    0.52630   2.364 0.018097 *  
detc22:1          -0.90213    0.71463  -1.262 0.206813    
detc22:2           0.09028    1.16079   0.078 0.938011    
detc23:1          -0.66982    0.68759  -0.974 0.329979    
detc23:2           0.97281    1.12604   0.864 0.387627    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Names of linear predictors: log(mu[,1]/mu[,3]), log(mu[,2]/mu[,3])

Residual deviance: 697.4959 on 810 degrees of freedom

Log-likelihood: -348.748 on 810 degrees of freedom

Number of Fisher scoring iterations: 5 

No Hauck-Donner effect found in any of the estimates


Reference group is level  3  of the response</code></pre>
</div>
</div>
<hr>
<p><strong>Summary of Output</strong></p>
<ol type="1">
<li>
<p>Intercepts</p>
<ul>
<li>
<strong>(Intercept):1</strong>: The log-odds of being in the “over a year ago” category relative to “never” are -0.99877 when all predictors are at their reference levels. This is not statistically significant (p = 0.351485).</li>
<li>
<strong>(Intercept):2</strong>: The log-odds of being in the “within a year” category relative to “never” are -2.70375 when all predictors are at their reference levels. This is marginally significant (p = 0.059406).</li>
</ul>
</li>
<li>
<p>Predictors</p>
<ul>
<li><p><strong>symptd3 or more:1</strong>: The log-odds of being in the “over a year ago” category relative to “never” increase by 1.12136 for those with symptoms 3 or more compared to less than 3. This is statistically significant (p = 0.001693).</p></li>
<li><p><strong>symptd3 or more:2</strong>: The log-odds of being in the “within a year” category relative to “never” increase by 2.09534 for those with symptoms 3 or more compared to less than 3. This is highly significant (p &lt; 0.001).</p></li>
<li><p><strong>pb:1</strong>: The log-odds of being in the “over a year ago” category relative to “never” decrease by 0.16811 for each unit increase in perceived benefit. This is statistically significant (p = 0.023426).</p></li>
<li><p><strong>pb:2</strong>: The log-odds of being in the “within a year” category relative to “never” decrease by 0.25101 for each unit increase in perceived benefit. This is highly significant (p &lt; 0.001).</p></li>
<li><p><strong>hist2yes:1</strong>: The log-odds of being in the “over a year ago” category relative to “never” increase by 1.01406 for those with a family history of breast cancer compared to those without. This is statistically significant (p = 0.025446).</p></li>
<li><p><strong>hist2yes:2</strong>: The log-odds of being in the “within a year” category relative to “never” increase by 1.29383 for those with a family history of breast cancer compared to those without. This is highly significant (p = 0.002835).</p></li>
<li><p><strong>bse:1</strong>: The log-odds of being in the “over a year ago” category relative to “never” increase by 1.28509 for those with breast self-exam training compared to those without. This is statistically significant (p = 0.012473).</p></li>
<li><p><strong>bse:2</strong>: The log-odds of being in the “within a year” category relative to “never” increase by 1.24397 for those with breast self-exam training compared to those without. This is statistically significant (p = 0.018097).</p></li>
<li><p><strong>detc22:1</strong>: The log-odds of being in the “over a year ago” category relative to “never” decrease by 0.90213 for those in the second level of detection likelihood compared to the reference level. This is not statistically significant (p = 0.206813).</p></li>
<li><p><strong>detc22:2</strong>: The log-odds of being in the “within a year” category relative to “never” increase by 0.09028 for those in the second level of detection likelihood compared to the reference level. This is not statistically significant (p = 0.938011).</p></li>
<li><p><strong>detc23:1</strong>: The log-odds of being in the “over a year ago” category relative to “never” decrease by 0.66982 for those in the third level of detection likelihood compared to the reference level. This is not statistically significant (p = 0.329979).</p></li>
<li><p><strong>detc23:2</strong>: The log-odds of being in the “within a year” category relative to “never” increase by 0.97281 for those in the third level of detection likelihood compared to the reference level. This is not statistically significant (p = 0.387627).</p></li>
</ul>
</li>
<li>
<p>Interpretation</p>
<ul>
<li>The model includes additional covariates such as symptoms, perceived benefit, family history, breast self-exam training, and detection likelihood.</li>
<li>Significant predictors include <code>symptd</code>, <code>pb</code>, <code>hist2</code>, and <code>bse</code>, indicating their impact on the likelihood of having a mammogram within a year or over a year ago relative to never.</li>
<li>The model fit statistics suggest that the model adequately fits the data.</li>
<li>Confidence intervals and RRRs provide further insights into the effects of these predictors.</li>
</ul>
</li>
</ol></section><section id="convert-detc-to-a-binary-variable" class="level3" data-number="4.1.4"><h3 data-number="4.1.4" class="anchored" data-anchor-id="convert-detc-to-a-binary-variable">
<span class="header-section-number">4.1.4</span> Convert <code>detc</code> to a Binary Variable</h3>
<p>The variable <code>detc</code> initially has 3 categories. The aim is to recode it into a binary variable <code>detcd</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat.m3</span> <span class="op">&lt;-</span> <span class="va">dat.m3</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>detcd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">detc</span> <span class="op">&lt;</span> <span class="fl">3</span>, <span class="st">"&lt;3"</span>, <span class="st">"3 or more"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<ul>
<li>
<code>ifelse(detc &lt; 3, '&lt;3', '3 or more')</code>: This function checks the value of <code>detc</code> for each observation.</li>
<li>If <code>detc</code> is less than 3, it assigns the value ‘&lt;3’ to <code>detcd</code>.</li>
<li>If <code>detc</code> is 3 or more, it assigns the value ‘3 or more’ to <code>detcd</code>.</li>
<li>This effectively recodes <code>detc</code> from 3 categories into a binary variable with 2 categories: ‘&lt;3’ and ‘3 or more’.</li>
</ul></section><section id="refit-the-model-with-the-new-detcd-variable" class="level3" data-number="4.1.5"><h3 data-number="4.1.5" class="anchored" data-anchor-id="refit-the-model-with-the-new-detcd-variable">
<span class="header-section-number">4.1.5</span> Refit the Model with the New <code>detcd</code> Variable</h3>
<div class="cell">
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fitmlog5</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/VGAM/man/vglm.html">vglm</a></span><span class="op">(</span><span class="va">me3</span> <span class="op">~</span> <span class="va">symptd</span> <span class="op">+</span> <span class="va">pb</span> <span class="op">+</span> <span class="va">hist2</span> <span class="op">+</span> <span class="va">bse</span> <span class="op">+</span> <span class="va">detcd</span>,</span>
<span>  family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/VGAM/man/multinomial.html">multinomial</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>  data <span class="op">=</span> <span class="va">dat.m3</span></span>
<span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fitmlog5</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
vglm(formula = me3 ~ symptd + pb + hist2 + bse + detcd, family = multinomial(), 
    data = dat.m3)

Coefficients: 
                  Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept):1     -1.82388    0.85509  -2.133 0.032928 *  
(Intercept):2     -2.62376    0.92639  -2.832 0.004622 ** 
symptd3 or more:1  1.12742    0.35636   3.164 0.001558 ** 
symptd3 or more:2  2.09475    0.45742   4.579 4.66e-06 ***
pb:1              -0.15432    0.07262  -2.125 0.033587 *  
pb:2              -0.24947    0.07258  -3.437 0.000588 ***
hist2yes:1         1.06318    0.45284   2.348 0.018885 *  
hist2yes:2         1.30986    0.43360   3.021 0.002520 ** 
bse:1              0.95601    0.50734   1.884 0.059515 .  
bse:2              1.23701    0.52542   2.354 0.018557 *  
detcd3 or more:1   0.11416    0.31821   0.359 0.719786    
detcd3 or more:2   0.88518    0.35624   2.485 0.012962 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Names of linear predictors: log(mu[,1]/mu[,3]), log(mu[,2]/mu[,3])

Residual deviance: 699.1326 on 812 degrees of freedom

Log-likelihood: -349.5663 on 812 degrees of freedom

Number of Fisher scoring iterations: 5 

No Hauck-Donner effect found in any of the estimates


Reference group is level  3  of the response</code></pre>
</div>
</div>
<hr>
<p><strong>Summary of Output</strong></p>
<ol type="1">
<li>
<p>Intercepts</p>
<ul>
<li>
<strong>(Intercept):1</strong>: The log-odds of being in the “over a year ago” category relative to “never” are -1.82388 when all predictors are at their reference levels. This is statistically significant (p = 0.032928).</li>
<li>
<strong>(Intercept):2</strong>: The log-odds of being in the “within a year” category relative to “never” are -2.62376 when all predictors are at their reference levels. This is highly significant (p = 0.004622).</li>
</ul>
</li>
<li>
<p>Predictors</p>
<ul>
<li><p><strong>symptd3 or more:1</strong>: The log-odds of being in the “over a year ago” category relative to “never” increase by 1.12742 for those with symptoms 3 or more compared to less than 3. This is statistically significant (p = 0.001558).</p></li>
<li><p><strong>symptd3 or more:2</strong>: The log-odds of being in the “within a year” category relative to “never” increase by 2.09475 for those with symptoms 3 or more compared to less than 3. This is highly significant (p &lt; 0.001).</p></li>
<li><p><strong>pb:1</strong>: The log-odds of being in the “over a year ago” category relative to “never” decrease by 0.15432 for each unit increase in perceived benefit. This is statistically significant (p = 0.033587).</p></li>
<li><p><strong>pb:2</strong>: The log-odds of being in the “within a year” category relative to “never” decrease by 0.24947 for each unit increase in perceived benefit. This is highly significant (p &lt; 0.001).</p></li>
<li><p><strong>hist2yes:1</strong>: The log-odds of being in the “over a year ago” category relative to “never” increase by 1.06318 for those with a family history of breast cancer compared to those without. This is statistically significant (p = 0.018885).</p></li>
<li><p><strong>hist2yes:2</strong>: The log-odds of being in the “within a year” category relative to “never” increase by 1.38968 for those with a family history of breast cancer compared to those without. This is highly significant (p = 0.001520).</p></li>
<li><p><strong>bse:1</strong>: The log-odds of being in the “over a year ago” category relative to “never” increase by 0.95601 for those with breast self-exam training compared to those without. This is marginally significant (p = 0.059515).</p></li>
<li><p><strong>bse:2</strong>: The log-odds of being in the “within a year” category relative to “never” increase by 1.20137 for those with breast self-exam training compared to those without. This is statistically significant (p = 0.018557).</p></li>
<li><p><strong>detcd3 or more:1</strong>: The log-odds of being in the “over a year ago” category relative to “never” increase by 0.11416 for those with detection likelihood 3 or more compared to less than 3. This is not statistically significant (p = 0.719786).</p></li>
<li><p><strong>detcd3 or more:2</strong>: The log-odds of being in the “within a year” category relative to “never” increase by 0.88518 for those with detection likelihood 3 or more compared to less than 3. This is statistically significant (p = 0.012962).</p></li>
</ul>
</li>
<li>
<p>Interpretation</p>
<ul>
<li>The model includes covariates such as symptoms, perceived benefit, family history, breast self-exam training, and detection likelihood.</li>
<li>Significant predictors include <code>symptd</code>, <code>pb</code>, <code>hist2</code>, and <code>bse</code>, indicating their impact on the likelihood of having a mammogram within a year or over a year ago relative to never.</li>
<li>The model fit statistics suggest that the model adequately fits the data.</li>
<li>Confidence intervals and RRRs provide further insights into the effects of these predictors.</li>
</ul>
</li>
</ol></section></section><section id="inferences-1" class="level2" data-number="4.2"><h2 data-number="4.2" class="anchored" data-anchor-id="inferences-1">
<span class="header-section-number">4.2</span> Inferences</h2>
<ol type="1">
<li>Retrieve the log-odds and RRRs (Relative Risk Ratios).</li>
<li>Calculate the 95% Confidence Intervals (CIs) for both the log-odds and the RRRs.</li>
<li>Combine these results into a table.</li>
<li>Present the results in a table</li>
</ol>
<section id="retrieve-log-odds-and-rrrs" class="level3" data-number="4.2.1"><h3 data-number="4.2.1" class="anchored" data-anchor-id="retrieve-log-odds-and-rrrs">
<span class="header-section-number">4.2.1</span> Retrieve Log-Odds and RRRs</h3>
<p>The log-odds are the coefficients from the multinomial logistic regression model, and the RRRs are the exponentiated coefficients.</p>
<div class="cell">
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">b_rrr_fitmlog5</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">fitmlog5</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">fitmlog5</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>
<strong><code>coef(fitmlog5)</code></strong>: Extracts the coefficients (log-odds) from the model <code>fitmlog5</code>.</li>
<li>
<strong><code>exp(coef(fitmlog5))</code></strong>: Exponentiates the coefficients to obtain the RRRs.</li>
<li>
<strong><code>cbind(coef(fitmlog5), exp(coef(fitmlog5)))</code></strong>: Combines the log-odds and RRRs into one table.</li>
</ul></section><section id="calculate-95-confidence-intervals" class="level3" data-number="4.2.2"><h3 data-number="4.2.2" class="anchored" data-anchor-id="calculate-95-confidence-intervals">
<span class="header-section-number">4.2.2</span> Calculate 95% Confidence Intervals</h3>
<div class="cell">
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ci_b_rrr_fitmlog5</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">fitmlog5</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">fitmlog5</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>
<strong><code>confint(fitmlog5)</code></strong>: Computes the 95% CIs for the log-odds.</li>
<li>
<strong><code>exp(confint(fitmlog5))</code></strong>: Computes the 95% CIs for the RRRs by exponentiating the CIs for the log-odds.</li>
<li>
<strong><code>cbind(confint(fitmlog5), exp(confint(fitmlog5)))</code></strong>: Combines the CIs for log-odds and RRRs into one table.</li>
</ul></section><section id="combine-the-results-into-a-table" class="level3" data-number="4.2.3"><h3 data-number="4.2.3" class="anchored" data-anchor-id="combine-the-results-into-a-table">
<span class="header-section-number">4.2.3</span> Combine the Results into a Table</h3>
<div class="cell">
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">res_fitmlog5</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">b_rrr_fitmlog5</span>, <span class="va">ci_b_rrr_fitmlog5</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">res_fitmlog5</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"b"</span>, <span class="st">"rrr"</span>, <span class="st">"lower 95% b"</span>, <span class="st">"upper 95% b"</span>, <span class="st">"lower 95% rrr"</span>, <span class="st">"upper 95% rrr"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>
<strong><code>cbind(b_rrr_fitmlog5, ci_b_rrr_fitmlog5)</code></strong>: Combines the log-odds, RRRs, and their CIs.</li>
<li>
<strong><code>colnames(res_fitmlog5) &lt;- c('b', 'rrr', 'lower 95% b', 'upper 95% b', 'lower 95% rrr', 'upper 95% rrr')</code></strong>: Renames the columns of the combined table for clarity.</li>
</ul></section><section id="display-the-results" class="level3" data-number="4.2.4"><h3 data-number="4.2.4" class="anchored" data-anchor-id="display-the-results">
<span class="header-section-number">4.2.4</span> Display the Results</h3>
<div class="cell">
<div class="sourceCode" id="cb52"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="va">res_fitmlog5</span>, digits <span class="op">=</span> <span class="fl">3</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/kable_styling.html">kable_styling</a></span><span class="op">(</span>bootstrap_options <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"striped"</span>, <span class="st">"hover"</span>, <span class="st">"condensed"</span>, <span class="st">"responsive"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">b</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">rrr</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">lower 95% b</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">upper 95% b</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">lower 95% rrr</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">upper 95% rrr</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept):1</td>
<td style="text-align: right;">-1.824</td>
<td style="text-align: right;">0.161</td>
<td style="text-align: right;">-3.500</td>
<td style="text-align: right;">-0.148</td>
<td style="text-align: right;">0.030</td>
<td style="text-align: right;">0.862</td>
</tr>
<tr class="even">
<td style="text-align: left;">(Intercept):2</td>
<td style="text-align: right;">-2.624</td>
<td style="text-align: right;">0.073</td>
<td style="text-align: right;">-4.439</td>
<td style="text-align: right;">-0.808</td>
<td style="text-align: right;">0.012</td>
<td style="text-align: right;">0.446</td>
</tr>
<tr class="odd">
<td style="text-align: left;">symptd3 or more:1</td>
<td style="text-align: right;">1.127</td>
<td style="text-align: right;">3.088</td>
<td style="text-align: right;">0.429</td>
<td style="text-align: right;">1.826</td>
<td style="text-align: right;">1.536</td>
<td style="text-align: right;">6.208</td>
</tr>
<tr class="even">
<td style="text-align: left;">symptd3 or more:2</td>
<td style="text-align: right;">2.095</td>
<td style="text-align: right;">8.123</td>
<td style="text-align: right;">1.198</td>
<td style="text-align: right;">2.991</td>
<td style="text-align: right;">3.314</td>
<td style="text-align: right;">19.911</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pb:1</td>
<td style="text-align: right;">-0.154</td>
<td style="text-align: right;">0.857</td>
<td style="text-align: right;">-0.297</td>
<td style="text-align: right;">-0.012</td>
<td style="text-align: right;">0.743</td>
<td style="text-align: right;">0.988</td>
</tr>
<tr class="even">
<td style="text-align: left;">pb:2</td>
<td style="text-align: right;">-0.249</td>
<td style="text-align: right;">0.779</td>
<td style="text-align: right;">-0.392</td>
<td style="text-align: right;">-0.107</td>
<td style="text-align: right;">0.676</td>
<td style="text-align: right;">0.898</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hist2yes:1</td>
<td style="text-align: right;">1.063</td>
<td style="text-align: right;">2.896</td>
<td style="text-align: right;">0.176</td>
<td style="text-align: right;">1.951</td>
<td style="text-align: right;">1.192</td>
<td style="text-align: right;">7.034</td>
</tr>
<tr class="even">
<td style="text-align: left;">hist2yes:2</td>
<td style="text-align: right;">1.310</td>
<td style="text-align: right;">3.706</td>
<td style="text-align: right;">0.460</td>
<td style="text-align: right;">2.160</td>
<td style="text-align: right;">1.584</td>
<td style="text-align: right;">8.669</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bse:1</td>
<td style="text-align: right;">0.956</td>
<td style="text-align: right;">2.601</td>
<td style="text-align: right;">-0.038</td>
<td style="text-align: right;">1.950</td>
<td style="text-align: right;">0.962</td>
<td style="text-align: right;">7.031</td>
</tr>
<tr class="even">
<td style="text-align: left;">bse:2</td>
<td style="text-align: right;">1.237</td>
<td style="text-align: right;">3.445</td>
<td style="text-align: right;">0.207</td>
<td style="text-align: right;">2.267</td>
<td style="text-align: right;">1.230</td>
<td style="text-align: right;">9.649</td>
</tr>
<tr class="odd">
<td style="text-align: left;">detcd3 or more:1</td>
<td style="text-align: right;">0.114</td>
<td style="text-align: right;">1.121</td>
<td style="text-align: right;">-0.510</td>
<td style="text-align: right;">0.738</td>
<td style="text-align: right;">0.601</td>
<td style="text-align: right;">2.091</td>
</tr>
<tr class="even">
<td style="text-align: left;">detcd3 or more:2</td>
<td style="text-align: right;">0.885</td>
<td style="text-align: right;">2.423</td>
<td style="text-align: right;">0.187</td>
<td style="text-align: right;">1.583</td>
<td style="text-align: right;">1.206</td>
<td style="text-align: right;">4.871</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<hr>
<ul>
<li>
<strong><code><a href="https://yihui.org/knitr/">library(knitr)</a></code></strong> and <strong><code><a href="http://haozhu233.github.io/kableExtra/">library(kableExtra)</a></code></strong>: Load the necessary libraries for table formatting.</li>
<li>
<strong><code>kable(res_fitmlog5, digits = 3)</code></strong>: Creates a table with <code>res_fitmlog5</code> data, formatting the values to three decimal places.</li>
<li>
<strong><code>kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))</code></strong>: Applies styling options to the table for better presentation.</li>
</ul>
<p><strong>Interpretation</strong></p>
<hr>
<ul>
<li>
<p><strong>(Intercept):1</strong></p>
<ul>
<li>The log-odds of being in the “over a year ago” category relative to “never” are -1.824 when all predictors are at their reference levels.</li>
<li>The RRR indicates that the odds of being in the “over a year ago” category are 0.161 times those of “never”.</li>
<li>The CIs suggest this estimate is statistically significant.</li>
</ul>
</li>
<li>
<p><strong>symptd3 or more:1</strong></p>
<ul>
<li>The log-odds of being in the “over a year ago” category relative to “never” increase by 1.127 for those with symptoms 3 or more compared to less than 3.</li>
<li>The RRR indicates that the odds are 3.088 times higher.</li>
<li>The CIs suggest this estimate is statistically significant.</li>
</ul>
</li>
<li>
<p><strong>pb:1</strong></p>
<ul>
<li>The log-odds of being in the “over a year ago” category relative to “never” decrease by 0.154 for each unit increase in perceived benefit.</li>
<li>The RRR indicates that the odds are 0.857 times lower.</li>
<li>The CIs suggest this estimate is statistically significant.</li>
</ul>
</li>
<li>
<p><strong>hist2yes:1</strong></p>
<ul>
<li>The log-odds of being in the “over a year ago” category relative to “never” increase by 1.063 for those with a family history of breast cancer compared to those without.</li>
<li>The RRR indicates that the odds are 2.896 times higher.</li>
<li>The CIs suggest this estimate is statistically significant.</li>
</ul>
</li>
<li>
<p><strong>bse:1</strong></p>
<ul>
<li>The log-odds of being in the “over a year ago” category relative to “never” increase by 0.956 for those with breast self-exam training compared to those without.</li>
<li>The RRR indicates that the odds are 2.601 times higher.</li>
<li>The CIs suggest this estimate is marginally significant.</li>
</ul>
</li>
<li>
<p><strong>detcd3 or more:1</strong></p>
<ul>
<li>The log-odds of being in the “over a year ago” category relative to “never” increase by 0.114 for those with detection likelihood 3 or more compared to less than 3.</li>
<li>The RRR indicates that the odds are 1.121 times higher.</li>
<li>The CIs suggest this estimate is not statistically significant.</li>
</ul>
</li>
</ul>
<hr>
<ul>
<li>
<p><strong>(Intercept):2</strong></p>
<ul>
<li>The log-odds of being in the “within a year” category relative to “never” are -2.624 when all predictors are at their reference levels.</li>
<li>The RRR indicates that the odds of being in the “within a year” category are 0.073 times those of “never”.</li>
<li>The CIs suggest this estimate is statistically significant.</li>
</ul>
</li>
<li>
<p><strong>symptd3 or more:2</strong></p>
<ul>
<li>The log-odds of being in the “within a year” category relative to “never” increase by 2.095 for those with symptoms 3 or more compared to less than 3.</li>
<li>The RRR indicates that the odds are 8.123 times higher.</li>
<li>The CIs suggest this estimate is highly significant.</li>
</ul>
</li>
<li>
<p><strong>pb:2</strong></p>
<ul>
<li>The log-odds of being in the “within a year” category relative to “never” decrease by 0.249 for each unit increase in perceived benefit.</li>
<li>The RRR indicates that the odds are 0.779 times lower.</li>
<li>The CIs suggest this estimate is highly significant.</li>
</ul>
</li>
<li>
<p><strong>hist2yes:2</strong></p>
<ul>
<li>The log-odds of being in the “within a year” category relative to “never” increase by 1.310 for those with a family history of breast cancer compared to those without.</li>
<li>The RRR indicates that the odds are 3.706 times higher.</li>
<li>The CIs suggest this estimate is statistically significant.</li>
</ul>
</li>
<li>
<p><strong>bse:2</strong></p>
<ul>
<li>The log-odds of being in the “within a year” category relative to “never” increase by 1.237 for those with breast self-exam training compared to those without.</li>
<li>The RRR indicates that the odds are 3.445 times higher.</li>
<li>The CIs suggest this estimate is statistically significant.</li>
</ul>
</li>
<li>
<p><strong>detcd3 or more:2</strong></p>
<ul>
<li>The log-odds of being in the “within a year” category relative to “never” increase by 0.885 for those with detection likelihood 3 or more compared to less than 3.</li>
<li>The RRR indicates that the odds are 2.423 times higher.</li>
<li>The CIs suggest this estimate is statistically significant.</li>
</ul>
</li>
</ul></section></section><section id="prediction" class="level2" data-number="4.3"><h2 data-number="4.3" class="anchored" data-anchor-id="prediction">
<span class="header-section-number">4.3</span> Prediction</h2>
<section id="predict-the-log-odds" class="level3" data-number="4.3.1"><h3 data-number="4.3.1" class="anchored" data-anchor-id="predict-the-log-odds">
<span class="header-section-number">4.3.1</span> Predict the Log Odds</h3>
<p>Predict the log odds for the given multinomial logistic regression model (<code>fitmlog1</code>).</p>
<div class="cell">
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Predicts the log odds and display the first 6 observations</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/VGAM/man/notdocumentedyet.html">predict.vgam</a></span><span class="op">(</span><span class="va">fitmlog1</span>, type <span class="op">=</span> <span class="st">'link'</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  log(mu[,1]/mu[,3]) log(mu[,2]/mu[,3])
1         -1.2504928         -0.9509763
2         -1.2504928         -0.9509763
3         -0.2411621          0.3053816
4         -1.2504928         -0.9509763
5         -1.2504928         -0.9509763
6         -1.2504928         -0.9509763</code></pre>
</div>
</div>
<hr>
<ul>
<li>
<strong><code>predict.vgam(fitmlog1, type = 'link')</code></strong>: Predicts the log odds (logit values) for each observation using the model <code>fitmlog1</code>. The <code>type = 'link'</code> option specifies that the predictions should be on the logit (log-odds) scale.</li>
<li>
<strong><code><a href="https://rdrr.io/r/utils/head.html">head()</a></code></strong>: Displays the first 6 observations.</li>
<li>
<strong>log(mu[,1]/mu[,3])</strong>: The predicted log odds of being in the “over a year ago” category vs.&nbsp;“never”.</li>
<li>
<strong>log(mu[,2]/mu[,3])</strong>: The predicted log odds of being in the “within a year” category vs.&nbsp;“never”.</li>
</ul>
<section id="manual-calculation-of-log-odds" class="level4" data-number="4.3.1.1"><h4 data-number="4.3.1.1" class="anchored" data-anchor-id="manual-calculation-of-log-odds">
<span class="header-section-number">4.3.1.1</span> Manual Calculation of Log Odds</h4>
<p>Manually verify these predictions using the coefficients from the model and the values of the predictors for that observation.</p>
<ul>
<li>
<strong>(Intercept):1</strong>: -1.2504928</li>
<li>
<strong>(Intercept):2</strong>: -0.9509763</li>
<li>
<strong>hist2yes:1</strong>: 1.0093308</li>
<li>
<strong>hist2yes:2</strong>: 1.2565379</li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb55"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">dat.m1</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">3</span>,<span class="op">]</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 7
    obs    me sympt    pb  hist   bse  detc
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     1     0     3     7     0     1     2
2     2     0     2    11     0     1     3
3     3     0     3     8     1     1     3</code></pre>
</div>
</div>
<section id="st-observation-hist2-no" class="level5" data-number="4.3.1.1.1"><h5 data-number="4.3.1.1.1" class="anchored" data-anchor-id="st-observation-hist2-no">
<span class="header-section-number">4.3.1.1.1</span> 1st Observation (hist2 = no)</h5>
<p>Logit for “over a year ago” ([1]) vs “never” ([3]):</p>
<p><span class="math display">\[
\text{logit}(P(\text{me3} = 1)) = \beta_0^{[1]} + \beta_{\text{hist2yes}}^{[1]} \cdot \text{hist2}
\]</span> <span class="math display">\[
= -1.2504928 + 1.0093308 \cdot 0
\]</span> <span class="math display">\[
= -1.2504928 + 0
\]</span> <span class="math display">\[
= -1.2504928
\]</span></p>
<hr>
<p>Logit for “within a year” ([2]) vs “never” ([3]):</p>
<p><span class="math display">\[
\text{logit}(P(\text{me3} = 2)) = \beta_0^{[2]} + \beta_{\text{hist2yes}}^{[2]} \cdot \text{hist2}
\]</span> <span class="math display">\[
= -0.9509763 + 1.2565379 \cdot 0
\]</span> <span class="math display">\[
= -0.9509763 + 0
\]</span> <span class="math display">\[
= -0.9509763
\]</span></p>
</section><section id="rd-observation-hist2-yes" class="level5" data-number="4.3.1.1.2"><h5 data-number="4.3.1.1.2" class="anchored" data-anchor-id="rd-observation-hist2-yes">
<span class="header-section-number">4.3.1.1.2</span> 3rd Observation (hist2 = yes)</h5>
<p>Logit for “over a year ago” ([1]) vs “never” ([3]):</p>
<p><span class="math display">\[
\text{logit}(P(\text{me3} = 1)) = \beta_0^{[1]} + \beta_{\text{hist2yes}}^{[1]} \cdot \text{hist2}
\]</span> <span class="math display">\[
= -1.2504928 + 1.0093308 \cdot 1
\]</span> <span class="math display">\[
= -1.2504928 + 1.0093308
\]</span> <span class="math display">\[
= -0.241162
\]</span></p>
<hr>
<p>Logit for “within a year” ([2]) vs “never” ([3]):</p>
<p><span class="math display">\[
\text{logit}(P(\text{me3} = 2)) = \beta_0^{[2]} + \beta_{\text{hist2yes}}^{[2]} \cdot \text{hist2}
\]</span> <span class="math display">\[
= -0.9509763 + 1.2565379 \cdot 1
\]</span> <span class="math display">\[
= -0.9509763 + 1.2565379
\]</span> <span class="math display">\[
= 0.3053816
\]</span></p>
</section></section></section><section id="predict-the-probability" class="level3" data-number="4.3.2"><h3 data-number="4.3.2" class="anchored" data-anchor-id="predict-the-probability">
<span class="header-section-number">4.3.2</span> Predict the Probability</h3>
<p>Using <code>fitmlog1</code> model, the log odds for the 1st observation:</p>
<ul>
<li>Log odds for “over a year ago”: -1.2504928</li>
<li>Log odds for “within a year”: -0.9509763</li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb57"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Predicts the probabilities for the first 6 observations</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/VGAM/man/notdocumentedyet.html">predict.vgam</a></span><span class="op">(</span><span class="va">fitmlog1</span>, type <span class="op">=</span> <span class="st">'response'</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  over.a.year.ago within.a.year     never
1       0.1711957     0.2309783 0.5978261
2       0.1711957     0.2309783 0.5978261
3       0.2500000     0.4318182 0.3181818
4       0.1711957     0.2309783 0.5978261
5       0.1711957     0.2309783 0.5978261
6       0.1711957     0.2309783 0.5978261</code></pre>
</div>
</div>
<hr>
<ul>
<li>
<strong><code>predict.vgam(fitmlog1, type = 'response')</code></strong>: Predicts the probabilities for each outcome category for the observations using the model <code>fitmlog1</code>. The <code>type = 'response'</code> option specifies that the predictions should be on the probability scale.</li>
<li>
<strong><code><a href="https://rdrr.io/r/utils/head.html">head()</a></code></strong>: Displays the first 6 observations.</li>
<li>
<strong>over.a.year.ago</strong>: Probability of being in the “over a year ago” category.</li>
<li>
<strong>within.a.year</strong>: Probability of being in the “within a year” category.</li>
<li>
<strong>never</strong>: Probability of being in the “never” category.</li>
</ul>
<p>The calculations below demonstrate how to use the predicted log odds to derive the probabilities for each outcome category, ensuring that the probabilities sum to 1 for each observation.</p>
<section id="probability-of-being-in-the-reference-group-never" class="level4" data-number="4.3.2.1"><h4 data-number="4.3.2.1" class="anchored" data-anchor-id="probability-of-being-in-the-reference-group-never">
<span class="header-section-number">4.3.2.1</span> Probability of Being in the Reference Group (“Never”)</h4>
<p><span class="math display">\[
P(\text{me3} = \text{never}) = \frac{1}{1 + \exp(\text{logit}_{\text{over a year ago}}) + \exp(\text{logit}_{\text{within a year}})}
\]</span> <span class="math display">\[
P(\text{me3} = \text{never}) = \frac{1}{1 + \exp(-1.2504928) + \exp(-0.9509763)}
\]</span> <span class="math display">\[
= \frac{1}{1 + 0.2865693 + 0.3867897}
\]</span> <span class="math display">\[
= \frac{1}{1.673359}
\]</span> <span class="math display">\[
= 0.5978261
\]</span></p>
</section><section id="probability-of-being-in-the-over-a-year-ago-group" class="level4" data-number="4.3.2.2"><h4 data-number="4.3.2.2" class="anchored" data-anchor-id="probability-of-being-in-the-over-a-year-ago-group">
<span class="header-section-number">4.3.2.2</span> Probability of Being in the “Over a Year Ago” Group</h4>
<p><span class="math display">\[
P(\text{me3} = \text{over a year ago}) = \frac{\exp(\text{logit}_{\text{over a year ago}})}{1 + \exp(\text{logit}_{\text{over a year ago}}) + \exp(\text{logit}_{\text{within a year}})}
\]</span> <span class="math display">\[
P(\text{me3} = \text{over a year ago}) = \frac{\exp(-1.2504928)}{1 + \exp(-1.2504928) + \exp(-0.9509763)}
\]</span> <span class="math display">\[
= \frac{0.2865693}{1 + 0.2865693 + 0.3867897}
\]</span> <span class="math display">\[
= \frac{0.2865693}{1.673359}
\]</span> <span class="math display">\[
= 0.1711957
\]</span></p>
</section><section id="probability-of-being-in-the-within-a-year-group" class="level4" data-number="4.3.2.3"><h4 data-number="4.3.2.3" class="anchored" data-anchor-id="probability-of-being-in-the-within-a-year-group">
<span class="header-section-number">4.3.2.3</span> Probability of Being in the “Within a Year” Group</h4>
<p><span class="math display">\[
P(\text{me3} = \text{within a year}) = \frac{\exp(\text{logit}_{\text{within a year}})}{1 + \exp(\text{logit}_{\text{over a year ago}}) + \exp(\text{logit}_{\text{within a year}})}
\]</span> <span class="math display">\[
P(\text{me3} = \text{within a year}) = \frac{\exp(-0.9509763)}{1 + \exp(-1.2504928) + \exp(-0.9509763)}
\]</span> <span class="math display">\[
= \frac{0.3867897}{1 + 0.2865693 + 0.3867897}
\]</span> <span class="math display">\[
= \frac{0.3867897}{1.673359}
\]</span> <span class="math display">\[
= 0.2309783
\]</span></p>
</section></section></section></section><section id="practical-3-alternative-approach" class="level1" data-number="5"><h1 data-number="5">
<span class="header-section-number">5</span> Practical 3: Alternative Approach</h1>
<p>This exercise demonstrates an alternative approach to fitting a multinomial logistic regression model using the <code>multinom</code> function from the <code>nnet</code> package. It includes steps to fit the model, change the reference category, extract p-values, and compute confidence intervals.</p>
<p>In the <code><a href="https://rdrr.io/pkg/VGAM/man/vglm.html">VGAM::vglm</a></code> function, the reference group is the category with the largest number of observations. In contrast, the <code><a href="https://rdrr.io/pkg/nnet/man/multinom.html">nnet::multinom</a></code> function uses the category with the smallest number of observations as the reference group.</p>
<section id="estimation-3" class="level2" data-number="5.1"><h2 data-number="5.1" class="anchored" data-anchor-id="estimation-3">
<span class="header-section-number">5.1</span> Estimation</h2>
<section id="fitting-the-model" class="level3" data-number="5.1.1"><h3 data-number="5.1.1" class="anchored" data-anchor-id="fitting-the-model">
<span class="header-section-number">5.1.1</span> Fitting the Model</h3>
<div class="cell">
<div class="sourceCode" id="cb59"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Fit the multinomial logistic regression model</span></span>
<span><span class="va">mlog_nnet1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/nnet/man/multinom.html">multinom</a></span><span class="op">(</span><span class="va">me3</span> <span class="op">~</span> <span class="va">hist2</span>, data <span class="op">=</span> <span class="va">dat.m3</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  9 (4 variable)
initial  value 452.628263 
final  value 396.169969 
converged</code></pre>
</div>
<div class="sourceCode" id="cb61"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Summary of the model</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mlog_nnet1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
multinom(formula = me3 ~ hist2, data = dat.m3)

Coefficients:
              (Intercept)   hist2yes
within.a.year   0.2995173  0.2470274
never           1.2504941 -1.0093349

Std. Errors:
              (Intercept) hist2yes
within.a.year   0.1662460 0.413737
never           0.1428933 0.427500

Residual Deviance: 792.3399 
AIC: 800.3399 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Note that the reference group here is “over.a.year.ago” instead of “never.”</p>
</div>
</div>
</section><section id="changing-the-reference-category" class="level3" data-number="5.1.2"><h3 data-number="5.1.2" class="anchored" data-anchor-id="changing-the-reference-category">
<span class="header-section-number">5.1.2</span> Changing the Reference Category</h3>
<div class="cell">
<div class="sourceCode" id="cb63"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Create new dataset and change the reference category</span></span>
<span><span class="va">dat.m4</span> <span class="op">&lt;-</span> <span class="va">dat.m3</span></span>
<span><span class="va">dat.m4</span> <span class="op">&lt;-</span> <span class="va">dat.m4</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>me4 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/relevel.html">relevel</a></span><span class="op">(</span><span class="va">me3</span>, ref <span class="op">=</span> <span class="st">"never"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Recheck the order of categories</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">dat.m4</span><span class="op">$</span><span class="va">me4</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "never"           "over.a.year.ago" "within.a.year"  </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb65"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Fit the model with the new reference category</span></span>
<span><span class="va">mlog_nnet2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/nnet/man/multinom.html">multinom</a></span><span class="op">(</span><span class="va">me4</span><span class="op">~</span> <span class="va">hist2</span>, data <span class="op">=</span> <span class="va">dat.m4</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  9 (4 variable)
initial  value 452.628263 
iter  10 value 396.169969
iter  10 value 396.169969
final  value 396.169969 
converged</code></pre>
</div>
<div class="sourceCode" id="cb67"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Summary of the new model</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mlog_nnet2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
multinom(formula = me4 ~ hist2, data = dat.m4)

Coefficients:
                (Intercept) hist2yes
over.a.year.ago  -1.2504803 1.009384
within.a.year    -0.9509794 1.256531

Std. Errors:
                (Intercept)  hist2yes
over.a.year.ago   0.1428926 0.4275097
within.a.year     0.1277115 0.3746633

Residual Deviance: 792.3399 
AIC: 800.3399 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The reference category is changed to “never,” which affects the interpretation of the coefficients.</p>
</div>
</div>
</section></section><section id="inferences-2" class="level2" data-number="5.2"><h2 data-number="5.2" class="anchored" data-anchor-id="inferences-2">
<span class="header-section-number">5.2</span> Inferences</h2>
<section id="getting-p-values" class="level3" data-number="5.2.1"><h3 data-number="5.2.1" class="anchored" data-anchor-id="getting-p-values">
<span class="header-section-number">5.2.1</span> Getting P-Values</h3>
<div class="cell">
<div class="sourceCode" id="cb69"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Calculate z-values</span></span>
<span><span class="va">z.test</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mlog_nnet2</span><span class="op">)</span><span class="op">$</span><span class="va">coefficients</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mlog_nnet2</span><span class="op">)</span><span class="op">$</span><span class="va">standard.errors</span></span>
<span></span>
<span><span class="co"># Calculate p-values</span></span>
<span><span class="va">p.val</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="va">z.test</span><span class="op">)</span>, <span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="op">*</span> <span class="fl">2</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">p.val</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'p-val intercept'</span>, <span class="st">'p-val hist'</span><span class="op">)</span></span>
<span><span class="va">p.val</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                p-val intercept   p-val hist
over.a.year.ago    0.000000e+00 0.0182218315
within.a.year      9.592327e-14 0.0007972127</code></pre>
</div>
</div>
<hr>
<ul>
<li>
<strong>z.test</strong>: z-values calculated by dividing coefficients by their standard errors.</li>
<li>
<strong>p.val</strong>: Two-tailed p-values calculated from the z-values.</li>
</ul></section><section id="confidence-intervals" class="level3" data-number="5.2.2"><h3 data-number="5.2.2" class="anchored" data-anchor-id="confidence-intervals">
<span class="header-section-number">5.2.2</span> Confidence Intervals</h3>
<div class="cell">
<div class="sourceCode" id="cb71"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Calculate confidence intervals</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">mlog_nnet2</span>, level <span class="op">=</span> <span class="fl">0.95</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>, , over.a.year.ago

                 2.5 %     97.5 %
(Intercept) -1.5305447 -0.9704159
hist2yes     0.1714807  1.8472880

, , within.a.year

                 2.5 %     97.5 %
(Intercept) -1.2012893 -0.7006696
hist2yes     0.5222045  1.9908576</code></pre>
</div>
</div>
<hr>
<ul>
<li>
<strong>Confidence intervals</strong>: Provide a range within which the true coefficient values are expected to lie with 95% confidence.</li>
</ul></section></section></section><section id="acknowledgment" class="level1" data-number="6"><h1 data-number="6">
<span class="header-section-number">6</span> Acknowledgment</h1>
<p>I would like to express my gratitude to <a href="https://myanalytics.com.my/">Professor Dr.&nbsp;Kamarul Imran Musa</a>, Medical Epidemiologist and Statistician, and Professor in Epidemiology and Biostatistics at the School of Medical Sciences, Universiti Sains Malaysia, for his teaching and guidance on the subject matter.</p>
</section><section id="references" class="level1" data-number="7"><h1 data-number="7">
<span class="header-section-number">7</span> References</h1>
<ul>
<li>Lecture on Multinomial Logistic Regression by <a href="https://myanalytics.com.my/">Professor Dr.&nbsp;Kamarul Imran Musa</a>.</li>
<li>
<a href="https://stats.idre.ucla.edu/stata/examples/alr2/applied-logistic-regression-second-edition-by-hosmer-and-lemeshowchapter-8-special-topics/">Applied Logistic Regression, Second Edition by Hosmer and Lemeshow, Chapter 8: Special Topics</a>. UCLA Institute for Digital Research &amp; Education.</li>
<li>
<a href="https://onlinecourses.science.psu.edu/stat504/node/171">STAT 504: Analysis of Discrete Data, Lesson 11: Multinomial Logistic Regression</a>. Penn State Eberly College of Science.</li>
<li>
<a href="https://stats.idre.ucla.edu/r/dae/multinomial-logistic-regression/">R Data Analysis Examples: Multinomial Logistic Regression</a>. UCLA Institute for Digital Research &amp; Education.</li>
<li>
<a href="https://cran.r-project.org/web/packages/mlogit/vignettes/mlogit.pdf">The mlogit Package: Multinomial Logit Models in R</a>. Croissant, Y. (2021).</li>
<li>Long, J. S., &amp; Freese, J. “Models for Nominal Outcomes.” In <em>Regression Models for Categorical Dependent Variables Using Stata</em> (3rd ed.). Stata Press.</li>
<li>Hosmer, D. W. Jr., Lemeshow, S., &amp; Sturdivant, R. X. (2013). <em>Special Topics</em>. In <em>Applied Logistic Regression</em> (3rd ed.). Wiley.</li>
</ul></section><section id="r-codes" class="level1" data-number="8"><h1 data-number="8">
<span class="header-section-number">8</span> R Codes</h1>
<p>The R codes used in this analysis are available at the following GitHub repository: <a href="https://github.com/drsaufi/DrPH-Epidemiology-Revision.git">DrPH-Epidemiology-Revision</a>. This repository includes all scripts and data necessary to replicate the analyses presented in this work.</p>
</section></main><!-- /main column -->
&nbsp;
<hr>
<p style="text-align: center;">A dedicated work by Dr Muhammad Saufi</p>

<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- Add font awesome icons --><p style="text-align: center;">
    <a href="https://www.facebook.com/drsaufimbbch/" class="fa fa-facebook"></a>
    <a href="https://github.com/drsaufi" class="fa fa-github"></a>
    <a href="mailto:drsaufimbbch@gmail.com" class="fa fa-envelope"></a>
</p>

&nbsp;
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>