<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Dr Muhammad Saufi">
<meta name="dcterms.date" content="2024-06-19">
<title>Ordinal Logistic Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="Ordinal Logistic Regression_files/libs/clipboard/clipboard.min.js"></script>
<script src="Ordinal Logistic Regression_files/libs/quarto-html/quarto.js"></script>
<script src="Ordinal Logistic Regression_files/libs/quarto-html/popper.min.js"></script>
<script src="Ordinal Logistic Regression_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Ordinal Logistic Regression_files/libs/quarto-html/anchor.min.js"></script>
<link href="Ordinal Logistic Regression_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Ordinal Logistic Regression_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="Ordinal Logistic Regression_files/libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="Ordinal Logistic Regression_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Ordinal Logistic Regression_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Ordinal Logistic Regression_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="Ordinal Logistic Regression_files/libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="styles.css">
</head>
<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="1"><h2 id="toc-title">Contents</h2>
   
  <ul>
<li>
<a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a>
  <ul>
<li><a href="#adjacent-category-logit-model" id="toc-adjacent-category-logit-model" class="nav-link" data-scroll-target="#adjacent-category-logit-model"><span class="header-section-number">1.1</span> Adjacent-Category Logit Model</a></li>
  <li><a href="#continuation-ratio-logit-model" id="toc-continuation-ratio-logit-model" class="nav-link" data-scroll-target="#continuation-ratio-logit-model"><span class="header-section-number">1.2</span> Continuation-Ratio Logit Model</a></li>
  <li><a href="#proportional-odds-model-cumulative-logit-model" id="toc-proportional-odds-model-cumulative-logit-model" class="nav-link" data-scroll-target="#proportional-odds-model-cumulative-logit-model"><span class="header-section-number">1.3</span> Proportional Odds Model (Cumulative Logit Model)</a></li>
  </ul>
</li>
  <li><a href="#setting-up-the-environment" id="toc-setting-up-the-environment" class="nav-link" data-scroll-target="#setting-up-the-environment"><span class="header-section-number">2</span> Setting Up the Environment</a></li>
  <li>
<a href="#practical-1" id="toc-practical-1" class="nav-link" data-scroll-target="#practical-1"><span class="header-section-number">3</span> Practical 1</a>
  <ul>
<li><a href="#data-reading-and-exploration" id="toc-data-reading-and-exploration" class="nav-link" data-scroll-target="#data-reading-and-exploration"><span class="header-section-number">3.1</span> Data Reading and Exploration</a></li>
  <li><a href="#estimation" id="toc-estimation" class="nav-link" data-scroll-target="#estimation"><span class="header-section-number">3.2</span> Estimation</a></li>
  <li>
<a href="#inferences" id="toc-inferences" class="nav-link" data-scroll-target="#inferences"><span class="header-section-number">3.3</span> Inferences</a>
  <ul>
<li><a href="#wald-based-p-values" id="toc-wald-based-p-values" class="nav-link" data-scroll-target="#wald-based-p-values"><span class="header-section-number">3.3.1</span> Wald-Based P-Values</a></li>
  <li><a href="#calculating-confidence-intervals" id="toc-calculating-confidence-intervals" class="nav-link" data-scroll-target="#calculating-confidence-intervals"><span class="header-section-number">3.3.2</span> Calculating Confidence Intervals</a></li>
  <li><a href="#model-comparison-using-likelihood-ratio-test" id="toc-model-comparison-using-likelihood-ratio-test" class="nav-link" data-scroll-target="#model-comparison-using-likelihood-ratio-test"><span class="header-section-number">3.3.3</span> Model Comparison using Likelihood Ratio Test</a></li>
  </ul>
</li>
  <li>
<a href="#checking-proportional-odds-assumption" id="toc-checking-proportional-odds-assumption" class="nav-link" data-scroll-target="#checking-proportional-odds-assumption"><span class="header-section-number">3.4</span> Checking Proportional Odds Assumption</a>
  <ul>
<li><a href="#method-1-using-nominal_test-function" id="toc-method-1-using-nominal_test-function" class="nav-link" data-scroll-target="#method-1-using-nominal_test-function"><span class="header-section-number">3.4.1</span> Method 1: Using <code>nominal_test</code> Function</a></li>
  <li><a href="#method-2-likelihood-ratio-test" id="toc-method-2-likelihood-ratio-test" class="nav-link" data-scroll-target="#method-2-likelihood-ratio-test"><span class="header-section-number">3.4.2</span> Method 2: Likelihood Ratio Test</a></li>
  </ul>
</li>
  <li>
<a href="#prediction" id="toc-prediction" class="nav-link" data-scroll-target="#prediction"><span class="header-section-number">3.5</span> Prediction</a>
  <ul>
<li><a href="#method-1-predicting-probabilities-for-existing-data" id="toc-method-1-predicting-probabilities-for-existing-data" class="nav-link" data-scroll-target="#method-1-predicting-probabilities-for-existing-data"><span class="header-section-number">3.5.1</span> Method 1: Predicting Probabilities for Existing Data</a></li>
  <li><a href="#prediction-method-2" id="toc-prediction-method-2" class="nav-link" data-scroll-target="#prediction-method-2"><span class="header-section-number">3.5.2</span> Method 2: Predicting Probabilities for New Data</a></li>
  <li><a href="#method-3-using-polr-function-from-mass-package" id="toc-method-3-using-polr-function-from-mass-package" class="nav-link" data-scroll-target="#method-3-using-polr-function-from-mass-package"><span class="header-section-number">3.5.3</span> Method 3: Using <code>polr</code> Function from <code>MASS</code> Package</a></li>
  <li>
<a href="#manual-calculation-of-predictions" id="toc-manual-calculation-of-predictions" class="nav-link" data-scroll-target="#manual-calculation-of-predictions"><span class="header-section-number">3.5.4</span> Manual Calculation of Predictions</a>
  <ul class="collapse">
<li><a href="#model-summary-of-mod.o1" id="toc-model-summary-of-mod.o1" class="nav-link" data-scroll-target="#model-summary-of-mod.o1"><span class="header-section-number">3.5.4.1</span> Model Summary of <code>mod.o1</code></a></li>
  <li><a href="#new-data-for-prediction" id="toc-new-data-for-prediction" class="nav-link" data-scroll-target="#new-data-for-prediction"><span class="header-section-number">3.5.4.2</span> New Data for Prediction</a></li>
  <li><a href="#obtain-linear-predictors" id="toc-obtain-linear-predictors" class="nav-link" data-scroll-target="#obtain-linear-predictors"><span class="header-section-number">3.5.4.3</span> Obtain Linear Predictors</a></li>
  <li><a href="#extract-coefficients" id="toc-extract-coefficients" class="nav-link" data-scroll-target="#extract-coefficients"><span class="header-section-number">3.5.4.4</span> Extract Coefficients</a></li>
  <li><a href="#calculate-linear-predictors-for-each-observation" id="toc-calculate-linear-predictors-for-each-observation" class="nav-link" data-scroll-target="#calculate-linear-predictors-for-each-observation"><span class="header-section-number">3.5.4.5</span> Calculate Linear Predictors for Each Observation</a></li>
  <li><a href="#calculate-logits" id="toc-calculate-logits" class="nav-link" data-scroll-target="#calculate-logits"><span class="header-section-number">3.5.4.6</span> Calculate Logits</a></li>
  <li><a href="#convert-logits-to-probabilities" id="toc-convert-logits-to-probabilities" class="nav-link" data-scroll-target="#convert-logits-to-probabilities"><span class="header-section-number">3.5.4.7</span> Convert Logits to Probabilities</a></li>
  <li><a href="#calculate-category-probabilities" id="toc-calculate-category-probabilities" class="nav-link" data-scroll-target="#calculate-category-probabilities"><span class="header-section-number">3.5.4.8</span> Calculate Category Probabilities</a></li>
  <li><a href="#confirm-predictions-with-the-model" id="toc-confirm-predictions-with-the-model" class="nav-link" data-scroll-target="#confirm-predictions-with-the-model"><span class="header-section-number">3.5.4.9</span> Confirm Predictions with the Model</a></li>
  </ul>
</li>
  </ul>
</li>
  </ul>
</li>
  <li>
<a href="#practical-2" id="toc-practical-2" class="nav-link" data-scroll-target="#practical-2"><span class="header-section-number">4</span> Practical 2</a>
  <ul>
<li>
<a href="#data-reading-and-exploration-1" id="toc-data-reading-and-exploration-1" class="nav-link" data-scroll-target="#data-reading-and-exploration-1"><span class="header-section-number">4.1</span> Data Reading and Exploration</a>
  <ul>
<li><a href="#converting-variables-to-factor-variables" id="toc-converting-variables-to-factor-variables" class="nav-link" data-scroll-target="#converting-variables-to-factor-variables"><span class="header-section-number">4.1.1</span> Converting Variables to Factor Variables</a></li>
  <li><a href="#creating-a-categorical-outcome-variable" id="toc-creating-a-categorical-outcome-variable" class="nav-link" data-scroll-target="#creating-a-categorical-outcome-variable"><span class="header-section-number">4.1.2</span> Creating a Categorical Outcome Variable</a></li>
  <li><a href="#creating-an-ordinal-variable" id="toc-creating-an-ordinal-variable" class="nav-link" data-scroll-target="#creating-an-ordinal-variable"><span class="header-section-number">4.1.3</span> Creating an Ordinal Variable</a></li>
  </ul>
</li>
  <li><a href="#baseline-logit-model" id="toc-baseline-logit-model" class="nav-link" data-scroll-target="#baseline-logit-model"><span class="header-section-number">4.2</span> Baseline Logit Model</a></li>
  <li>
<a href="#continuation-ratio-model" id="toc-continuation-ratio-model" class="nav-link" data-scroll-target="#continuation-ratio-model"><span class="header-section-number">4.3</span> Continuation Ratio Model</a>
  <ul>
<li><a href="#first-model" id="toc-first-model" class="nav-link" data-scroll-target="#first-model"><span class="header-section-number">4.3.1</span> First Model</a></li>
  <li>
<a href="#second-model" id="toc-second-model" class="nav-link" data-scroll-target="#second-model"><span class="header-section-number">4.3.2</span> Second Model</a>
  <ul class="collapse">
<li><a href="#third-model" id="toc-third-model" class="nav-link" data-scroll-target="#third-model"><span class="header-section-number">4.3.2.1</span> Third Model</a></li>
  </ul>
</li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">4.3.3</span> Conclusion</a></li>
  </ul>
</li>
  </ul>
</li>
  </ul></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Ordinal Logistic Regression</h1>
<p class="subtitle lead">Advanced Categorical Data Analysis</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Dr Muhammad Saufi </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 19, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header><div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
About This Document
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This document serves both learning and practical purposes. It is designed for educational use, aiming to enhance statistical analysis skills and provide clear, organized notes for future reference.</p>
</div>
</div>
</div>
<section id="introduction" class="level1" data-number="1"><h1 data-number="1">
<span class="header-section-number">1</span> Introduction</h1>
<p>Ordinal logistic regression is a statistical analysis used for predicting an ordinal outcome based on one or more predictor variables. An ordinal outcome has categories with a natural order but unknown distances between categories, such as ratings (e.g., poor, fair, good, excellent).</p>
<p>The dependent variable is ordinal, meaning it has a meaningful order. Examples include survey responses (e.g., strongly disagree to strongly agree) or educational attainment (e.g., high school, bachelor’s, master’s, doctorate).</p>
<p>Ordinal logistic regression includes several models that are used to analyze ordinal data. The most common models are:</p>
<ol type="1">
<li>Adjacent-Category Logit Model</li>
<li>Continuation-Ratio Logit Model</li>
<li>Proportional Odds Model (Cumulative Logit Model)</li>
</ol>
<section id="adjacent-category-logit-model" class="level2" data-number="1.1"><h2 data-number="1.1" class="anchored" data-anchor-id="adjacent-category-logit-model">
<span class="header-section-number">1.1</span> Adjacent-Category Logit Model</h2>
<p>This model compares each response category with the next adjacent category. The model can be written as:</p>
<p><span class="math display">\[
\log \left( \frac{P(Y = j)}{P(Y = j+1)} \right) = \alpha_j + \beta X
\]</span></p>
<ul>
<li>
<span class="math inline">\(Y\)</span> is the ordinal response variable.</li>
<li>
<span class="math inline">\(j\)</span> is the category.</li>
<li>
<span class="math inline">\(\alpha_j\)</span> are the intercepts for the <span class="math inline">\(j\)</span>-th category.</li>
<li>
<span class="math inline">\(\beta\)</span> is the coefficient for the predictor variable <span class="math inline">\(X\)</span>.</li>
</ul>
<p>The model assumes that the log-odds do not depend on the specific category being compared. The model helps understand how the odds change from one category to the next adjacent category based on the predictor variables.</p>
</section><section id="continuation-ratio-logit-model" class="level2" data-number="1.2"><h2 data-number="1.2" class="anchored" data-anchor-id="continuation-ratio-logit-model">
<span class="header-section-number">1.2</span> Continuation-Ratio Logit Model</h2>
<p>This model is used to compare each response category with all lower categories combined. The model can be written as:</p>
<p><span class="math display">\[
\log \left( \frac{P(Y = j)}{P(Y &lt; j)} \right) = \alpha_j + \beta X
\]</span></p>
<ul>
<li>
<span class="math inline">\(Y\)</span> is the ordinal response variable.</li>
<li>
<span class="math inline">\(j\)</span> is the category.</li>
<li>
<span class="math inline">\(\alpha_j\)</span> are the intercepts for the <span class="math inline">\(j\)</span>-th category.</li>
<li>
<span class="math inline">\(\beta\)</span> is the coefficient for the predictor variable <span class="math inline">\(X\)</span>.</li>
</ul>
<p>Different constant terms and slopes are allowed, making it more flexible. The model compares the probability of being in a particular category to the probability of being in all lower categories combined, providing detailed insights into transitions between levels.</p>
</section><section id="proportional-odds-model-cumulative-logit-model" class="level2" data-number="1.3"><h2 data-number="1.3" class="anchored" data-anchor-id="proportional-odds-model-cumulative-logit-model">
<span class="header-section-number">1.3</span> Proportional Odds Model (Cumulative Logit Model)</h2>
<p>The Proportional Odds Model is used to model the cumulative probabilities of the ordinal outcome variable. The model compares the cumulative probability of the response being in a category less than or equal to a specific value versus being in a higher category:</p>
<p><span class="math display">\[
\log \left( \frac{P(Y \leq j)}{P(Y &gt; j)} \right) = \alpha_j + \beta X
\]</span></p>
<ul>
<li>
<span class="math inline">\(Y\)</span> is the ordinal response variable.</li>
<li>
<span class="math inline">\(j\)</span> is the category.</li>
<li>
<span class="math inline">\(\alpha_j\)</span> are the intercepts for the <span class="math inline">\(j\)</span>-th category.</li>
<li>
<span class="math inline">\(\beta\)</span> is the coefficient for the predictor variable <span class="math inline">\(X\)</span>.</li>
</ul>
<p>The relationship between predictors and the log-odds of being in a lower versus higher category is constant across all categories. The coefficients <span class="math inline">\(\beta\)</span> indicate the effect of the predictors on the log-odds of the outcome being at or below a certain category versus above it.</p>
</section></section><section id="setting-up-the-environment" class="level1" data-number="2"><h1 data-number="2">
<span class="header-section-number">2</span> Setting Up the Environment</h1>
<p>Load the necessary libraries to ensure the R environment is equipped with the tools and functions required for efficient and effective analysis.</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/runehaubo/ordinal">ordinal</a></span><span class="op">)</span> <span class="co"># to perform ordinal model</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span> <span class="co"># data wrangling</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://haven.tidyverse.org">haven</a></span><span class="op">)</span> <span class="co"># to read statistical data</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://broom.tidymodels.org/">broom</a></span><span class="op">)</span> <span class="co"># to tidy results</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/ddsjoberg/gtsummary">gtsummary</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://www.stat.auckland.ac.nz/~yee/VGAM/">VGAM</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://benjaminschlegel.ch/r/brant/">brant</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section><section id="practical-1" class="level1" data-number="3"><h1 data-number="3">
<span class="header-section-number">3</span> Practical 1</h1>
<p>The <code>wine</code> dataset used in this exercise is used to illustrate how to apply cumulative link models (Proportional Odds Models) for analyzing ordinal data. This dataset contains 72 observations and 6 variables.</p>
<ol type="1">
<li>
<strong>response</strong>: A numeric variable representing the response value.</li>
<li>
<strong>rating</strong>: An ordinal factor variable with levels indicating the bitterness rating of the wine (from 1 to 5, with 1 being the least bitter and 5 being the most bitter).</li>
<li>
<strong>temp</strong>: A factor variable indicating the temperature at which the wine was served (e.g., cold, warm).</li>
<li>
<strong>contact</strong>: A factor variable indicating whether the wine had contact with air (e.g., yes, no).</li>
<li>
<strong>bottle</strong>: A numeric variable representing different bottle codes.</li>
<li>
<strong>judge</strong>: A factor variable representing different judges who rated the wine.</li>
</ol>
<section id="data-reading-and-exploration" class="level2" data-number="3.1"><h2 data-number="3.1" class="anchored" data-anchor-id="data-reading-and-exploration">
<span class="header-section-number">3.1</span> Data Reading and Exploration</h2>
<p>First, load the dataset and convert any labeled variables to factors. Then, perform exploratory data analysis to understand the data distribution and relationships between variables.</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Reading the data</span></span>
<span><span class="va">data.o1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://haven.tidyverse.org/reference/read_dta.html">read_dta</a></span><span class="op">(</span><span class="st">"Datasets/wine.dta"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Briefly examine the data</span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">data.o1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Rows: 72
Columns: 6
$ response &lt;dbl&gt; 36, 48, 47, 67, 77, 60, 83, 90, 17, 22, 14, 50, 30, 51, 90, 7…
$ rating   &lt;dbl+lbl&gt; 2, 3, 3, 4, 4, 4, 5, 5, 1, 2, 1, 3, 2, 3, 5, 4, 2, 3, 3, …
$ temp     &lt;dbl+lbl&gt; 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, …
$ contact  &lt;dbl+lbl&gt; 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, …
$ bottle   &lt;dbl+lbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, …
$ judge    &lt;dbl+lbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, …</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Summarize the data</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">data.o1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>    response         rating           temp        contact        bottle    
 Min.   :12.00   Min.   :1.000   Min.   :1.0   Min.   :1.0   Min.   :1.00  
 1st Qu.:32.00   1st Qu.:2.000   1st Qu.:1.0   1st Qu.:1.0   1st Qu.:2.75  
 Median :46.00   Median :3.000   Median :1.5   Median :1.5   Median :4.50  
 Mean   :47.22   Mean   :2.917   Mean   :1.5   Mean   :1.5   Mean   :4.50  
 3rd Qu.:60.00   3rd Qu.:4.000   3rd Qu.:2.0   3rd Qu.:2.0   3rd Qu.:6.25  
 Max.   :90.00   Max.   :5.000   Max.   :2.0   Max.   :2.0   Max.   :8.00  
     judge  
 Min.   :1  
 1st Qu.:3  
 Median :5  
 Mean   :5  
 3rd Qu.:7  
 Max.   :9  </code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Convert labeled variables to factor variables</span></span>
<span><span class="va">data.o2</span> <span class="op">&lt;-</span> <span class="va">data.o1</span></span>
<span><span class="va">data.o2</span> <span class="op">&lt;-</span> <span class="va">data.o2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/across.html">across</a></span><span class="op">(</span><span class="fu"><a href="https://tidyselect.r-lib.org/reference/where.html">where</a></span><span class="op">(</span><span class="va">is.labelled</span><span class="op">)</span>, <span class="op">~</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/as_factor.html">as_factor</a></span><span class="op">(</span><span class="va">.x</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Check the data structure after conversion</span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">data.o2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Rows: 72
Columns: 6
$ response &lt;dbl&gt; 36, 48, 47, 67, 77, 60, 83, 90, 17, 22, 14, 50, 30, 51, 90, 7…
$ rating   &lt;fct&gt; 2, 3, 3, 4, 4, 4, 5, 5, 1, 2, 1, 3, 2, 3, 5, 4, 2, 3, 3, 2, 5…
$ temp     &lt;fct&gt; cold, cold, cold, cold, warm, warm, warm, warm, cold, cold, c…
$ contact  &lt;fct&gt; no, no, yes, yes, no, no, yes, yes, no, no, yes, yes, no, no,…
$ bottle   &lt;fct&gt; 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5…
$ judge    &lt;fct&gt; 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3…</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Summarize the characteristics of the dataset by `rating`</span></span>
<span><span class="va">data.o2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">response</span>, <span class="va">temp</span>, <span class="va">rating</span>, <span class="va">contact</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://www.danieldsjoberg.com/gtsummary/reference/tbl_summary.html">tbl_summary</a></span><span class="op">(</span>by <span class="op">=</span> <span class="va">rating</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div id="nbahnkqmah" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#nbahnkqmah table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#nbahnkqmah thead, #nbahnkqmah tbody, #nbahnkqmah tfoot, #nbahnkqmah tr, #nbahnkqmah td, #nbahnkqmah th {
  border-style: none;
}

#nbahnkqmah p {
  margin: 0;
  padding: 0;
}

#nbahnkqmah .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#nbahnkqmah .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#nbahnkqmah .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#nbahnkqmah .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#nbahnkqmah .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#nbahnkqmah .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#nbahnkqmah .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#nbahnkqmah .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#nbahnkqmah .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#nbahnkqmah .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#nbahnkqmah .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#nbahnkqmah .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#nbahnkqmah .gt_spanner_row {
  border-bottom-style: hidden;
}

#nbahnkqmah .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#nbahnkqmah .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#nbahnkqmah .gt_from_md > :first-child {
  margin-top: 0;
}

#nbahnkqmah .gt_from_md > :last-child {
  margin-bottom: 0;
}

#nbahnkqmah .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#nbahnkqmah .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#nbahnkqmah .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#nbahnkqmah .gt_row_group_first td {
  border-top-width: 2px;
}

#nbahnkqmah .gt_row_group_first th {
  border-top-width: 2px;
}

#nbahnkqmah .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#nbahnkqmah .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#nbahnkqmah .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#nbahnkqmah .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#nbahnkqmah .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#nbahnkqmah .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#nbahnkqmah .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#nbahnkqmah .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#nbahnkqmah .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#nbahnkqmah .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#nbahnkqmah .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#nbahnkqmah .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#nbahnkqmah .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#nbahnkqmah .gt_left {
  text-align: left;
}

#nbahnkqmah .gt_center {
  text-align: center;
}

#nbahnkqmah .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#nbahnkqmah .gt_font_normal {
  font-weight: normal;
}

#nbahnkqmah .gt_font_bold {
  font-weight: bold;
}

#nbahnkqmah .gt_font_italic {
  font-style: italic;
}

#nbahnkqmah .gt_super {
  font-size: 65%;
}

#nbahnkqmah .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#nbahnkqmah .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#nbahnkqmah .gt_indent_1 {
  text-indent: 5px;
}

#nbahnkqmah .gt_indent_2 {
  text-indent: 10px;
}

#nbahnkqmah .gt_indent_3 {
  text-indent: 15px;
}

#nbahnkqmah .gt_indent_4 {
  text-indent: 20px;
}

#nbahnkqmah .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead><tr class="header gt_col_headings">
<th id="<strong>Characteristic</strong>" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><strong>Characteristic</strong></th>
<th id="<strong>1</strong>, N = 5<span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">
<strong>1</strong>, N = 5<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span>
</th>
<th id="<strong>2</strong>, N = 22<span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">
<strong>2</strong>, N = 22<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span>
</th>
<th id="<strong>3</strong>, N = 26<span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">
<strong>3</strong>, N = 26<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span>
</th>
<th id="<strong>4</strong>, N = 12<span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">
<strong>4</strong>, N = 12<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span>
</th>
<th id="<strong>5</strong>, N = 7<span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;><sup>1</sup></span>" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">
<strong>5</strong>, N = 7<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span>
</th>
</tr></thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="label">response</td>
<td class="gt_row gt_center" headers="stat_1">14 (13, 17)</td>
<td class="gt_row gt_center" headers="stat_2">31 (27, 35)</td>
<td class="gt_row gt_center" headers="stat_3">48 (45, 51)</td>
<td class="gt_row gt_center" headers="stat_4">67 (62, 72)</td>
<td class="gt_row gt_center" headers="stat_5">84 (82, 89)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">temp</td>
<td class="gt_row gt_center" headers="stat_1"><br></td>
<td class="gt_row gt_center" headers="stat_2"><br></td>
<td class="gt_row gt_center" headers="stat_3"><br></td>
<td class="gt_row gt_center" headers="stat_4"><br></td>
<td class="gt_row gt_center" headers="stat_5"><br></td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;cold</td>
<td class="gt_row gt_center" headers="stat_1">5 (100%)</td>
<td class="gt_row gt_center" headers="stat_2">16 (73%)</td>
<td class="gt_row gt_center" headers="stat_3">13 (50%)</td>
<td class="gt_row gt_center" headers="stat_4">2 (17%)</td>
<td class="gt_row gt_center" headers="stat_5">0 (0%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;warm</td>
<td class="gt_row gt_center" headers="stat_1">0 (0%)</td>
<td class="gt_row gt_center" headers="stat_2">6 (27%)</td>
<td class="gt_row gt_center" headers="stat_3">13 (50%)</td>
<td class="gt_row gt_center" headers="stat_4">10 (83%)</td>
<td class="gt_row gt_center" headers="stat_5">7 (100%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">contact</td>
<td class="gt_row gt_center" headers="stat_1">1 (20%)</td>
<td class="gt_row gt_center" headers="stat_2">8 (36%)</td>
<td class="gt_row gt_center" headers="stat_3">13 (50%)</td>
<td class="gt_row gt_center" headers="stat_4">9 (75%)</td>
<td class="gt_row gt_center" headers="stat_5">5 (71%)</td>
</tr>
</tbody>
<tfoot class="gt_footnotes"><tr class="even">
<td colspan="6" class="gt_footnote">
<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> Median (IQR); n (%)</td>
</tr></tfoot>
</table>
</div>
</div>
</div>
</section><section id="estimation" class="level2" data-number="3.2"><h2 data-number="3.2" class="anchored" data-anchor-id="estimation">
<span class="header-section-number">3.2</span> Estimation</h2>
<p>The objective is to estimate the cumulative link model (proportional odds model) using the <code>clm</code> function from the <code>ordinal</code> package. This involves estimating regression coefficients, standard errors, and p-values. The cumulative link model (logit link) is specified as:</p>
<p><span class="math display">\[
P(Y_i \leq j) = \theta_j - \beta_1(\text{temp}) - \beta_2(\text{contact})
\]</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(\theta_j\)</span> are the threshold parameters, and <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\beta_2\)</span> are the regression coefficients for <code>temp</code> and <code>contact</code>, respectively.</p>
</div>
</div>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Fit the cumulative link model</span></span>
<span><span class="va">mod.o1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/ordinal/man/clm.html">clm</a></span><span class="op">(</span><span class="va">rating</span> <span class="op">~</span> <span class="va">temp</span> <span class="op">+</span> <span class="va">contact</span>, data <span class="op">=</span> <span class="va">data.o2</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mod.o1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>formula: rating ~ temp + contact
data:    data.o2

 link  threshold nobs logLik AIC    niter max.grad cond.H 
 logit flexible  72   -86.49 184.98 6(0)  4.02e-12 2.7e+01

Coefficients:
           Estimate Std. Error z value Pr(&gt;|z|)    
tempwarm     2.5031     0.5287   4.735 2.19e-06 ***
contactyes   1.5278     0.4766   3.205  0.00135 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Threshold coefficients:
    Estimate Std. Error z value
1|2  -1.3444     0.5171  -2.600
2|3   1.2508     0.4379   2.857
3|4   3.4669     0.5978   5.800
4|5   5.0064     0.7309   6.850</code></pre>
</div>
</div>
<hr>
<p><strong>Summary of Output</strong></p>
<ol type="1">
<li>
<p>Coefficients:</p>
<ul>
<li><p><strong>tempwarm:</strong> The estimated coefficient for <code>tempwarm</code> is 2.5031, meaning that having a warm temperature increases the log odds of being in a higher rating category by 2.5031, compared to the baseline category (cold temperature). The effect is statistically significant at the 0.001 level (p-value = 2.19e-06).</p></li>
<li><p><strong>contactyes:</strong> The estimated coefficient for <code>contactyes</code> is 1.5278, meaning that having contact increases the log odds of being in a higher rating category by 1.5278, compared to the baseline category (no contact). The effect is statistically significant at the 0.01 level (p-value = 0.00135).</p></li>
</ul>
</li>
<li>
<p>Threshold Coefficients</p>
<ul>
<li><p><strong>1|2:</strong> The threshold coefficient of -1.3444 separates the first category from the second. This value indicates the log odds of being in category 1 or lower versus category 2 or higher.</p></li>
<li><p><strong>2|3:</strong> The threshold coefficient of 1.2508 separates the second category from the third. This value indicates the log odds of being in category 2 or lower versus category 3 or higher.</p></li>
<li><p><strong>3|4:</strong> The threshold coefficient of 3.4669 separates the third category from the fourth. This value indicates the log odds of being in category 3 or lower versus category 4 or higher.</p></li>
<li><p><strong>4|5:</strong> The threshold coefficient of 5.0064 separates the fourth category from the fifth. This value indicates the log odds of being in category 4 or lower versus category 5.</p></li>
</ul>
</li>
<li>
<p>Interpretation</p>
<ul>
<li><p><strong>tempwarm:</strong> The estimate is 2.5031 with a p-value of 2.19e-06, indicating a significant positive association between warmer temperature and higher bitterness ratings.</p></li>
<li><p><strong>contactyes:</strong> The estimate is 1.5278 with a p-value of 0.00135, indicating a significant positive association between contact with air and higher bitterness ratings.</p></li>
</ul>
</li>
</ol>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Tidy summary of the model</span></span>
<span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="va">mod.o1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
  term       estimate std.error statistic  p.value coef.type
  &lt;chr&gt;         &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;    
1 1|2           -1.34     0.517     -2.60 9.33e- 3 intercept
2 2|3            1.25     0.438      2.86 4.28e- 3 intercept
3 3|4            3.47     0.598      5.80 6.64e- 9 intercept
4 4|5            5.01     0.731      6.85 7.41e-12 intercept
5 tempwarm       2.50     0.529      4.73 2.19e- 6 location 
6 contactyes     1.53     0.477      3.21 1.35e- 3 location </code></pre>
</div>
</div>
<hr>
<p><strong>Interpretation</strong></p>
<ol type="1">
<li><p><strong>1|2:</strong> The threshold separating category 1 from category 2 has a log-odds estimate of -1.34, which is statistically significant (p-value &lt; 0.01).</p></li>
<li><p><strong>2|3:</strong> The threshold separating category 2 from category 3 has a log-odds estimate of 1.25, which is statistically significant (p-value &lt; 0.01).</p></li>
<li><p><strong>3|4:</strong> The threshold separating category 3 from category 4 has a log-odds estimate of 3.47, which is statistically significant (p-value &lt; 0.001).</p></li>
<li><p><strong>4|5:</strong> The threshold separating category 4 from category 5 has a log-odds estimate of 5.01, which is statistically significant (p-value &lt; 0.001).</p></li>
<li><p><strong>tempwarm:</strong> The log-odds of the response variable being in a higher category increase by 2.50 when the temperature is warm compared to cold. This effect is statistically significant (p-value &lt; 0.001).</p></li>
<li><p><strong>contactyes:</strong> The log-odds of the response variable being in a higher category increase by 1.53 when there is contact compared to no contact. This effect is statistically significant (p-value &lt; 0.01).</p></li>
</ol>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Tidy summary with exponentiated coefficients and confidence intervals</span></span>
<span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="va">mod.o1</span>, exponentiate <span class="op">=</span> <span class="cn">TRUE</span>, conf.int <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 8
  term       estimate std.error statistic  p.value conf.low conf.high coef.type
  &lt;chr&gt;         &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;    
1 1|2           0.261     0.517     -2.60 9.33e- 3    NA         NA   intercept
2 2|3           3.49      0.438      2.86 4.28e- 3    NA         NA   intercept
3 3|4          32.0       0.598      5.80 6.64e- 9    NA         NA   intercept
4 4|5         149.        0.731      6.85 7.41e-12    NA         NA   intercept
5 tempwarm     12.2       0.529      4.73 2.19e- 6     4.53      36.4 location 
6 contactyes    4.61      0.477      3.21 1.35e- 3     1.85      12.1 location </code></pre>
</div>
</div>
<hr>
<p><strong>Interpretation</strong></p>
<ol type="1">
<li><p><strong>1|2:</strong> The odds of being in category 1 or lower versus category 2 or higher are 0.261 times, indicating a decrease in odds, which is statistically significant.</p></li>
<li><p><strong>2|3:</strong> The odds of being in category 2 or lower versus category 3 or higher are 3.49 times, indicating an increase in odds, which is statistically significant.</p></li>
<li><p><strong>3|4:</strong> The odds of being in category 3 or lower versus category 4 or higher are 32 times, indicating a substantial increase in odds, which is statistically significant.</p></li>
<li><p><strong>4|5:</strong> The odds of being in category 4 or lower versus category 5 are 149 times, indicating a substantial increase in odds, which is statistically significant.</p></li>
<li><p><strong>tempwarm:</strong> The odds of the response variable being in a higher category are 12.2 times higher when the temperature is warm compared to cold. This effect is statistically significant, and the confidence interval (4.53 to 36.4) indicates the range within which the true odds ratio is likely to fall with 95% confidence.</p></li>
<li><p><strong>contactyes:</strong> The odds of the response variable being in a higher category are 4.61 times higher when there is contact compared to no contact. This effect is statistically significant, and the confidence interval (1.85 to 12.1) indicates the range within which the true odds ratio is likely to fall with 95% confidence.</p></li>
</ol></section><section id="inferences" class="level2" data-number="3.3"><h2 data-number="3.3" class="anchored" data-anchor-id="inferences">
<span class="header-section-number">3.3</span> Inferences</h2>
<p>The inferences from the fitted cumulative link model are performed by:</p>
<ol type="1">
<li>Checking Wald-based p-values</li>
<li>Calculating confidence intervals</li>
<li>Comparing models</li>
</ol>
<section id="wald-based-p-values" class="level3" data-number="3.3.1"><h3 data-number="3.3.1" class="anchored" data-anchor-id="wald-based-p-values">
<span class="header-section-number">3.3.1</span> Wald-Based P-Values</h3>
<p>Wald-based p-values test whether each parameter (regression coefficient) is significantly different from zero. These were already included in the <code>summary</code> and <code>tidy</code> outputs, showing which predictors are significant.</p>
</section><section id="calculating-confidence-intervals" class="level3" data-number="3.3.2"><h3 data-number="3.3.2" class="anchored" data-anchor-id="calculating-confidence-intervals">
<span class="header-section-number">3.3.2</span> Calculating Confidence Intervals</h3>
<p>Confidence intervals provide a range of values within which the true parameter value is likely to fall. The confidence intervals were displayed in the previous <code>tidy</code> output with <code>conf.int = TRUE</code>.</p>
</section><section id="model-comparison-using-likelihood-ratio-test" class="level3" data-number="3.3.3"><h3 data-number="3.3.3" class="anchored" data-anchor-id="model-comparison-using-likelihood-ratio-test">
<span class="header-section-number">3.3.3</span> Model Comparison using Likelihood Ratio Test</h3>
<p>Let’s compare two nested models using the likelihood ratio test:</p>
<ol type="1">
<li>
<strong>Model <code>mod.o1b</code>:</strong> A simpler model with only <code>temp</code> as the predictor.</li>
<li>
<strong>Model <code>mod.o1</code>:</strong> A more complex model including both <code>temp</code> and <code>contact</code> as predictors.</li>
</ol>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Fit the simpler model</span></span>
<span><span class="va">mod.o1b</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/ordinal/man/clm.html">clm</a></span><span class="op">(</span><span class="va">rating</span> <span class="op">~</span> <span class="va">temp</span>, data <span class="op">=</span> <span class="va">data.o2</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Perform the likelihood ratio test to compare models</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">mod.o1b</span>, <span class="va">mod.o1</span>, test <span class="op">=</span> <span class="st">"Chisq"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stderr">
<pre><code>'test' argument ignored in anova.clm</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Likelihood ratio tests of cumulative link models:
 
        formula:                link: threshold:
mod.o1b rating ~ temp           logit flexible  
mod.o1  rating ~ temp + contact logit flexible  

        no.par    AIC  logLik LR.stat df Pr(&gt;Chisq)    
mod.o1b      5 194.03 -92.013                          
mod.o1       6 184.98 -86.492  11.043  1  0.0008902 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<hr>
<p><strong>Summary of Output</strong></p>
<ul>
<li><p>The p-value of 0.0008902 is highly significant, indicating that adding <code>contact</code> to the model significantly improves the fit compared to the simpler model with only <code>temp</code>.</p></li>
<li><p>Therefore, model <code>o1</code> (which includes both <code>temp</code> and <code>contact</code>) is preferred over model <code>o1b</code>.</p></li>
</ul></section></section><section id="checking-proportional-odds-assumption" class="level2" data-number="3.4"><h2 data-number="3.4" class="anchored" data-anchor-id="checking-proportional-odds-assumption">
<span class="header-section-number">3.4</span> Checking Proportional Odds Assumption</h2>
<p>The proportional odds assumption is crucial for the cumulative link model. It implies that the relationship between each pair of outcome groups is the same. There are two methods to check the proportional odds assumption.</p>
<section id="method-1-using-nominal_test-function" class="level3" data-number="3.4.1"><h3 data-number="3.4.1" class="anchored" data-anchor-id="method-1-using-nominal_test-function">
<span class="header-section-number">3.4.1</span> Method 1: Using <code>nominal_test</code> Function</h3>
<p>The <code><a href="https://rdrr.io/pkg/ordinal/man/nominal.test.html">ordinal::nominal_test()</a></code> function tests the ordinality of each predictor. If the p-value is greater than 0.05, it fails to reject the null hypothesis that the proportional odds assumption holds for that predictor.</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/ordinal/man/nominal.test.html">nominal_test</a></span><span class="op">(</span><span class="va">mod.o1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Tests of nominal effects

formula: rating ~ temp + contact
        Df  logLik    AIC    LRT Pr(&gt;Chi)
&lt;none&gt;     -86.492 184.98                
temp     3 -84.904 187.81 3.1750   0.3654
contact  3 -86.209 190.42 0.5667   0.9040</code></pre>
</div>
</div>
<hr>
<p><strong>Interpretation:</strong></p>
<ul>
<li><p>For both <code>temp</code> and <code>contact</code>, the p-values are greater than 0.05 (0.3654 and 0.9040, respectively).</p></li>
<li><p>This indicates that the assumption of proportional odds cannot be rejected for these variables, suggesting that the proportional odds assumption holds.</p></li>
</ul></section><section id="method-2-likelihood-ratio-test" class="level3" data-number="3.4.2"><h3 data-number="3.4.2" class="anchored" data-anchor-id="method-2-likelihood-ratio-test">
<span class="header-section-number">3.4.2</span> Method 2: Likelihood Ratio Test</h3>
<p>This method involves comparing two models:</p>
<ol type="1">
<li>
<p><strong>Model <code>mod.o1</code></strong></p>
<ul>
<li>This model includes the predictors <code>temp</code> and <code>contact</code> and assumes that the proportional odds assumption holds for all predictors.</li>
</ul>
</li>
<li>
<p><strong>Model <code>mod.o1.nominal</code>:</strong></p>
<ul>
<li><p>This model treats the predictor <code>contact</code> as having nominal effects, meaning it does not assume proportional odds for this predictor.</p></li>
<li><p>Instead, it allows the effect of <code>contact</code> to vary across different thresholds of the ordinal response variable.</p></li>
</ul>
</li>
</ol>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Fit the nominal model</span></span>
<span><span class="va">mod.o1.nominal</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/ordinal/man/clm.html">clm</a></span><span class="op">(</span><span class="va">rating</span> <span class="op">~</span> <span class="va">temp</span>, nominal <span class="op">=</span> <span class="op">~</span><span class="va">contact</span>, data <span class="op">=</span> <span class="va">data.o2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>nominal = ~contact</code> specifies that <code>contact</code> should be treated as having non-proportional effects.</p>
</div>
</div>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Compare the two models using `anova` function</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">mod.o1</span>, <span class="va">mod.o1.nominal</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Likelihood ratio tests of cumulative link models:
 
               formula:                nominal: link: threshold:
mod.o1         rating ~ temp + contact ~1       logit flexible  
mod.o1.nominal rating ~ temp           ~contact logit flexible  

               no.par    AIC  logLik LR.stat df Pr(&gt;Chisq)
mod.o1              6 184.98 -86.492                      
mod.o1.nominal      9 190.42 -86.209  0.5667  3      0.904</code></pre>
</div>
</div>
<hr>
<p><strong>Interpretation:</strong></p>
<ul>
<li><p>The p-value is not significant at the 5% level, indicating that the more complex model (<code>o1.nominal</code>) does not provide a significantly better fit than the simpler model (<code>o1</code>).</p></li>
<li><p>The proportional odds assumption holds for the predictor <code>contact</code>. Therefore, the simpler model (<code>o1</code>), which assumes proportional odds for <code>contact</code>, is adequate.</p></li>
</ul></section></section><section id="prediction" class="level2" data-number="3.5"><h2 data-number="3.5" class="anchored" data-anchor-id="prediction">
<span class="header-section-number">3.5</span> Prediction</h2>
<section id="method-1-predicting-probabilities-for-existing-data" class="level3" data-number="3.5.1"><h3 data-number="3.5.1" class="anchored" data-anchor-id="method-1-predicting-probabilities-for-existing-data">
<span class="header-section-number">3.5.1</span> Method 1: Predicting Probabilities for Existing Data</h3>
<p>This method focuses on predicting the probabilities (fitted probabilities) that each observation in the existing dataset falls into each response category.</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Remove the outcome variable (`rating`)</span></span>
<span><span class="va">new.data1</span> <span class="op">&lt;-</span> <span class="va">data.o2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">-</span><span class="va">rating</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The outcome variable (<code>rating</code>) is removed from the dataset because it is the response variable we want to predict.</p>
</div>
</div>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Predict the probabilities for each category</span></span>
<span><span class="va">prob.mod.o1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">mod.o1</span>, newdata <span class="op">=</span> <span class="va">new.data1</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">prob.mod.o1</span><span class="op">$</span><span class="va">fit</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>           1         2         3          4          5
1 0.20679013 0.5706497 0.1922909 0.02361882 0.00665041
2 0.20679013 0.5706497 0.1922909 0.02361882 0.00665041
3 0.05354601 0.3776461 0.4430599 0.09582084 0.02992711
4 0.05354601 0.3776461 0.4430599 0.09582084 0.02992711
5 0.02088771 0.2014157 0.5015755 0.20049402 0.07562701
6 0.02088771 0.2014157 0.5015755 0.20049402 0.07562701</code></pre>
</div>
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">tail</a></span><span class="op">(</span><span class="va">prob.mod.o1</span><span class="op">$</span><span class="va">fit</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>             1          2         3          4          5
67 0.053546010 0.37764614 0.4430599 0.09582084 0.02992711
68 0.053546010 0.37764614 0.4430599 0.09582084 0.02992711
69 0.020887709 0.20141572 0.5015755 0.20049402 0.07562701
70 0.020887709 0.20141572 0.5015755 0.20049402 0.07562701
71 0.004608274 0.05380128 0.3042099 0.36359581 0.27378469
72 0.004608274 0.05380128 0.3042099 0.36359581 0.27378469</code></pre>
</div>
</div>
<hr>
<ul>
<li><p>The rows correspond to different observations in the dataset.</p></li>
<li><p>The columns represent the predicted probabilities for each response category (1 to 5).</p></li>
</ul>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">class.o1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">mod.o1</span>, type <span class="op">=</span> <span class="st">"class"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">class.o1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>$fit
 [1] 2 2 3 3 3 3 4 4 2 2 3 3 3 3 4 4 2 2 3 3 3 3 4 4 2 2 3 3 3 3 4 4 2 2 3 3 3 3
[39] 4 4 2 2 3 3 3 3 4 4 2 2 3 3 3 3 4 4 2 2 3 3 3 3 4 4 2 2 3 3 3 3 4 4
Levels: 1 2 3 4 5</code></pre>
</div>
</div>
<hr>
<ul>
<li><p>The <code>predict</code> function with <code>type = 'class'</code> is used to predict the most likely category for each observation.</p></li>
<li><p>This output shows the predicted most likely category for each observation, represented by the numbers 1 to 5.</p></li>
</ul></section><section id="prediction-method-2" class="level3" data-number="3.5.2"><h3 data-number="3.5.2" class="anchored" data-anchor-id="prediction-method-2">
<span class="header-section-number">3.5.2</span> Method 2: Predicting Probabilities for New Data</h3>
<p>This method involves predicting the probabilities that new data falls into each response category. This is useful for understanding model behavior under different conditions or for making predictions for hypothetical scenarios. Remember the categories of the outcome are:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">data.o2</span><span class="op">$</span><span class="va">rating</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] "1" "2" "3" "4" "5"</code></pre>
</div>
</div>
<hr>
<p>The linear predictor and predicted probabilites for these categories:</p>
<ol type="1">
<li>temp = cold, contact = no</li>
<li>temp = warm, contact = no</li>
<li>temp = cold, contact = yes</li>
<li>temp = warm, contact = yes</li>
</ol>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Create a new dataset that includes all combinations of the levels of the predictors</span></span>
<span><span class="va">new.data2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/expand.grid.html">expand.grid</a></span><span class="op">(</span>temp <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">data.o2</span><span class="op">$</span><span class="va">temp</span><span class="op">)</span>, contact <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">data.o2</span><span class="op">$</span><span class="va">contact</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">new.data2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>  temp contact
1 cold      no
2 warm      no
3 cold     yes
4 warm     yes</code></pre>
</div>
</div>
<hr>
<ul>
<li>This creates a new data frame with all combinations of <code>temp</code> and <code>contact</code>.</li>
</ul>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Get linear predictors for the new data</span></span>
<span><span class="va">lp.new.data2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">mod.o1</span>, newdata <span class="op">=</span> <span class="va">new.data2</span>, type <span class="op">=</span> <span class="st">"linear.predictor"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Get probabilities for the new data</span></span>
<span><span class="va">prob.new.data2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">mod.o1</span>, newdata <span class="op">=</span> <span class="va">new.data2</span>, type <span class="op">=</span> <span class="st">"prob"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># View the results</span></span>
<span><span class="va">lp.new.data2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>$eta1
          1          2          3         4         5
1 -1.344383  1.2508088  3.4668869 5.0064042 100000.00
2 -3.847485 -1.2522932  0.9637849 2.5033022  99997.50
3 -2.872181 -0.2769889  1.9390893 3.4786065  99998.47
4 -5.375283 -2.7800909 -0.5640127 0.9755045  99995.97

$eta2
          1         2          3          4         5
1 -100000.0 -1.344383  1.2508088  3.4668869 5.0064042
2 -100002.5 -3.847485 -1.2522932  0.9637849 2.5033022
3 -100001.5 -2.872181 -0.2769889  1.9390893 3.4786065
4 -100004.0 -5.375283 -2.7800909 -0.5640127 0.9755045</code></pre>
</div>
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">prob.new.data2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>$fit
            1          2         3          4          5
1 0.206790132 0.57064970 0.1922909 0.02361882 0.00665041
2 0.020887709 0.20141572 0.5015755 0.20049402 0.07562701
3 0.053546010 0.37764614 0.4430599 0.09582084 0.02992711
4 0.004608274 0.05380128 0.3042099 0.36359581 0.27378469</code></pre>
</div>
</div>
<hr>
<ul>
<li><p><strong>$eta1 and $eta2:</strong> Linear predictors for each category.</p></li>
<li><p><strong>$fit:</strong> Predicted probabilities for each category for the new data.</p></li>
</ul>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Combine the new data with the predicted probabilities for a comprehensive view</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">new.data2</span>, <span class="va">prob.new.data2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>  temp contact       fit.1      fit.2     fit.3      fit.4      fit.5
1 cold      no 0.206790132 0.57064970 0.1922909 0.02361882 0.00665041
2 warm      no 0.020887709 0.20141572 0.5015755 0.20049402 0.07562701
3 cold     yes 0.053546010 0.37764614 0.4430599 0.09582084 0.02992711
4 warm     yes 0.004608274 0.05380128 0.3042099 0.36359581 0.27378469</code></pre>
</div>
</div>
</section><section id="method-3-using-polr-function-from-mass-package" class="level3" data-number="3.5.3"><h3 data-number="3.5.3" class="anchored" data-anchor-id="method-3-using-polr-function-from-mass-package">
<span class="header-section-number">3.5.3</span> Method 3: Using <code>polr</code> Function from <code>MASS</code> Package</h3>
<p>This method involves using the <code>polr</code> function from the <code>MASS</code> package to fit a proportional odds model and then predict probabilities for each category of the ordinal response variable.</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Fit the model</span></span>
<span><span class="va">mod_polr</span> <span class="op">&lt;-</span> <span class="fu">MASS</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/MASS/man/polr.html">polr</a></span><span class="op">(</span><span class="va">rating</span> <span class="op">~</span> <span class="va">temp</span> <span class="op">+</span> <span class="va">contact</span>, data <span class="op">=</span> <span class="va">data.o2</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mod_polr</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stderr">
<pre><code>
Re-fitting to get Hessian</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
MASS::polr(formula = rating ~ temp + contact, data = data.o2)

Coefficients:
           Value Std. Error t value
tempwarm   2.503     0.5287   4.735
contactyes 1.528     0.4766   3.205

Intercepts:
    Value   Std. Error t value
1|2 -1.3444  0.5171    -2.5998
2|3  1.2508  0.4379     2.8565
3|4  3.4669  0.5978     5.7998
4|5  5.0064  0.7309     6.8496

Residual Deviance: 172.9838 
AIC: 184.9838 </code></pre>
</div>
</div>
<hr>
<ul>
<li><p>The model is fitted using the <code>polr</code> function from the <code>MASS</code> package. The output provides the estimated coefficients for the predictors and the thresholds (intercepts) for the ordinal response variable.</p></li>
<li><p><code>tempwarm</code>: The coefficient for warm temperature, indicating a significant positive association with higher ratings.</p></li>
<li><p><code>contactyes</code>: The coefficient for contact with air, indicating a significant positive association with higher ratings.</p></li>
</ul>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb43"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Predict the probabilities for each category</span></span>
<span><span class="va">prob_polr</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">mod_polr</span>, type <span class="op">=</span> <span class="st">"probs"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">prob_polr</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>          1         2         3          4           5
1 0.2067917 0.5706466 0.1922920 0.02361917 0.006650532
2 0.2067917 0.5706466 0.1922920 0.02361917 0.006650532
3 0.0535471 0.3776458 0.4430586 0.09582112 0.029927296
4 0.0535471 0.3776458 0.4430586 0.09582112 0.029927296
5 0.0208885 0.2014185 0.5015746 0.20049218 0.075626257
6 0.0208885 0.2014185 0.5015746 0.20049218 0.075626257</code></pre>
</div>
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb45"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">tail</a></span><span class="op">(</span><span class="va">prob_polr</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>             1          2         3          4          5
67 0.053547101 0.37764585 0.4430586 0.09582112 0.02992730
68 0.053547101 0.37764585 0.4430586 0.09582112 0.02992730
69 0.020888502 0.20141847 0.5015746 0.20049218 0.07562626
70 0.020888502 0.20141847 0.5015746 0.20049218 0.07562626
71 0.004608507 0.05380284 0.3042139 0.36359456 0.27378016
72 0.004608507 0.05380284 0.3042139 0.36359456 0.27378016</code></pre>
</div>
</div>
<hr>
<ul>
<li><p>The <code>predict</code> function with <code>type = 'probs'</code> is used to obtain the predicted probabilities for each response category for each observation in the dataset.</p></li>
<li><p>The rows correspond to different observations in the dataset.</p></li>
<li><p>The columns represent the predicted probabilities for each response category (1 to 5).</p></li>
</ul></section><section id="manual-calculation-of-predictions" class="level3" data-number="3.5.4"><h3 data-number="3.5.4" class="anchored" data-anchor-id="manual-calculation-of-predictions">
<span class="header-section-number">3.5.4</span> Manual Calculation of Predictions</h3>
<p>Manually calculate the probabilities for an ordinal outcome using the coefficients from a cumulative link model <code>mod.o1</code>.</p>
<section id="model-summary-of-mod.o1" class="level4" data-number="3.5.4.1"><h4 data-number="3.5.4.1" class="anchored" data-anchor-id="model-summary-of-mod.o1">
<span class="header-section-number">3.5.4.1</span> Model Summary of <code>mod.o1</code>
</h4>
<p>Review the model summary to get the coefficients for the predictors and the threshold values needed for calculations.</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb47"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Model summary</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mod.o1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>formula: rating ~ temp + contact
data:    data.o2

 link  threshold nobs logLik AIC    niter max.grad cond.H 
 logit flexible  72   -86.49 184.98 6(0)  4.02e-12 2.7e+01

Coefficients:
           Estimate Std. Error z value Pr(&gt;|z|)    
tempwarm     2.5031     0.5287   4.735 2.19e-06 ***
contactyes   1.5278     0.4766   3.205  0.00135 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Threshold coefficients:
    Estimate Std. Error z value
1|2  -1.3444     0.5171  -2.600
2|3   1.2508     0.4379   2.857
3|4   3.4669     0.5978   5.800
4|5   5.0064     0.7309   6.850</code></pre>
</div>
</div>
</section><section id="new-data-for-prediction" class="level4" data-number="3.5.4.2"><h4 data-number="3.5.4.2" class="anchored" data-anchor-id="new-data-for-prediction">
<span class="header-section-number">3.5.4.2</span> New Data for Prediction</h4>
<p>The new data points for which predictions are needed are defined using the previously generated new data from <a href="#prediction-method-2">Prediction: Method 2</a>.</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb49"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">new.data2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>  temp contact
1 cold      no
2 warm      no
3 cold     yes
4 warm     yes</code></pre>
</div>
</div>
</section><section id="obtain-linear-predictors" class="level4" data-number="3.5.4.3"><h4 data-number="3.5.4.3" class="anchored" data-anchor-id="obtain-linear-predictors">
<span class="header-section-number">3.5.4.3</span> Obtain Linear Predictors</h4>
<p>Use the <code>predict</code> function with <code>type = "linear.predictor"</code> to get the linear predictors for the new data points, represented by <code>eta1</code> and <code>eta2</code> in the output. Refer <a href="#prediction-method-2">Prediction: Method 2</a>.</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb51"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lp.new.data2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>$eta1
          1          2          3         4         5
1 -1.344383  1.2508088  3.4668869 5.0064042 100000.00
2 -3.847485 -1.2522932  0.9637849 2.5033022  99997.50
3 -2.872181 -0.2769889  1.9390893 3.4786065  99998.47
4 -5.375283 -2.7800909 -0.5640127 0.9755045  99995.97

$eta2
          1         2          3          4         5
1 -100000.0 -1.344383  1.2508088  3.4668869 5.0064042
2 -100002.5 -3.847485 -1.2522932  0.9637849 2.5033022
3 -100001.5 -2.872181 -0.2769889  1.9390893 3.4786065
4 -100004.0 -5.375283 -2.7800909 -0.5640127 0.9755045</code></pre>
</div>
</div>
</section><section id="extract-coefficients" class="level4" data-number="3.5.4.4"><h4 data-number="3.5.4.4" class="anchored" data-anchor-id="extract-coefficients">
<span class="header-section-number">3.5.4.4</span> Extract Coefficients</h4>
<p>Extract the coefficients from the model that include the estimates for the thresholds and the predictor variables:</p>
<ul>
<li>Thresholds: 1|2, 2|3, 3|4, 4|5</li>
<li>Predictors: tempwarm, contactyes</li>
</ul>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb53"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">coef.mod.o1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">mod.o1</span><span class="op">)</span></span>
<span><span class="va">coef.mod.o1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>       1|2        2|3        3|4        4|5   tempwarm contactyes 
 -1.344383   1.250809   3.466887   5.006404   2.503102   1.527798 </code></pre>
</div>
</div>
</section><section id="calculate-linear-predictors-for-each-observation" class="level4" data-number="3.5.4.5"><h4 data-number="3.5.4.5" class="anchored" data-anchor-id="calculate-linear-predictors-for-each-observation">
<span class="header-section-number">3.5.4.5</span> Calculate Linear Predictors for Each Observation</h4>
<p>For each new observation, calculate the linear predictors (bx) using the coefficients and the new data values. Using fourth observation as an example:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb55"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lp.mod.o1.bx4</span> <span class="op">&lt;-</span> <span class="va">coef.mod.o1</span><span class="op">[</span><span class="st">"tempwarm"</span><span class="op">]</span> <span class="op">*</span> <span class="fl">1</span> <span class="op">+</span> <span class="va">coef.mod.o1</span><span class="op">[</span><span class="st">"contactyes"</span><span class="op">]</span> <span class="op">*</span> <span class="fl">1</span></span>
<span><span class="va">lp.mod.o1.bx4</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>tempwarm 
  4.0309 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>This calculates the linear predictor for the fourth observation, where <code>temp</code> is warm (coded as 1) and <code>contact</code> is yes (coded as 1).</p>
</div>
</div>
</section><section id="calculate-logits" class="level4" data-number="3.5.4.6"><h4 data-number="3.5.4.6" class="anchored" data-anchor-id="calculate-logits">
<span class="header-section-number">3.5.4.6</span> Calculate Logits</h4>
<p>Using the linear predictors (bx) and the thresholds, calculate the logits using the formula:</p>
<p><span class="math display">\[
\text{logit}(P(Y \leq j)) = \beta_{0j} - (\beta_1 X_1 + \beta_2 X_2 + \cdots + \beta_p X_p)
\]</span></p>
<ul>
<li>
<strong><span class="math inline">\(\beta_{0j}\)</span></strong>: Threshold coefficient for category <span class="math inline">\(j\)</span>.</li>
<li>
<strong><span class="math inline">\(\beta_1, \beta_2, \ldots, \beta_p\)</span></strong>: Coefficients for the predictor variables.</li>
<li>
<strong><span class="math inline">\(X_1, X_2, \ldots, X_p\)</span></strong>: Values of the predictor variables.</li>
<li>
<strong>Logit Calculation</strong>: The linear predictor (<span class="math inline">\(\beta_1 X_1 + \beta_2 X_2 + \cdots + \beta_p X_p\)</span>) is subtracted from the threshold coefficient to get the logit.</li>
</ul>
<p>Given the threshold coefficients from the model summary:</p>
<ul>
<li><span class="math inline">\(\beta_{01|2} = -1.3444\)</span></li>
<li><span class="math inline">\(\beta_{02|3} = 1.2508\)</span></li>
<li><span class="math inline">\(\beta_{03|4} = 3.4669\)</span></li>
<li><span class="math inline">\(\beta_{04|5} = 5.0064\)</span></li>
</ul>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb57"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">logit1</span> <span class="op">&lt;-</span> <span class="va">coef.mod.o1</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span> <span class="op">-</span> <span class="va">lp.mod.o1.bx4</span></span>
<span><span class="va">logit2</span> <span class="op">&lt;-</span> <span class="va">coef.mod.o1</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span> <span class="op">-</span> <span class="va">lp.mod.o1.bx4</span></span>
<span><span class="va">logit3</span> <span class="op">&lt;-</span> <span class="va">coef.mod.o1</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span> <span class="op">-</span> <span class="va">lp.mod.o1.bx4</span></span>
<span><span class="va">logit4</span> <span class="op">&lt;-</span> <span class="va">coef.mod.o1</span><span class="op">[</span><span class="fl">4</span><span class="op">]</span> <span class="op">-</span> <span class="va">lp.mod.o1.bx4</span></span>
<span><span class="va">logit1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>      1|2 
-5.375283 </code></pre>
</div>
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb59"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">logit2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>      2|3 
-2.780091 </code></pre>
</div>
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb61"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">logit3</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>       3|4 
-0.5640127 </code></pre>
</div>
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb63"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">logit4</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>      4|5 
0.9755045 </code></pre>
</div>
</div>
</section><section id="convert-logits-to-probabilities" class="level4" data-number="3.5.4.7"><h4 data-number="3.5.4.7" class="anchored" data-anchor-id="convert-logits-to-probabilities">
<span class="header-section-number">3.5.4.7</span> Convert Logits to Probabilities</h4>
<p>The probabilities represent the cumulative probabilities for each threshold. The logistic function is used to convert logits (log-odds) into probabilities. The formula for the logistic function:</p>
<p><span class="math display">\[
\text{logit}^{-1}(x) = \frac{1}{1 + e^{-x}}
\]</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(x\)</span> is the logit value.</p>
</div>
</div>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb65"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">pLeq1</span> <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">/</span> <span class="op">(</span><span class="fl">1</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="op">-</span><span class="va">logit1</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">pLeq2</span> <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">/</span> <span class="op">(</span><span class="fl">1</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="op">-</span><span class="va">logit2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">pLeq3</span> <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">/</span> <span class="op">(</span><span class="fl">1</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="op">-</span><span class="va">logit3</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">pLeq4</span> <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">/</span> <span class="op">(</span><span class="fl">1</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="op">-</span><span class="va">logit4</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section><section id="calculate-category-probabilities" class="level4" data-number="3.5.4.8"><h4 data-number="3.5.4.8" class="anchored" data-anchor-id="calculate-category-probabilities">
<span class="header-section-number">3.5.4.8</span> Calculate Category Probabilities</h4>
<p>To find the probability of each specific category, calculate the differences between the cumulative probabilities. This will give the probability of the response falling into each category.</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb66"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">pMat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span></span>
<span>  p1 <span class="op">=</span> <span class="va">pLeq1</span>,</span>
<span>  p2 <span class="op">=</span> <span class="va">pLeq2</span> <span class="op">-</span> <span class="va">pLeq1</span>,</span>
<span>  p3 <span class="op">=</span> <span class="va">pLeq3</span> <span class="op">-</span> <span class="va">pLeq2</span>,</span>
<span>  p4 <span class="op">=</span> <span class="va">pLeq4</span> <span class="op">-</span> <span class="va">pLeq3</span>,</span>
<span>  p5 <span class="op">=</span> <span class="fl">1</span> <span class="op">-</span> <span class="va">pLeq4</span></span>
<span><span class="op">)</span></span>
<span><span class="va">pMat</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>             p1         p2        p3        p4        p5
1|2 0.004608274 0.05380128 0.3042099 0.3635958 0.2737847</code></pre>
</div>
</div>
</section><section id="confirm-predictions-with-the-model" class="level4" data-number="3.5.4.9"><h4 data-number="3.5.4.9" class="anchored" data-anchor-id="confirm-predictions-with-the-model">
<span class="header-section-number">3.5.4.9</span> Confirm Predictions with the Model</h4>
<p>Finally, confirm the manual calculations by comparing them with the predictions from the <code>predict</code> function using <code>type = "prob"</code>. Refer <a href="#method-2">Method 2</a>.</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb68"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">prob.new.data2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>$fit
            1          2         3          4          5
1 0.206790132 0.57064970 0.1922909 0.02361882 0.00665041
2 0.020887709 0.20141572 0.5015755 0.20049402 0.07562701
3 0.053546010 0.37764614 0.4430599 0.09582084 0.02992711
4 0.004608274 0.05380128 0.3042099 0.36359581 0.27378469</code></pre>
</div>
</div>
</section></section></section></section><section id="practical-2" class="level1" data-number="4"><h1 data-number="4">
<span class="header-section-number">4</span> Practical 2</h1>
<p>The <code>lowbwt.dta</code> dataset used in this exercise is sourced from the Applied Logistic Regression book and involves data that are related to logistic regression models for ordinal outcomes.</p>
<p><strong>Variables</strong>:</p>
<ul>
<li>
<code>id</code>: Identification number for each observation.</li>
<li>
<code>lbw</code>: Indicator variable for low birth weight.</li>
<li>
<code>age</code>: Age of the mother in years.</li>
<li>
<code>lwt</code>: Weight of the mother at the last menstrual period in pounds.</li>
<li>
<code>race</code>: Race of the mother.</li>
<li>
<code>smoke</code>: Smoking status during pregnancy.</li>
<li>
<code>ptl</code>: Number of previous premature labors.</li>
<li>
<code>hyper</code>: Presence of hypertension.</li>
<li>
<code>urirr</code>: Presence of uterine irritability.</li>
<li>
<code>pvft</code>: Physician visits during the first trimester.</li>
<li>
<code>weight</code>: Birth weight in grams.</li>
<li>
<code>agecat</code>: Age category of the mother.</li>
<li>
<code>wcat</code>: Weight category of the mother.</li>
<li>
<code>anyptl</code>: Indicator variable for any previous premature labor.</li>
<li>
<code>newpvft</code>: New variable for physician visits during the first trimester.</li>
</ul>
<section id="data-reading-and-exploration-1" class="level2" data-number="4.1"><h2 data-number="4.1" class="anchored" data-anchor-id="data-reading-and-exploration-1">
<span class="header-section-number">4.1</span> Data Reading and Exploration</h2>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb70"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Data reading</span></span>
<span><span class="va">data.o3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://haven.tidyverse.org/reference/read_dta.html">read_dta</a></span><span class="op">(</span><span class="op">(</span><span class="st">"Datasets/lowbwt.dta"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Data summary</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">data.o3</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>       id             lbw              age             lwt       
 Min.   :  4.0   Min.   :0.0000   Min.   :14.00   Min.   : 80.0  
 1st Qu.: 68.0   1st Qu.:0.0000   1st Qu.:19.00   1st Qu.:110.0  
 Median :123.0   Median :0.0000   Median :23.00   Median :121.0  
 Mean   :121.1   Mean   :0.3122   Mean   :23.24   Mean   :129.8  
 3rd Qu.:176.0   3rd Qu.:1.0000   3rd Qu.:26.00   3rd Qu.:140.0  
 Max.   :226.0   Max.   :1.0000   Max.   :45.00   Max.   :250.0  
      race           smoke             ptl             hyper        
 Min.   :1.000   Min.   :0.0000   Min.   :0.0000   Min.   :0.00000  
 1st Qu.:1.000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.00000  
 Median :1.000   Median :0.0000   Median :0.0000   Median :0.00000  
 Mean   :1.847   Mean   :0.3915   Mean   :0.1958   Mean   :0.06349  
 3rd Qu.:3.000   3rd Qu.:1.0000   3rd Qu.:0.0000   3rd Qu.:0.00000  
 Max.   :3.000   Max.   :1.0000   Max.   :3.0000   Max.   :1.00000  
     urirr             pvft            weight         agecat     
 Min.   :0.0000   Min.   :0.0000   Min.   : 709   Min.   :1.000  
 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:2414   1st Qu.:1.000  
 Median :0.0000   Median :0.0000   Median :2977   Median :2.000  
 Mean   :0.1481   Mean   :0.7937   Mean   :2945   Mean   :2.238  
 3rd Qu.:0.0000   3rd Qu.:1.0000   3rd Qu.:3475   3rd Qu.:3.000  
 Max.   :1.0000   Max.   :6.0000   Max.   :4990   Max.   :4.000  
      wcat           anyptl          newpvft      
 Min.   :1.000   Min.   :0.0000   Min.   :0.0000  
 1st Qu.:2.000   1st Qu.:0.0000   1st Qu.:0.0000  
 Median :3.000   Median :0.0000   Median :0.0000  
 Mean   :2.857   Mean   :0.1587   Mean   :0.6931  
 3rd Qu.:4.000   3rd Qu.:0.0000   3rd Qu.:1.0000  
 Max.   :5.000   Max.   :1.0000   Max.   :2.0000  </code></pre>
</div>
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb72"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Detailed view of the dataset</span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">data.o3</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Rows: 189
Columns: 15
$ id      &lt;dbl&gt; 85, 86, 87, 88, 89, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 1…
$ lbw     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ age     &lt;dbl&gt; 19, 33, 20, 21, 18, 21, 22, 17, 29, 26, 19, 19, 22, 30, 18, 18…
$ lwt     &lt;dbl&gt; 182, 155, 105, 108, 107, 124, 118, 103, 123, 113, 95, 150, 95,…
$ race    &lt;dbl&gt; 2, 3, 1, 1, 1, 3, 1, 3, 1, 1, 3, 3, 3, 3, 1, 1, 2, 1, 3, 1, 3,…
$ smoke   &lt;dbl&gt; 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,…
$ ptl     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,…
$ hyper   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,…
$ urirr   &lt;dbl&gt; 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,…
$ pvft    &lt;dbl&gt; 0, 3, 1, 2, 0, 0, 1, 1, 1, 0, 0, 1, 0, 2, 0, 0, 0, 3, 0, 1, 2,…
$ weight  &lt;dbl&gt; 2523, 2551, 2557, 2594, 2600, 2622, 2637, 2637, 2663, 2665, 27…
$ agecat  &lt;dbl+lbl&gt; 1, 4, 2, 2, 1, 2, 2, 1, 3, 3, 1, 1, 2, 4, 1, 1, 1, 3, 2, 3…
$ wcat    &lt;dbl+lbl&gt; 5, 5, 1, 2, 2, 3, 2, 1, 3, 2, 1, 4, 1, 2, 1, 1, 1, 2, 2, 2…
$ anyptl  &lt;dbl+lbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0…
$ newpvft &lt;dbl+lbl&gt; 0, 2, 1, 2, 0, 0, 1, 1, 1, 0, 0, 1, 0, 2, 0, 0, 0, 2, 0, 1…</code></pre>
</div>
</div>
<section id="converting-variables-to-factor-variables" class="level3" data-number="4.1.1"><h3 data-number="4.1.1" class="anchored" data-anchor-id="converting-variables-to-factor-variables">
<span class="header-section-number">4.1.1</span> Converting Variables to Factor Variables</h3>
<p>Since the dataset comes with labeled variables, convert to factor variables using the <code>mutate</code> and <code>across</code> functions from the <code>dplyr</code> package.</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb74"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Copy into new dataset and keep original dataset</span></span>
<span><span class="va">data.o4</span> <span class="op">&lt;-</span> <span class="va">data.o3</span></span>
<span></span>
<span><span class="co"># Convert to factor variables</span></span>
<span><span class="va">data.o4</span> <span class="op">&lt;-</span> <span class="va">data.o4</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/across.html">across</a></span><span class="op">(</span><span class="fu"><a href="https://tidyselect.r-lib.org/reference/where.html">where</a></span><span class="op">(</span><span class="va">is.labelled</span><span class="op">)</span>, <span class="op">~</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/as_factor.html">as_factor</a></span><span class="op">(</span><span class="va">.x</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">data.o4</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>       id             lbw              age             lwt       
 Min.   :  4.0   Min.   :0.0000   Min.   :14.00   Min.   : 80.0  
 1st Qu.: 68.0   1st Qu.:0.0000   1st Qu.:19.00   1st Qu.:110.0  
 Median :123.0   Median :0.0000   Median :23.00   Median :121.0  
 Mean   :121.1   Mean   :0.3122   Mean   :23.24   Mean   :129.8  
 3rd Qu.:176.0   3rd Qu.:1.0000   3rd Qu.:26.00   3rd Qu.:140.0  
 Max.   :226.0   Max.   :1.0000   Max.   :45.00   Max.   :250.0  
      race           smoke             ptl             hyper        
 Min.   :1.000   Min.   :0.0000   Min.   :0.0000   Min.   :0.00000  
 1st Qu.:1.000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.00000  
 Median :1.000   Median :0.0000   Median :0.0000   Median :0.00000  
 Mean   :1.847   Mean   :0.3915   Mean   :0.1958   Mean   :0.06349  
 3rd Qu.:3.000   3rd Qu.:1.0000   3rd Qu.:0.0000   3rd Qu.:0.00000  
 Max.   :3.000   Max.   :1.0000   Max.   :3.0000   Max.   :1.00000  
     urirr             pvft            weight       agecat        wcat   
 Min.   :0.0000   Min.   :0.0000   Min.   : 709   &lt;20  :51   &lt;105   :37  
 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:2414   20-24:69   106-120:55  
 Median :0.0000   Median :0.0000   Median :2977   25-29:42   121-130:31  
 Mean   :0.1481   Mean   :0.7937   Mean   :2945   30+  :27   131-150:30  
 3rd Qu.:0.0000   3rd Qu.:1.0000   3rd Qu.:3475              151+   :36  
 Max.   :1.0000   Max.   :6.0000   Max.   :4990                          
 anyptl   newpvft 
 0 :159   0 :100  
 1+: 30   1 : 47  
          2+: 42  
                  
                  
                  </code></pre>
</div>
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb76"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">data.o4</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Rows: 189
Columns: 15
$ id      &lt;dbl&gt; 85, 86, 87, 88, 89, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 1…
$ lbw     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ age     &lt;dbl&gt; 19, 33, 20, 21, 18, 21, 22, 17, 29, 26, 19, 19, 22, 30, 18, 18…
$ lwt     &lt;dbl&gt; 182, 155, 105, 108, 107, 124, 118, 103, 123, 113, 95, 150, 95,…
$ race    &lt;dbl&gt; 2, 3, 1, 1, 1, 3, 1, 3, 1, 1, 3, 3, 3, 3, 1, 1, 2, 1, 3, 1, 3,…
$ smoke   &lt;dbl&gt; 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,…
$ ptl     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,…
$ hyper   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,…
$ urirr   &lt;dbl&gt; 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,…
$ pvft    &lt;dbl&gt; 0, 3, 1, 2, 0, 0, 1, 1, 1, 0, 0, 1, 0, 2, 0, 0, 0, 3, 0, 1, 2,…
$ weight  &lt;dbl&gt; 2523, 2551, 2557, 2594, 2600, 2622, 2637, 2637, 2663, 2665, 27…
$ agecat  &lt;fct&gt; &lt;20, 30+, 20-24, 20-24, &lt;20, 20-24, 20-24, &lt;20, 25-29, 25-29, …
$ wcat    &lt;fct&gt; 151+, 151+, &lt;105, 106-120, 106-120, 121-130, 106-120, &lt;105, 12…
$ anyptl  &lt;fct&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1+, 0, 0, 0, 0, 0, 0, 0…
$ newpvft &lt;fct&gt; 0, 2+, 1, 2+, 0, 0, 1, 1, 1, 0, 0, 1, 0, 2+, 0, 0, 0, 2+, 0, 1…</code></pre>
</div>
</div>
</section><section id="creating-a-categorical-outcome-variable" class="level3" data-number="4.1.2"><h3 data-number="4.1.2" class="anchored" data-anchor-id="creating-a-categorical-outcome-variable">
<span class="header-section-number">4.1.2</span> Creating a Categorical Outcome Variable</h3>
<p>Create a categorical outcome variable using <code>cut</code> function. The variable <code>weight</code> is categorized into a 4-category variable <code>bwt4</code>.</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb78"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Create categorical outcome variable</span></span>
<span><span class="va">data.o4</span> <span class="op">&lt;-</span> <span class="va">data.o4</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>bwt4 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/cut.html">cut</a></span><span class="op">(</span><span class="va">weight</span>,</span>
<span>    breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">708</span>, <span class="fl">2500</span>, <span class="fl">2999</span>, <span class="fl">3500</span>, <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">weight</span><span class="op">)</span><span class="op">)</span>,</span>
<span>    labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"&lt;=2500"</span>, <span class="st">"2501-3000"</span>, <span class="st">"3001-3500"</span>, <span class="st">"&gt;3500"</span><span class="op">)</span></span>
<span>  <span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Summarize dataset by the newly created variable `bwt4`</span></span>
<span><span class="va">data.o4</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">bwt4</span>, <span class="va">weight</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">bwt4</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise_all.html">summarize_at</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/vars.html">vars</a></span><span class="op">(</span><span class="va">weight</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>min <span class="op">=</span> <span class="va">min</span>, max <span class="op">=</span> <span class="va">max</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  bwt4        min   max
  &lt;fct&gt;     &lt;dbl&gt; &lt;dbl&gt;
1 &lt;=2500      709  2495
2 2501-3000  2523  2992
3 3001-3500  3005  3487
4 &gt;3500      3544  4990</code></pre>
</div>
</div>
</section><section id="creating-an-ordinal-variable" class="level3" data-number="4.1.3"><h3 data-number="4.1.3" class="anchored" data-anchor-id="creating-an-ordinal-variable">
<span class="header-section-number">4.1.3</span> Creating an Ordinal Variable</h3>
<p>Create an ordinal variable and define the levels of the variable.</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb80"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Create and define the levels of ordinal variable</span></span>
<span><span class="va">lev</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"&gt;3500"</span>, <span class="st">"3001-3500"</span>, <span class="st">"2501-3000"</span>, <span class="st">"&lt;=2500"</span><span class="op">)</span></span>
<span><span class="va">data.o4</span> <span class="op">&lt;-</span> <span class="va">data.o4</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>bwt4a <span class="op">=</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_relevel.html">fct_relevel</a></span><span class="op">(</span><span class="va">bwt4</span>, <span class="va">lev</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>bwt4a <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">ordered</a></span><span class="op">(</span><span class="va">bwt4a</span>, levels <span class="op">=</span> <span class="va">lev</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Check the structure of the new variable</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">data.o4</span><span class="op">$</span><span class="va">bwt4a</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code> Ord.factor w/ 4 levels "&gt;3500"&lt;"3001-3500"&lt;..: 3 3 3 3 3 3 3 3 3 3 ...</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb82"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Check the levels of `bwt4`</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">data.o4</span><span class="op">$</span><span class="va">bwt4</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] "&lt;=2500"    "2501-3000" "3001-3500" "&gt;3500"    </code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb84"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Check the levels of `bwt4a`</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">data.o4</span><span class="op">$</span><span class="va">bwt4a</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] "&gt;3500"     "3001-3500" "2501-3000" "&lt;=2500"   </code></pre>
</div>
</div>
</section></section><section id="baseline-logit-model" class="level2" data-number="4.2"><h2 data-number="4.2" class="anchored" data-anchor-id="baseline-logit-model">
<span class="header-section-number">4.2</span> Baseline Logit Model</h2>
<p>The Baseline Logit Model, also known as the Multinomial Logistic Regression Model, is used to handle situations where the outcome variable is nominal with more than two categories. This model extends the binary logistic regression model to multiple categories by modeling the log-odds of each category relative to a baseline category.</p>
<p>This exercise demonstrates how to replicate the baseline logit model (unconstrained) which requires a dataset with an outcome variable without ordering. In this dataset <code>data.o4</code>, a new variable <code>bwt4b</code> without ordering is created from <code>bwt4</code> by re-leveling the factors according to the specified levels (<code>lev</code>).</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb86"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Create new variable and re-leveling according to the specified levels</span></span>
<span><span class="va">data.o4</span> <span class="op">&lt;-</span> <span class="va">data.o4</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>bwt4b <span class="op">=</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_relevel.html">fct_relevel</a></span><span class="op">(</span><span class="va">bwt4</span>, <span class="va">lev</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Fit the model</span></span>
<span><span class="va">bl.mod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/VGAM/man/vglm.html">vglm</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">bwt4</span> <span class="op">~</span> <span class="va">smoke</span>, family <span class="op">=</span> <span class="va">multinomial</span>, data <span class="op">=</span> <span class="va">data.o4</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">bl.mod</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
Call:
vglm(formula = bwt4 ~ smoke, family = multinomial, data = data.o4)

Coefficients: 
              Estimate Std. Error z value Pr(&gt;|z|)   
(Intercept):1  -0.1881     0.2511  -0.749  0.45392   
(Intercept):2  -0.4643     0.2721  -1.707  0.08791 . 
(Intercept):3  -0.1881     0.2511  -0.749  0.45392   
smoke:1         1.1914     0.4328   2.753  0.00591 **
smoke:2         0.8390     0.4769   1.759  0.07853 . 
smoke:3         0.6234     0.4613   1.351  0.17658   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Names of linear predictors: log(mu[,1]/mu[,4]), log(mu[,2]/mu[,4]), 
log(mu[,3]/mu[,4])

Residual deviance: 510.9718 on 561 degrees of freedom

Log-likelihood: -255.4859 on 561 degrees of freedom

Number of Fisher scoring iterations: 4 

No Hauck-Donner effect found in any of the estimates


Reference group is level  4  of the response</code></pre>
</div>
</div>
<hr>
<ul>
<li>
<code>smoke:1</code> with an estimate of 1.1914 implies a positive effect of smoking on the probability of being in the first category (<code>&lt;=2500</code>) relative to the reference category (<code>&gt;3500</code>).</li>
<li>
<code>smoke:2</code> and <code>smoke:3</code> have positive estimates, suggesting an increased likelihood of being in these categories as well due to smoking.</li>
</ul>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb88"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Calculate the exponentiated coefficients (RRR)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">bl.mod</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>(Intercept):1 (Intercept):2 (Intercept):3       smoke:1       smoke:2 
    0.8285714     0.6285714     0.8285714     3.2915361     2.3140496 
      smoke:3 
    1.8652038 </code></pre>
</div>
</div>
<hr>
<ul>
<li>For <code>smoke:1</code>, the RRR is 3.2915, meaning smokers are about 3.29 times more likely to be in the lowest birth weight category (<code>&lt;=2500</code>) compared to the reference category (<code>&gt;3500</code>).</li>
</ul></section><section id="continuation-ratio-model" class="level2" data-number="4.3"><h2 data-number="4.3" class="anchored" data-anchor-id="continuation-ratio-model">
<span class="header-section-number">4.3</span> Continuation Ratio Model</h2>
<p>The Continuation Ratio Model is another approach to modeling ordinal response data, particularly useful when the response categories have a natural order and when the sequential nature of the response process makes clinical or logical sense. This model is different from other ordinal logistic models in that it models the log-odds of being in a particular category given that the respondent has not been in any previous categories. The model is used to analyze ordinal response data by comparing categories sequentially. In this case, the weight categories are compared in the following manner:</p>
<ol type="1">
<li>Compare <code>bwt &gt;= 3500</code> vs.&nbsp;<code>bwt = 3000-3500</code>
</li>
<li>Compare <code>bwt &gt;= 3500</code> and <code>bwt = 3000-3500</code> vs.&nbsp;<code>bwt = 2500-3000</code>
</li>
<li>Compare <code>bwt &gt;= 3500</code> and <code>bwt = 3000-3500</code> and <code>bwt = 2500-3000</code> vs.&nbsp;<code>bwt &lt; 2500</code>
</li>
</ol>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb90"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Check the distribution of weight categories</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">data.o4</span><span class="op">$</span><span class="va">bwt4</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
   &lt;=2500 2501-3000 3001-3500     &gt;3500 
       59        38        46        46 </code></pre>
</div>
</div>
<section id="first-model" class="level3" data-number="4.3.1"><h3 data-number="4.3.1" class="anchored" data-anchor-id="first-model">
<span class="header-section-number">4.3.1</span> First Model</h3>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb92"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Filter the dataset to include only the weight categories `&gt;3500` and `3001-3500`</span></span>
<span><span class="va">data.o4a</span> <span class="op">&lt;-</span> <span class="va">data.o4</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">bwt4a</span> <span class="op">==</span> <span class="st">'&gt;3500'</span> <span class="op">|</span> <span class="va">bwt4a</span> <span class="op">==</span> <span class="st">'3001-3500'</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Check the distribution of weight categories</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">data.o4a</span><span class="op">$</span><span class="va">bwt4a</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
    &gt;3500 3001-3500 2501-3000    &lt;=2500 
       46        46         0         0 </code></pre>
</div>
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb94"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Fit the first model that predicts `bwt4a` based on `smoke`</span></span>
<span><span class="va">cr.mod1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">bwt4a</span> <span class="op">~</span> <span class="va">smoke</span>, </span>
<span>               family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span><span class="st">'logit'</span><span class="op">)</span>, </span>
<span>               data <span class="op">=</span> <span class="va">data.o4a</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">cr.mod1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = bwt4a ~ smoke, family = binomial(link = "logit"), 
    data = data.o4a)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)  -0.1881     0.2511  -0.749    0.454
smoke         0.6234     0.4613   1.351    0.177

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 127.54  on 91  degrees of freedom
Residual deviance: 125.68  on 90  degrees of freedom
AIC: 129.68

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
</section><section id="second-model" class="level3" data-number="4.3.2"><h3 data-number="4.3.2" class="anchored" data-anchor-id="second-model">
<span class="header-section-number">4.3.2</span> Second Model</h3>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb96"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Filter the dataset to include the weight categories `&gt;3500`, `3001-3500`, and `2501-3000`</span></span>
<span><span class="va">data.o4b</span> <span class="op">&lt;-</span> <span class="va">data.o4</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">bwt4</span> <span class="op">==</span> <span class="st">'&gt;3500'</span> <span class="op">|</span> <span class="va">bwt4</span> <span class="op">==</span> <span class="st">'3001-3500'</span> <span class="op">|</span> <span class="va">bwt4</span> <span class="op">==</span> <span class="st">'2501-3000'</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Recode `bwt4a` variable into a new variable `bwt4b`</span></span>
<span><span class="va">data.o4b</span> <span class="op">&lt;-</span> <span class="va">data.o4b</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>bwt4b <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">bwt4a</span> <span class="op">==</span> <span class="st">'&gt;3500'</span>, <span class="fl">0</span>, <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">bwt4a</span> <span class="op">==</span> <span class="st">'3001-3500'</span>, <span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Check the distribution of weight categories</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">data.o4b</span><span class="op">$</span><span class="va">bwt4b</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
 0  1 
92 38 </code></pre>
</div>
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb98"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Fit the second model with the recoded `bwt4b` as the dependent variable and `smoke` as the independent variable</span></span>
<span><span class="va">cr.mod2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">bwt4b</span> <span class="op">~</span> <span class="va">smoke</span>, </span>
<span>               family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span><span class="st">'logit'</span><span class="op">)</span>, </span>
<span>               data <span class="op">=</span> <span class="va">data.o4b</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">cr.mod2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = bwt4b ~ smoke, family = binomial(link = "logit"), 
    data = data.o4b)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -1.0678     0.2471  -4.321 1.56e-05 ***
smoke         0.5082     0.3991   1.273    0.203    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 157.09  on 129  degrees of freedom
Residual deviance: 155.49  on 128  degrees of freedom
AIC: 159.49

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<section id="third-model" class="level4" data-number="4.3.2.1"><h4 data-number="4.3.2.1" class="anchored" data-anchor-id="third-model">
<span class="header-section-number">4.3.2.1</span> Third Model</h4>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb100"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Recode `bwt4a` variable into `bwt4c` where all categories are grouped into a new variable</span></span>
<span><span class="va">data.o4c</span> <span class="op">&lt;-</span> <span class="va">data.o4</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>bwt4c <span class="op">=</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_recode.html">fct_recode</a></span><span class="op">(</span><span class="va">bwt4a</span>, </span>
<span>                            gp0 <span class="op">=</span> <span class="st">'&gt;3500'</span>,</span>
<span>                            gp0 <span class="op">=</span> <span class="st">'3001-3500'</span>,</span>
<span>                            gp0 <span class="op">=</span> <span class="st">'3001-3500'</span>,</span>
<span>                            gp0 <span class="op">=</span> <span class="st">'2501-3000'</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Check the distribution of weight categories</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">data.o4c</span><span class="op">$</span><span class="va">bwt4c</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
   gp0 &lt;=2500 
   130     59 </code></pre>
</div>
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb102"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Fit the third model to compare the recoded groups with `smoke` as the predictor</span></span>
<span><span class="va">cr.mod3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">bwt4c</span> <span class="op">~</span> <span class="va">smoke</span>, </span>
<span>               family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span><span class="st">'logit'</span><span class="op">)</span>, </span>
<span>               data <span class="op">=</span> <span class="va">data.o4c</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">cr.mod3</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = bwt4c ~ smoke, family = binomial(link = "logit"), 
    data = data.o4c)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -1.0871     0.2147  -5.062 4.14e-07 ***
smoke         0.7041     0.3196   2.203   0.0276 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 234.67  on 188  degrees of freedom
Residual deviance: 229.80  on 187  degrees of freedom
AIC: 233.8

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
</section></section><section id="conclusion" class="level3" data-number="4.3.3"><h3 data-number="4.3.3" class="anchored" data-anchor-id="conclusion">
<span class="header-section-number">4.3.3</span> Conclusion</h3>
<p>The three estimates from the different continuation-ratio models are quite similar, with values around 0.6. These estimates indicate that the odds of a birth in the next lower weight category relative to the higher weight categories among women who smoked during pregnancy is about 1.8 times that of women who did not smoke. In summary, smoking during pregnancy consistently increases the odds of having a baby in a lower weight category by approximately 1.8 times across the different comparisons made using the continuation-ratio model.</p>
</section></section></section></main><!-- /main column -->
&nbsp;
<hr>
<p style="text-align: center;">A dedicated work by Dr Muhammad Saufi</p>

<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- Add font awesome icons --><p style="text-align: center;">
    <a href="https://www.facebook.com/drsaufimbbch/" class="fa fa-facebook"></a>
    <a href="https://github.com/drsaufi" class="fa fa-github"></a>
    <a href="mailto:drsaufimbbch@gmail.com" class="fa fa-envelope"></a>
</p>

&nbsp;
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>